function esc(value = '') {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function shell({ title, subtitle, body, appointment = null }) {
  const appointmentJson = appointment ? `<script type="application/json" id="calendar-operation-appointment">${JSON.stringify(appointment).replace(/</g, '\\u003c')}</script>` : '';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>
:root{color-scheme:light;--ink:#20322b;--muted:#6c7d75;--paper:#f7f5ef;--panel:#fffdf9;--line:#dfe5df;--leaf:#496b5a;--danger:#8a3f3f}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.shell{max-width:900px;margin:0 auto;padding:24px 16px 42px}.top{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;margin-bottom:16px}.top h1{margin:0;font-size:1.5rem}.top p{margin:5px 0 0;color:var(--muted)}a{color:var(--leaf);font-weight:700;text-decoration:none}.panel{background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:18px;margin-bottom:14px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.field{display:grid;gap:6px}.wide{grid-column:1/-1}label{font-size:.82rem;font-weight:750}input,select,textarea{width:100%;border:1px solid var(--line);border-radius:10px;padding:10px;background:#fff;color:var(--ink);font:inherit}textarea{min-height:110px;resize:vertical}.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:14px}.button{border:1px solid var(--leaf);border-radius:999px;padding:9px 14px;background:var(--leaf);color:#fff;font:inherit;font-weight:750;cursor:pointer}.button.secondary{background:#fff;color:var(--leaf)}.button.danger{border-color:var(--danger);background:var(--danger)}.button:disabled{opacity:.5}.status{margin-top:12px;padding:10px 12px;border:1px solid var(--line);border-radius:10px;color:var(--muted);background:#fff}.status.error{color:var(--danger)}.results{display:grid;gap:7px;margin-top:8px}.result{border:1px solid var(--line);border-radius:10px;padding:9px;background:#fff;text-align:left;cursor:pointer}.meta{font-size:.82rem;color:var(--muted);line-height:1.5}.review{display:grid;gap:6px}.review div{display:flex;justify-content:space-between;gap:20px;border-bottom:1px solid var(--line);padding:7px 0}.review div:last-child{border-bottom:0}@media(max-width:650px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}.top{flex-direction:column}}
</style><script src="/calendar/operations/client.js" defer></script></head><body><div class="shell"><header class="top"><div><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div><a href="/calendar/read-only">← Calendar</a></header>${body}${appointmentJson}</div></body></html>`;
}

function renderNewBookingPage({ operator, date = '' } = {}) {
  const body = `<section class="panel"><p class="meta">Authenticated operator: <strong>${esc(operator?.displayName)}</strong> • ${esc(operator?.calendarRole)} • source <code>shiloh_calendar</code>. Availability and conflict authority comes from canonical Shiloh state; Google synchronization happens only after canonical commit.</p></section>
<section class="panel" data-calendar-operation-page="new"><div class="grid">
<div class="field"><label for="date">Date</label><input id="date" type="date" value="${esc(date)}"></div>
<div class="field"><label for="time">Start time</label><input id="time" type="time" step="300"></div>
<div class="field wide"><label for="client-search">Canonical client</label><div class="actions"><input id="client-search" type="search" placeholder="Name or mobile"><button class="button secondary" type="button" data-client-search>Find client</button></div><div class="results" data-client-results></div><input id="client-id" type="hidden"></div>
<div class="field"><label for="service">Service</label><select id="service"><option value="">Choose service</option></select></div>
<div class="field"><label for="staff">Practitioner</label><select id="staff" disabled><option value="">Choose service first</option></select></div>
</div><div class="actions"><button class="button secondary" type="button" data-preview-create>Review</button><button class="button" type="button" data-create disabled>Create canonical booking</button></div><div class="status" data-status>Choose one canonical client, service, practitioner and time.</div><div class="review" data-review hidden></div></section>`;
  return shell({ title: 'Create Shiloh booking', subtitle: 'Operational Calendar • authenticated canonical mutation', body });
}

function renderAppointmentPage({ operator, appointment } = {}) {
  const date = appointment?.startsAt ? new Intl.DateTimeFormat('en-CA', { timeZone: 'Africa/Johannesburg', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date(appointment.startsAt)) : '';
  const time = appointment?.startsAt ? new Intl.DateTimeFormat('en-GB', { timeZone: 'Africa/Johannesburg', hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date(appointment.startsAt)) : '';
  const body = `<section class="panel"><p class="meta">Authenticated operator: <strong>${esc(operator?.displayName)}</strong> • ${esc(operator?.calendarRole)} • source <code>shiloh_calendar</code>.</p><div class="review"><div><span>Appointment</span><strong>#${esc(appointment?.appointmentId)}</strong></div><div><span>Client</span><strong>${esc(appointment?.clientName)}</strong></div><div><span>Service</span><strong>${esc(appointment?.serviceName)}</strong></div><div><span>Practitioner</span><strong>${esc(appointment?.staffName)}</strong></div><div><span>Status</span><strong>${esc(appointment?.status)}</strong></div></div></section>
<section class="panel" data-calendar-operation-page="appointment" data-appointment-id="${esc(appointment?.appointmentId)}"><h2>Edit</h2><div class="grid"><div class="field wide"><label for="title">Title</label><input id="title" maxlength="160" value="${esc(appointment?.title || '')}"></div><div class="field wide"><label for="notes">Notes</label><textarea id="notes" maxlength="4000">${esc(appointment?.notes || '')}</textarea></div></div><div class="actions"><button class="button" type="button" data-edit>Save edit</button></div>
<hr><h2>Reschedule</h2><div class="grid"><div class="field"><label for="date">Date</label><input id="date" type="date" value="${esc(date)}"></div><div class="field"><label for="time">Start time</label><input id="time" type="time" step="300" value="${esc(time)}"></div></div><div class="actions"><button class="button" type="button" data-reschedule>Reschedule</button></div>
<hr><h2>Cancel</h2><div class="field"><label for="cancel-reason">Reason</label><input id="cancel-reason" maxlength="500" placeholder="Cancellation reason"></div><div class="actions"><button class="button danger" type="button" data-cancel>Cancel appointment</button></div>
<hr><h2>Provider recovery</h2><p class="meta">Canonical Shiloh state remains authoritative. Use retry only to re-queue failed or stale Google synchronization for this appointment.</p><div class="actions"><button class="button secondary" type="button" data-sync-retry>Retry Google sync</button></div><div class="status" data-status>Canonical changes commit first. Google synchronization is queued, auditable and retryable.</div></section>`;
  return shell({ title: `Manage appointment #${appointment?.appointmentId}`, subtitle: 'Operational Calendar • authenticated lifecycle mutation', body, appointment });
}

function clientScript() {
  return `(function(){'use strict';
var API='/calendar/operations',AUTH='/calendar/staff-auth';
function q(s){return document.querySelector(s)}function status(m,e){var n=q('[data-status]');if(n){n.textContent=m;n.classList.toggle('error',!!e)}}
function key(){if(window.crypto&&crypto.randomUUID)return crypto.randomUUID();return Date.now().toString(36)+Math.random().toString(36).slice(2)+Math.random().toString(36).slice(2)}
function mutationKey(button,namespace,payload){var signature=String(namespace)+'|'+JSON.stringify(payload||{});if(button.dataset.shilohMutationSignature!==signature||!button.dataset.shilohMutationKey){button.dataset.shilohMutationSignature=signature;button.dataset.shilohMutationKey=key()}return button.dataset.shilohMutationKey}
function clearMutationKey(button){delete button.dataset.shilohMutationSignature;delete button.dataset.shilohMutationKey}
async function json(r){try{return await r.json()}catch(_){return {}}}
async function post(url,payload,mutating,idempotencyKey){var headers={'Content-Type':'application/json','Accept':'application/json'};if(mutating){var c=await post(AUTH+'/csrf',{},false);if(!c.ok)throw new Error('SESSION');var cb=await json(c);headers['x-shiloh-csrf-token']=cb.csrfToken;headers['x-shiloh-idempotency-key']=idempotencyKey||key()}return fetch(url,{method:'POST',credentials:'same-origin',cache:'no-store',headers:headers,body:JSON.stringify(payload||{})})}
function lock(button,yes){if(button)button.disabled=!!yes}
async function initNew(){var optionsResponse=await fetch(API+'/options',{credentials:'same-origin',cache:'no-store',headers:{'Accept':'application/json'}}),options=await json(optionsResponse);if(!optionsResponse.ok){status(options.error||'Calendar booking options unavailable.',true);return}var service=q('#service'),staff=q('#staff');(options.services||[]).forEach(function(s){var o=document.createElement('option');o.value=s.id;o.textContent=s.name;service.appendChild(o)});service.addEventListener('change',function(){staff.innerHTML='<option value="">Choose practitioner</option>';var id=Number(service.value),svc=(options.services||[]).find(function(x){return Number(x.id)===id});if(!svc){staff.disabled=true;return}var allowed=new Set((svc.staffIds||[]).map(Number));(options.staff||[]).filter(function(x){return allowed.has(Number(x.id))}).forEach(function(p){var o=document.createElement('option');o.value=p.id;o.textContent=p.displayName;staff.appendChild(o)});staff.disabled=false;q('[data-create]').disabled=true});
q('[data-client-search]').addEventListener('click',async function(){var query=String(q('#client-search').value||'').trim();var r=await post(API+'/client-search',{query:query},false),b=await json(r),box=q('[data-client-results]');box.textContent='';if(!r.ok){status(b.error||'Client search unavailable.',true);return}(b.clients||[]).forEach(function(c){var btn=document.createElement('button');btn.type='button';btn.className='result';btn.textContent=c.displayName+' — CRM #'+c.id+(c.contactHint?' — '+c.contactHint:'');btn.addEventListener('click',function(){q('#client-id').value=c.id;status('Selected '+c.displayName+' — CRM #'+c.id);box.textContent=''});box.appendChild(btn)});if(!(b.clients||[]).length)status('No canonical client matched. Use Christel emergency booking for guarded new-client creation.',true)});
q('[data-preview-create]').addEventListener('click',async function(){var payload={clientId:Number(q('#client-id').value),serviceId:Number(service.value),staffId:Number(staff.value),date:q('#date').value,time:q('#time').value};var r=await post(API+'/preview',payload,false),b=await json(r);if(!r.ok){status(b.error||b.message||'Slot unavailable.',true);q('[data-create]').disabled=true;return}var review=q('[data-review]');review.hidden=false;review.innerHTML='<div><span>Client</span><strong>'+b.review.client.displayName+'</strong></div><div><span>Service</span><strong>'+b.review.service.name+'</strong></div><div><span>Practitioner</span><strong>'+b.review.practitioner.displayName+'</strong></div><div><span>Time</span><strong>'+new Date(b.review.startsAt).toLocaleString('en-ZA',{timeZone:'Africa/Johannesburg'})+'</strong></div>';q('[data-create]').disabled=false;status('Canonical Shiloh state is available. Google has not been consulted as booking authority.')});
q('[data-create]').addEventListener('click',async function(){var btn=this;lock(btn,true);var payload={clientId:Number(q('#client-id').value),serviceId:Number(service.value),staffId:Number(staff.value),date:q('#date').value,time:q('#time').value},idem=mutationKey(btn,'create',payload);try{var r=await post(API+'/appointments',payload,true,idem),b=await json(r);if(!r.ok){status(b.error||'Booking failed. Retrying the unchanged request is safe.',true);lock(btn,false);return}clearMutationKey(btn);status('Canonical booking #'+b.appointmentId+' created. Provider sync: '+b.providerSync);window.location.assign('/calendar/read-only')}catch(_){status('Secure booking request was interrupted. Retry the unchanged request; Shiloh will reuse the same idempotency key.',true);lock(btn,false)}})}
async function initAppointment(){var root=q('[data-calendar-operation-page="appointment"]'),id=Number(root.dataset.appointmentId);async function mutate(path,payload,button){lock(button,true);var idem=mutationKey(button,path,payload);try{var r=await post(API+'/appointments/'+id+'/'+path,payload,true,idem),b=await json(r);if(!r.ok){status(b.error||'Calendar mutation failed. Retrying the unchanged request is safe.',true);lock(button,false);return}clearMutationKey(button);status('Canonical appointment updated. Provider sync: '+b.providerSync);if(path==='cancel')setTimeout(function(){window.location.assign('/calendar/read-only')},300);else lock(button,false)}catch(_){status('Secure Calendar mutation was interrupted. Retry the unchanged request; Shiloh will reuse the same idempotency key.',true);lock(button,false)}}
q('[data-edit]').addEventListener('click',function(){mutate('edit',{title:q('#title').value,notes:q('#notes').value},this)});q('[data-reschedule]').addEventListener('click',function(){mutate('reschedule',{date:q('#date').value,time:q('#time').value},this)});q('[data-cancel]').addEventListener('click',function(){if(confirm('Cancel this canonical Shiloh appointment?'))mutate('cancel',{reason:q('#cancel-reason').value},this)});var retry=q('[data-sync-retry]');if(retry)retry.addEventListener('click',async function(){var btn=this,payload={appointmentId:id},idem=mutationKey(btn,'sync_retry',payload);lock(btn,true);try{var r=await post(API+'/sync/retry',payload,true,idem),b=await json(r);if(!r.ok){status(b.error||'Provider retry could not be queued. Retrying the unchanged request is safe.',true);lock(btn,false);return}clearMutationKey(btn);status('Google synchronization re-queued. Canonical Shiloh appointment state was not changed.');lock(btn,false)}catch(_){status('Provider retry request was interrupted. Retry safely with the same idempotency key.',true);lock(btn,false)}})}
var page=q('[data-calendar-operation-page]');if(!page)return;if(page.dataset.calendarOperationPage==='new')initNew().catch(function(){status('Calendar operations unavailable.',true)});else initAppointment().catch(function(){status('Calendar operations unavailable.',true)});
})();`;
}
module.exports = { renderNewBookingPage, renderAppointmentPage, clientScript };
