function calendarAppointmentEndTimeClientScript() {
  return `(function(){'use strict';
var API='/calendar/operations';var AUTH='/calendar/staff-auth';
function one(s,r){return(r||document).querySelector(s);}function all(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s));}
function operationId(){if(window.crypto&&typeof window.crypto.randomUUID==='function')return window.crypto.randomUUID();return'E'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2);}
async function json(r){try{return await r.json();}catch(_e){return{};}}
async function csrf(){var r=await fetch(AUTH+'/csrf',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','Accept':'application/json'},body:'{}'});var b=await json(r);if(!r.ok||!b.csrfToken)throw new Error('Your secure Calendar session has expired.');return b.csrfToken;}
async function read(path){var r=await fetch(API+path,{credentials:'same-origin',cache:'no-store',headers:{'Accept':'application/json'}});var b=await json(r);if(!r.ok){var e=new Error(b.error||'The appointment is unavailable.');e.code=b.code;throw e;}return b;}
async function post(path,payload){var token=await csrf();var r=await fetch(API+path,{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','Accept':'application/json','x-shiloh-csrf-token':token},body:JSON.stringify(payload||{})});token='';var b=await json(r);if(!r.ok){var e=new Error(b.error||'The end-time adjustment failed closed.');e.code=b.code;e.details=b.details;throw e;}return b;}
function appointmentId(card){var raw=String(card&&card.dataset.eventId||'');var m=raw.match(/^appointment-(\\d+)$/);return m?Number(m[1]):null;}
function localParts(value){var d=new Date(value);if(Number.isNaN(d.getTime()))return{value:'',label:''};var parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Johannesburg',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(d),x={};parts.forEach(function(p){x[p.type]=p.value;});return{value:x.year+'-'+x.month+'-'+x.day+'T'+x.hour+':'+x.minute,label:x.year+'-'+x.month+'-'+x.day+' '+x.hour+':'+x.minute};}
function iso(value){if(!/^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}$/.test(String(value||'')))throw new Error('Choose a valid end date and time.');var d=new Date(String(value)+':00+02:00');if(Number.isNaN(d.getTime()))throw new Error('Choose a valid end date and time.');return d.toISOString();}
function globalStatus(message,tone){var n=one('[data-calendar-operation-status]');if(n){n.textContent=message||'';n.dataset.tone=tone||'ready';}}
function ensureStyles(){if(one('[data-end-time-styles]'))return;var s=document.createElement('style');s.dataset.endTimeStyles='true';s.textContent='.appointment-end-time-manage{display:grid!important;gap:10px!important}.appointment-end-time-manage label{display:grid;gap:6px;font-size:.78rem;font-weight:750}.appointment-end-time-manage input{width:100%;min-height:44px;border:1px solid var(--line-strong,#ccd7d0);border-radius:9px;padding:9px;font:inherit;background:#fff}.end-time-submit{min-height:44px;border:0;border-radius:9px;padding:10px 13px;background:var(--leaf-deep,#285945);color:#fff;font:inherit;font-weight:800;cursor:pointer}.end-time-state{padding:11px;border-radius:10px;background:var(--leaf-soft,#e7eee9);display:grid;gap:4px}.end-time-error{padding:10px;border-radius:9px;background:#f8eaea;color:#8a3f3f}.end-time-hint{font-size:.76rem;line-height:1.45;color:var(--muted,#6c7d75)}';document.head.appendChild(s);}
function ensureForm(panel){var form=one('[data-end-time-form]',panel);if(form)return form;form=document.createElement('form');form.className='panel-action visible appointment-end-time-manage';form.dataset.endTimeForm='true';form.innerHTML='<span class="eyebrow">Appointment timing</span><h3>Adjust end time</h3><div class="end-time-state"><strong data-end-time-appointment></strong><span data-end-time-start></span><span data-end-time-current></span></div><label>Effective end time<input name="endsAt" type="datetime-local" step="300" required></label><p class="end-time-hint">Finishing earlier frees the practitioner sooner. Extending later is rechecked against appointments, blocks, clinic hours and schedule authority. Conflicts fail closed.</p><div class="end-time-error" data-end-time-error hidden></div><button class="end-time-submit" type="submit">Save end time</button>';var actions=one('.panel-actions',panel);if(actions)actions.insertBefore(form,actions.firstChild);else one('.management-card',panel).appendChild(form);form.addEventListener('submit',submit);return form;}
async function load(card,panel){var id=appointmentId(card);if(!id)return;var form=ensureForm(panel),err=one('[data-end-time-error]',form);err.hidden=true;form.dataset.appointmentId=String(id);form.dataset.revision='';form.hidden=false;globalStatus('Loading current canonical appointment timing…','working');try{var b=await read('/appointments/'+id+'/end-time'),a=b.appointment||{};if(form.dataset.appointmentId!==String(id))return;form.dataset.revision=String(a.revision||'');one('[data-end-time-appointment]',form).textContent='Appointment #'+id;one('[data-end-time-start]',form).textContent='Start: '+localParts(a.startsAt).label;one('[data-end-time-current]',form).textContent='Current end: '+localParts(a.endsAt).label;form.elements.endsAt.value=localParts(a.endsAt).value;globalStatus('Current appointment timing loaded.','ready');}catch(e){form.hidden=true;globalStatus(e.message||'Appointment timing is unavailable.','error');}}
async function submit(e){e.preventDefault();var form=e.currentTarget,button=one('button[type="submit"]',form),err=one('[data-end-time-error]',form),id=Number(form.dataset.appointmentId),revision=String(form.dataset.revision||'');if(!id||!revision)return;err.hidden=true;button.disabled=true;try{await post('/appointments/'+id+'/end-time',{expectedRevision:revision,endsAt:iso(form.elements.endsAt.value),requestId:operationId()});globalStatus('Appointment end time saved. Refreshing canonical Calendar…','ready');window.location.reload();}catch(ex){err.textContent=ex.message||'Nothing was changed.';err.hidden=false;globalStatus(ex.message||'End-time adjustment failed closed.','error');button.disabled=false;}}
function install(){ensureStyles();document.addEventListener('shiloh:appointment-panel-open',function(event){var panel=event.target.closest('[data-calendar-management-panel]')||event.target;var card=event.detail&&event.detail.card;if(card&&panel)load(card,panel);});}
install();
})();`;
}

module.exports = { calendarAppointmentEndTimeClientScript };
