function calendarAppointmentDetailsClientScript() {
  return `(function(){'use strict';
function one(selector,root){return(root||document).querySelector(selector);}
function text(selector,root){var node=one(selector,root);return node?String(node.textContent||'').trim():'';}
function appointmentId(card){var raw=String(card&&card.dataset&&card.dataset.eventId||'');var match=raw.match(/^appointment-(\\d+)$/);return match?Number(match[1]):Number(card&&card.dataset&&card.dataset.appointmentId||0);}
function requestedAppointmentId(){try{var value=new URLSearchParams(window.location.search).get('appointment');var id=Number(value||0);return Number.isSafeInteger(id)&&id>0?id:0;}catch(_error){return 0;}}
function ensureDialog(){var dialog=one('[data-appointment-details-dialog]');if(dialog)return dialog;var holder=document.createElement('div');holder.innerHTML='<dialog class="appointment-details-dialog" data-appointment-details-dialog aria-labelledby="appointment-details-title"><section class="appointment-details-card"><header><div><span class="eyebrow">Appointment details</span><h2 id="appointment-details-title" data-details-title>Appointment</h2></div><button type="button" data-details-close aria-label="Close appointment details">×</button></header><div class="appointment-details-summary"><strong data-details-client></strong><span data-details-mobile></span><span data-details-service></span><span data-details-practitioner></span><span data-details-time></span><span data-details-status></span></div><div class="appointment-details-actions"><button type="button" data-details-edit hidden>Edit appointment</button><button type="button" data-details-done>Done</button></div></section></dialog>';dialog=holder.firstElementChild;document.body.appendChild(dialog);var style=document.createElement('style');style.textContent='.appointment-details-dialog{border:0;padding:0;background:transparent;max-width:none;max-height:none;width:100%;height:100%;margin:0}.appointment-details-dialog::backdrop{background:rgba(13,31,24,.42)}.appointment-details-card{position:absolute;right:0;top:0;height:100%;width:min(430px,100%);overflow:auto;background:var(--panel,#fff);padding:22px;box-shadow:-12px 0 40px rgba(20,45,35,.2)}.appointment-details-card header{display:flex;justify-content:space-between;gap:12px;align-items:start;border-bottom:1px solid var(--line,#dfe5df);padding-bottom:14px}.appointment-details-card h2{margin:3px 0;font-size:1.25rem}.appointment-details-card header button{width:44px;height:44px;border:1px solid var(--line,#dfe5df);border-radius:999px;background:#fff;font-size:1.15rem}.appointment-details-summary{margin:16px 0;padding:12px;border-radius:12px;background:var(--leaf-soft,#e7eee9);display:grid;gap:5px}.appointment-details-actions{display:flex;gap:9px;flex-wrap:wrap}.appointment-details-actions button{min-height:44px;border:1px solid var(--leaf-deep,#294b3e);border-radius:9px;padding:10px 13px;background:#fff;color:var(--leaf-deep,#294b3e);font:inherit;font-weight:800}.appointment-details-actions [data-details-edit]{background:var(--leaf-deep,#294b3e);color:#fff}.event-card[data-kind="appointment"]{cursor:pointer}@media(max-width:700px){.appointment-details-card{padding:16px}.event-card[data-kind="appointment"]{min-height:44px}}';document.head.appendChild(style);one('[data-details-close]',dialog).addEventListener('click',function(){dialog.close();});one('[data-details-done]',dialog).addEventListener('click',function(){dialog.close();});dialog.addEventListener('click',function(event){if(event.target===dialog)dialog.close();});return dialog;}
var activeCard=null;
function openDetails(card){var id=appointmentId(card);if(!id)return;activeCard=card;var dialog=ensureDialog();one('[data-details-title]',dialog).textContent='Appointment #'+id;one('[data-details-client]',dialog).textContent=card.dataset.clientName||text('h4',card)||'Client';one('[data-details-mobile]',dialog).textContent=card.dataset.clientMobile||text('.event-client-mobile',card)||'Contact unavailable';one('[data-details-service]',dialog).textContent=card.dataset.serviceName||text('.event-service-context span:last-child',card)||'Treatment unavailable';one('[data-details-practitioner]',dialog).textContent=card.dataset.practitionerNames||text('.event-practitioners',card)||'Practitioner unavailable';one('[data-details-time]',dialog).textContent=text('.event-time-range',card)||text('.event-time-start',card)||'';one('[data-details-status]',dialog).textContent=card.dataset.appointmentStatus||text('.event-state',card)||text('.kind-pill',card)||'Appointment';var edit=one('[data-details-edit]',dialog);var editable=card.dataset.appointmentManagementTarget==='true';edit.hidden=!editable;edit.onclick=editable?function(){dialog.close();card.dataset.detailsEditBypass='true';card.click();delete card.dataset.detailsEditBypass;}:null;if(!dialog.open)dialog.showModal();}
function cards(){return Array.prototype.slice.call(document.querySelectorAll('.event-card[data-kind="appointment"][data-canonical="true"]'));}
function enhance(){cards().forEach(function(card){if(card.dataset.appointmentDetailsReady==='true')return;card.dataset.appointmentDetailsReady='true';card.setAttribute('role','button');card.setAttribute('tabindex','0');var id=appointmentId(card);card.setAttribute('aria-label','View appointment details'+(id?' #'+id:''));});}
function openRequested(){var requested=requestedAppointmentId();if(!requested)return;var card=cards().find(function(item){return appointmentId(item)===requested;});if(card)openDetails(card);}
document.addEventListener('click',function(event){var card=event.target.closest&&event.target.closest('.event-card[data-kind="appointment"][data-canonical="true"]');if(!card||card.dataset.detailsEditBypass==='true'||event.target.closest('a,button,input,select,textarea,label'))return;event.preventDefault();event.stopImmediatePropagation();openDetails(card);},true);
document.addEventListener('keydown',function(event){var card=event.target.closest&&event.target.closest('.event-card[data-kind="appointment"][data-canonical="true"]');if(!card||event.target!==card||!['Enter',' '].includes(event.key))return;event.preventDefault();event.stopImmediatePropagation();openDetails(card);},true);
enhance();openRequested();})();`;
}

module.exports = { calendarAppointmentDetailsClientScript };
