function calendarOperationalMutationsClientScript() {
  return `(function(){'use strict';
var API='/calendar/operations';var AUTH='/calendar/staff-auth';var dragged=null;
function one(selector,root){return(root||document).querySelector(selector);}function all(selector,root){return Array.prototype.slice.call((root||document).querySelectorAll(selector));}
function operationId(){if(window.crypto&&typeof window.crypto.randomUUID==='function')return window.crypto.randomUUID();return'D'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2);}
function status(message,tone){var target=one('[data-calendar-operation-status]');if(!target)return;target.textContent=String(message||'');target.dataset.tone=tone||'ready';}
async function json(response){try{return await response.json();}catch(_error){return{};}}
async function csrf(){var response=await fetch(AUTH+'/csrf',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','Accept':'application/json'},body:'{}'});if(!response.ok)throw new Error('Your secure Calendar session has expired.');var body=await json(response);if(!body.csrfToken)throw new Error('A secure operation token could not be issued.');return body.csrfToken;}
async function request(path,method,payload){var token=await csrf();var response=await fetch(API+path,{method:method,credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','Accept':'application/json','x-shiloh-csrf-token':token},body:JSON.stringify(payload||{})});token='';var body=await json(response);if(!response.ok){var error=new Error(body.error||'The canonical Calendar operation failed closed.');error.code=body.code;throw error;}return body;}
function isoStart(date,time){var value=new Date(String(date)+'T'+String(time)+':00+02:00');if(Number.isNaN(value.getTime()))throw new Error('Choose a valid date and time.');return value.toISOString();}
function splitLocal(value){var date=new Date(value);if(Number.isNaN(date.getTime()))return{date:'',time:''};var parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Johannesburg',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(date);var map={};parts.forEach(function(part){map[part.type]=part.value;});return{date:map.year+'-'+map.month+'-'+map.day,time:map.hour+':'+map.minute};}
async function finish(work,message){status('Validating and saving against canonical Shiloh state…','working');try{await work();status(message||'Saved. Refreshing canonical Calendar…','ready');window.location.reload();}catch(error){status(error.message||'Nothing was changed. Reload Calendar and retry.','error');}}
function appointmentData(card){return{id:Number(card.dataset.appointmentId),revision:String(card.dataset.revision||''),staffIds:String(card.dataset.staffIds||'').split(',').map(Number).filter(Boolean),startsAt:card.dataset.startsAt||''};}
async function rescheduleAppointment(data,date,time){return request('/appointments/'+data.id+'/reschedule','POST',{expectedRevision:data.revision,startsAt:isoStart(date,time),requestId:operationId()});}
function askReschedule(card,forcedDate){var data=appointmentData(card);var current=splitLocal(data.startsAt);var date=forcedDate||window.prompt('New date (YYYY-MM-DD)',current.date);if(!date)return;var time=window.prompt('Exact new start time (HH:MM)',current.time);if(!time)return;finish(function(){return rescheduleAppointment(data,date,time);},'Appointment rescheduled. Refreshing canonical Calendar…');}
function askReassign(card){var data=appointmentData(card);var destination=window.prompt('Destination canonical practitioner ID');if(!destination)return;finish(function(){return request('/appointments/'+data.id+'/reassign','POST',{expectedRevision:data.revision,fromStaffId:data.staffIds.length===1?data.staffIds[0]:null,destinationStaffId:Number(destination),requestId:operationId()});},'Practitioner reassigned. Refreshing canonical Calendar…');}
function askCancel(card){var data=appointmentData(card);var reason=window.prompt('Cancellation reason');if(!reason)return;if(!window.confirm('Cancel appointment #'+data.id+' at its exact current revision? This does not send a client message.'))return;finish(function(){return request('/appointments/'+data.id+'/cancel','POST',{expectedRevision:data.revision,confirmation:{confirmed:true,appointmentId:data.id,revision:data.revision},reason:reason,requestId:operationId()});},'Appointment cancelled. Refreshing canonical Calendar…');}
function manageAppointment(button){var card=button.closest('[data-appointment-id]');if(!card)return;var action=String(window.prompt('Manage appointment: R = reschedule, A = reassign, C = cancel','R')||'').trim().toLowerCase();if(action==='r')askReschedule(card);else if(action==='a')askReassign(card);else if(action==='c')askCancel(card);}
function blockData(card){return{id:Number(card.dataset.blockId),revision:String(card.dataset.revision||''),staffId:Number(card.dataset.staffIds||0),locationId:card.dataset.locationId?Number(card.dataset.locationId):null,startsAt:card.dataset.startsAt||'',endsAt:card.dataset.endsAt||'',blockType:card.dataset.blockType||'other',title:card.dataset.title||'Operational block'};}
function blockPayload(data){var start=splitLocal(data.startsAt);var end=splitLocal(data.endsAt);var date=window.prompt('Block date (YYYY-MM-DD)',start.date);if(!date)return null;var starts=window.prompt('Block start (HH:MM)',start.time);if(!starts)return null;var ends=window.prompt('Block end (HH:MM)',end.time);if(!ends)return null;var title=window.prompt('Block title',data.title||'Operational block');if(!title)return null;return{staffId:data.staffId,locationId:data.locationId,startsAt:isoStart(date,starts),endsAt:isoStart(date,ends),blockType:data.blockType||'other',title:title,requestId:operationId()};}
function manageBlock(button){var card=button.closest('[data-block-id]');if(!card)return;var data=blockData(card);var action=String(window.prompt('Manage block: E = edit, R = remove','E')||'').trim().toLowerCase();if(action==='e'){var payload=blockPayload(data);if(!payload)return;payload.expectedRevision=data.revision;finish(function(){return request('/blocks/'+data.id,'PATCH',payload);},'Block updated. Refreshing canonical Calendar…');}else if(action==='r'&&window.confirm('Remove this exact canonical block? Appointments will not be moved or cancelled.')){finish(function(){return request('/blocks/'+data.id,'DELETE',{expectedRevision:data.revision,requestId:operationId()});},'Block removed. Refreshing canonical Calendar…');}}
function manageLeave(button){var card=button.closest('[data-leave-id]');if(!card)return;var id=Number(card.dataset.leaveId);var revision=String(card.dataset.revision||'');var locationId=card.dataset.locationId?Number(card.dataset.locationId):null;var action=String(window.prompt('Manage operational leave: E = edit, R = remove','E')||'').trim().toLowerCase();if(action==='e'){var date=window.prompt('Leave date (YYYY-MM-DD)',card.dataset.date||'');if(!date)return;var reason=window.prompt('Operational leave reason',card.dataset.reason||'Operational leave');if(!reason)return;finish(function(){return request('/leave/'+id,'PATCH',{expectedRevision:revision,date:date,reason:reason,locationId:locationId,requestId:operationId()});},'Leave updated. Refreshing canonical Calendar…');}else if(action==='r'&&window.confirm('Remove this exact operational leave record? Appointments will not be moved or cancelled.')){finish(function(){return request('/leave/'+id,'DELETE',{expectedRevision:revision,requestId:operationId()});},'Leave removed. Refreshing canonical Calendar…');}}
function addBlock(button){var staffId=Number(button.dataset.staffId);var date=button.dataset.date;var starts=window.prompt('Block start (HH:MM)','08:00');if(!starts)return;var ends=window.prompt('Block end (HH:MM)','09:00');if(!ends)return;var title=window.prompt('Block title','Operational block');if(!title)return;finish(function(){return request('/blocks','POST',{staffId:staffId,startsAt:isoStart(date,starts),endsAt:isoStart(date,ends),blockType:'other',title:title,requestId:operationId()});},'Block created. Refreshing canonical Calendar…');}
function addLeave(button){var staffId=Number(button.dataset.staffId);var date=window.prompt('Operational leave date (YYYY-MM-DD)',button.dataset.date||'');if(!date)return;var reason=window.prompt('Operational leave reason','Operational leave');if(!reason)return;finish(function(){return request('/leave','POST',{staffId:staffId,date:date,reason:reason,requestId:operationId()});},'Leave created. Refreshing canonical Calendar…');}
function dayOfWeek(date){return new Date(String(date)+'T12:00:00+02:00').getUTCDay();}
async function manageSchedule(button){var staffId=Number(button.dataset.staffId);var day=dayOfWeek(button.dataset.date);status('Loading current canonical working schedule…','working');try{var response=await fetch(API+'/staff/'+staffId+'/schedule/'+day,{credentials:'same-origin',cache:'no-store',headers:{'Accept':'application/json'}});var state=await json(response);if(!response.ok)throw new Error(state.error||'The current working schedule is unavailable.');var mode=String(window.prompt('Schedule mode: window, closed, or inherit',state.mode||'inherit')||'').trim().toLowerCase();if(!mode)return;var payload={mode:mode,expectedRevision:state.revision,requestId:operationId()};if(mode==='window'){payload.startsLocal=window.prompt('Working start (HH:MM)',state.windows&&state.windows[0]?state.windows[0].startsLocal:'08:00');if(!payload.startsLocal)return;payload.endsLocal=window.prompt('Working end (HH:MM)',state.windows&&state.windows[0]?state.windows[0].endsLocal:'17:00');if(!payload.endsLocal)return;}finish(function(){return request('/staff/'+staffId+'/schedule/'+day,'PUT',payload);},'Working schedule updated. Refreshing canonical Calendar…');}catch(error){status(error.message||'The schedule operation failed closed.','error');}}
document.addEventListener('click',function(event){var button=event.target.closest('[data-calendar-operation]');if(!button)return;var action=button.dataset.calendarOperation;if(action==='manage-appointment')manageAppointment(button);else if(action==='manage-block')manageBlock(button);else if(action==='manage-leave')manageLeave(button);else if(action==='add-block')addBlock(button);else if(action==='add-leave')addLeave(button);else if(action==='manage-schedule')manageSchedule(button);});
all('[data-appointment-id][draggable="true"]').forEach(function(card){card.addEventListener('dragstart',function(event){dragged=appointmentData(card);event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',String(dragged.id));});card.addEventListener('dragend',function(){dragged=null;});});
all('[data-calendar-drop-target]').forEach(function(target){target.addEventListener('dragover',function(event){if(dragged){event.preventDefault();event.dataTransfer.dropEffect='move';}});target.addEventListener('drop',function(event){if(!dragged)return;event.preventDefault();var card=one('[data-appointment-id="'+dragged.id+'"]');var date=target.dataset.date;if(card&&date)askReschedule(card,date);dragged=null;});});
})();`;
}

module.exports = { calendarOperationalMutationsClientScript };
