function calendarAppointmentEndTimeClientScript() {
  return `(function(){'use strict';
var API='/calendar/operations';var AUTH='/calendar/staff-auth';
function one(s,r){return(r||document).querySelector(s);}function all(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s));}
function operationId(){if(window.crypto&&typeof window.crypto.randomUUID==='function')return window.crypto.randomUUID();return'E'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2);}
async function json(r){try{return await r.json();}catch(_e){return{};}}
async function csrf(){var r=await fetch(AUTH+'/csrf',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','Accept':'application/json'},body:'{}'});var b=await json(r);if(!r.ok||!b.csrfToken)throw new Error('Your secure Calendar session has expired.');return b.csrfToken;}
async function read(path){var r=await fetch(API+path,{credentials:'same-origin',cache:'no-store',headers:{'Accept':'application/json'}});var b=await json(r);if(!r.ok){var e=new Error(b.error||'The appointment is unavailable.');e.code=b.code;throw e;}return b;}
async function post(path,payload){var token=await csrf();var r=await fetch(API+path,{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','Accept':'application/json','x-shiloh-csrf-token':token},body:JSON.stringify(payload||{})});token='';var b=await json(r);if(!r.ok){var e=new Error(b.error||'The end-time adjustment failed closed.');e.code=b.code;e.details=b.details;throw e;}return b;}
function appointmentId(card){var raw=String(card&&card.dataset.eventId||'');var m=raw.match(/^appointment-(\\d+)$/);return m?Number(m[1]):null;}
function localParts(value){var d=new Date(value);if(Number.isNaN(d.getTime()))return{value:'',label:''};var parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Johannesburg',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(d),x={};parts.forEach(function(p){x[p.type]=p.value;});return{value:x.year+'-'+x.month+'-'+x.day+'T'+x.hour+':'+x.minute,label:x.year+'-'+x.month+'-'+x.day+' '+x.hour+':'+x.minute};}
function iso(value){if(!/^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}$/.test(String(value||'')))throw new Error('Choose a valid end date and time.');var d=new Date(String(value)+':00+02:00');if(Number.isNaN(d.getTime()))throw new Error('Choose a valid end date and time.');return d.toISOString();}
function globalStatus(message,tone){var n=one('[data-calendar-operation-status]');if(n){n.textContent=message||'';n.dataset.tone=tone||'ready';}}
function ensureStyles(){if(one('[data-end-time-styles]'))return;var s=document.createElement('style');s.dataset.endTimeStyles='true';s.textContent='.end-time-action{min-height:44px!important}.end-time-dialog{border:0;padding:0;background:transparent;max-width:none;max-height:none;width:100%;height:100%;margin:0}.end-time-dialog::backdrop{background:rgba(13,31,24,.42)}.end-time-card{position:absolute;right:0;top:0;height:100%;width:min(430px,100%);overflow:auto;background:var(--panel,#fffdf9);padding:22px;box-shadow:-12px 0 40px rgba(20,45,35,.2);color:var(--ink,#20322b)}.end-time-form{display:grid;gap:14px}.end-time-form label{display:grid;gap:6px;font-size:.78rem;font-weight:750}.end-time-form input{width:100%;min-height:44px;border:1px solid var(--line-strong,#ccd7d0);border-radius:9px;padding:9px;font:inherit;background:#fff}.end-time-submit{min-height:44px;border:0;border-radius:9px;padding:10px 13px;background:var(--leaf-deep,#285945);color:#fff;font:inherit;font-weight:800;cursor:pointer}.end-time-state{padding:11px;border-radius:10px;background:var(--leaf-soft,#e7eee9);display:grid;gap:4px}.end-time-error{padding:10px;border-radius:9px;background:#f8eaea;color:#8a3f3f}.end-time-hint{font-size:.76rem;line-height:1.45;color:var(--muted,#6c7d75)}@media(max-width:700px){.end-time-card{padding:16px}.end-time-action{min-height:44px!important}}';document.head.appendChild(s);}
function ensureDialog(){var d=one('[data-end-time-dialog]');if(d)return d;var h=document.createElement('div');h.innerHTML='<dialog class="end-time-dialog" data-end-time-dialog aria-labelledby="end-time-title"><section class="end-time-card"><header class="panel-head"><div><span class="eyebrow">Appointment timing</span><h2 id="end-time-title">Adjust end time</h2><span class="panel-hint">Updates canonical practitioner availability immediately.</span></div><button class="panel-close" type="button" data-end-time-close aria-label="Close">×</button></header><form class="end-time-form" data-end-time-form><div class="end-time-state"><strong data-end-time-appointment></strong><span data-end-time-start></span><span data-end-time-current></span></div><label>Effective end time<input name="endsAt" type="datetime-local" step="300" required></label><p class="end-time-hint">Finishing earlier frees the practitioner sooner. Extending later is rechecked against appointments, blocks, clinic hours and schedule authority where applicable. Conflicts fail closed.</p><div class="end-time-error" data-end-time-error hidden></div><button class="end-time-submit" type="submit">Save end time</button></form></section></dialog>';d=h.firstElementChild;document.body.appendChild(d);one('[data-end-time-close]',d).addEventListener('click',function(){d.close();});d.addEventListener('click',function(e){if(e.target===d)d.close();});d.addEventListener('cancel',function(){d.dataset.appointmentId='';d.dataset.revision='';});one('[data-end-time-form]',d).addEventListener('submit',submit);return d;}
async function open(card){var id=appointmentId(card);if(!id)return;var d=ensureDialog(),err=one('[data-end-time-error]',d);err.hidden=true;globalStatus('Loading current canonical appointment timing…','working');try{var b=await read('/appointments/'+id+'/end-time'),a=b.appointment||{};d.dataset.appointmentId=String(id);d.dataset.revision=String(a.revision||'');one('[data-end-time-appointment]',d).textContent='Appointment #'+id;one('[data-end-time-start]',d).textContent='Start: '+localParts(a.startsAt).label;one('[data-end-time-current]',d).textContent='Current end: '+localParts(a.endsAt).label;one('[data-end-time-form]',d).elements.endsAt.value=localParts(a.endsAt).value;globalStatus('Current appointment timing loaded.','ready');d.showModal();}catch(e){globalStatus(e.message||'Appointment timing is unavailable.','error');}}
async function submit(e){e.preventDefault();var d=ensureDialog(),form=e.currentTarget,button=one('button[type="submit"]',form),err=one('[data-end-time-error]',d),id=Number(d.dataset.appointmentId),revision=String(d.dataset.revision||'');if(!id||!revision)return;err.hidden=true;button.disabled=true;try{await post('/appointments/'+id+'/end-time',{expectedRevision:revision,endsAt:iso(form.elements.endsAt.value),requestId:operationId()});globalStatus('Appointment end time saved. Refreshing canonical Calendar…','ready');window.location.reload();}catch(ex){err.textContent=ex.message||'Nothing was changed.';err.hidden=false;globalStatus(ex.message||'End-time adjustment failed closed.','error');button.disabled=false;}}
function install(){ensureStyles();all('.event-card[data-kind="appointment"][data-event-id^="appointment-"]').forEach(function(card){var actions=one('.event-card-actions',card);if(!actions||one('[data-adjust-end-time]',card))return;var b=document.createElement('button');b.type='button';b.className='event-operation end-time-action';b.dataset.adjustEndTime='true';b.textContent='Adjust end time';b.addEventListener('click',function(){open(card);});actions.appendChild(b);});}
install();
})();`;
}

module.exports = { calendarAppointmentEndTimeClientScript };
