function calendarAppointmentTreatmentPriceClientScript() {
  return `(function(){'use strict';
var API='/calendar/operations';var AUTH='/calendar/staff-auth';
function one(s,r){return(r||document).querySelector(s);}
function operationId(){if(window.crypto&&typeof window.crypto.randomUUID==='function')return window.crypto.randomUUID();return'TP'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2);}
async function json(r){try{return await r.json();}catch(_e){return{};}}
async function csrf(){var r=await fetch(AUTH+'/csrf',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','Accept':'application/json'},body:'{}'});var b=await json(r);if(!r.ok||!b.csrfToken)throw new Error('Your secure Calendar session has expired.');return b.csrfToken;}
async function read(path){var r=await fetch(API+path,{credentials:'same-origin',cache:'no-store',headers:{'Accept':'application/json'}});var b=await json(r);if(!r.ok){var e=new Error(b.error||'The appointment treatment and price are unavailable.');e.code=b.code;throw e;}return b;}
async function patch(path,payload){var token=await csrf();var r=await fetch(API+path,{method:'PATCH',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','Accept':'application/json','x-shiloh-csrf-token':token},body:JSON.stringify(payload||{})});token='';var b=await json(r);if(!r.ok){var e=new Error(b.error||'The appointment correction failed closed.');e.code=b.code;e.details=b.details;throw e;}return b;}
function money(value){var n=Number(value);return Number.isFinite(n)?'R'+n.toFixed(2):'Price varies';}
function globalStatus(message,tone){var n=one('[data-calendar-operation-status]');if(n){n.textContent=message||'';n.dataset.tone=tone||'ready';}}
function ensureStyles(){if(one('[data-treatment-price-styles]'))return;var s=document.createElement('style');s.dataset.treatmentPriceStyles='true';s.textContent='.appointment-treatment-price{display:grid!important;gap:10px!important}.appointment-treatment-price label{display:grid;gap:6px;font-size:.78rem;font-weight:750}.appointment-treatment-price select,.appointment-treatment-price input{width:100%;min-height:44px;border:1px solid var(--line-strong,#ccd7d0);border-radius:9px;padding:9px;font:inherit;background:#fff}.treatment-price-current{padding:11px;border-radius:10px;background:var(--leaf-soft,#e7eee9);display:grid;gap:4px}.treatment-price-catalogue{font-size:.74rem;line-height:1.4;color:var(--muted,#6c7d75)}.treatment-price-error{padding:10px;border-radius:9px;background:#f8eaea;color:#8a3f3f}.treatment-price-submit{min-height:44px;border:0;border-radius:9px;padding:10px 13px;background:var(--leaf-deep,#285945);color:#fff;font:inherit;font-weight:800;cursor:pointer}@media(max-width:700px){.appointment-treatment-price select,.appointment-treatment-price input,.treatment-price-submit{min-height:44px;font-size:16px}}';document.head.appendChild(s);}
function ensureForm(panel){var form=one('[data-treatment-price-form]',panel);if(form)return form;form=document.createElement('form');form.className='panel-action visible appointment-treatment-price';form.dataset.treatmentPriceForm='true';form.innerHTML='<span class="eyebrow">Treatment &amp; price</span><h3>Correct this appointment</h3><div class="treatment-price-current"><strong data-treatment-price-current-service></strong><span data-treatment-price-current-price></span></div><label>Treatment<select name="serviceId" required></select></label><p class="treatment-price-catalogue" data-treatment-price-catalogue></p><label>Charged price (R)<input name="chargedPrice" type="number" min="0" max="9999999999.99" step="0.01" inputmode="decimal" required></label><p class="treatment-price-catalogue">This changes only this appointment. The treatment catalogue and its standard price stay under Services.</p><div class="treatment-price-error" data-treatment-price-error hidden></div><button class="treatment-price-submit" type="submit">Save treatment &amp; price</button>';var actions=one('.panel-actions',panel);if(actions)actions.insertBefore(form,actions.firstChild);else one('.management-card',panel).appendChild(form);form.addEventListener('submit',submit);form.elements.serviceId.addEventListener('change',function(){showCataloguePrice(form);});return form;}
function showCataloguePrice(form){var option=form.elements.serviceId.selectedOptions&&form.elements.serviceId.selectedOptions[0];var hint=one('[data-treatment-price-catalogue]',form);if(!option){hint.textContent='';return;}var standard=option.dataset.standardPrice;hint.textContent=option.dataset.variablePrice==='true'?'Services standard: variable price':standard===''?'Services standard: not set':'Services standard: '+money(standard);}
async function load(panel,appointment){var id=Number(appointment&&appointment.id);if(!id)return;var form=ensureForm(panel),error=one('[data-treatment-price-error]',form);form.hidden=false;error.hidden=true;form.dataset.appointmentId=String(id);form.dataset.revision='';globalStatus('Loading current appointment treatment and price…','working');try{var body=await read('/appointments/'+id+'/treatment-price'),current=body.appointment||{},services=body.catalogue||[];if(form.dataset.appointmentId!==String(id))return;form.dataset.revision=String(current.revision||'');var currentService=current.services&&current.services.length?current.services.map(function(x){return x.name;}).join(' + '):'Treatment unavailable';one('[data-treatment-price-current-service]',form).textContent=currentService;one('[data-treatment-price-current-price]',form).textContent='Charged: '+money(current.chargedPrice);form.elements.serviceId.innerHTML='';services.forEach(function(service){var option=document.createElement('option');option.value=String(service.id);option.textContent=service.name;option.dataset.standardPrice=service.standardPrice==null?'':String(service.standardPrice);option.dataset.variablePrice=service.variablePrice===true?'true':'false';form.elements.serviceId.appendChild(option);});var currentId=current.services&&current.services.length===1?Number(current.services[0].serviceId):0;if(currentId&&services.some(function(service){return Number(service.id)===currentId;}))form.elements.serviceId.value=String(currentId);form.elements.chargedPrice.value=current.chargedPrice==null?'':Number(current.chargedPrice).toFixed(2);showCataloguePrice(form);globalStatus('Current appointment treatment and price loaded.','ready');}catch(ex){form.hidden=true;globalStatus(ex.message||'Appointment treatment and price are unavailable.','error');}}
async function submit(event){event.preventDefault();var form=event.currentTarget,button=one('button[type="submit"]',form),error=one('[data-treatment-price-error]',form),id=Number(form.dataset.appointmentId),revision=String(form.dataset.revision||'');if(!id||!revision)return;error.hidden=true;button.disabled=true;try{await patch('/appointments/'+id+'/treatment-price',{expectedRevision:revision,serviceId:Number(form.elements.serviceId.value),chargedPrice:String(form.elements.chargedPrice.value||''),requestId:operationId()});globalStatus('Appointment treatment and charged price saved. Refreshing canonical Calendar…','ready');window.location.reload();}catch(ex){error.textContent=ex.message||'Nothing was changed.';error.hidden=false;globalStatus(ex.message||'Appointment correction failed closed.','error');button.disabled=false;}}
function install(){ensureStyles();document.addEventListener('shiloh:appointment-panel-open',function(event){var panel=event.target.closest('[data-calendar-management-panel]')||event.target;var appointment=event.detail&&event.detail.appointment;if(panel&&appointment)load(panel,appointment);});}
install();
})();`;
}

module.exports = { calendarAppointmentTreatmentPriceClientScript };
