'use strict';

function calendarAvailabilityPractitionerSelectClientScript() {
  return `(function(){'use strict';
var API='/calendar/operations';var AUTH='/calendar/staff-auth';
function one(selector,root){return(root||document).querySelector(selector);}function all(selector,root){return Array.prototype.slice.call((root||document).querySelectorAll(selector));}
function status(message,tone){var target=one('[data-calendar-operation-status]');if(!target)return;target.textContent=String(message||'');target.dataset.tone=tone||'ready';}
function operationId(){if(window.crypto&&typeof window.crypto.randomUUID==='function')return window.crypto.randomUUID();return'D'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2);}
function isoStart(date,time){var value=new Date(String(date)+'T'+String(time)+':00+02:00');if(Number.isNaN(value.getTime()))throw new Error('Choose a valid date and time.');return value.toISOString();}
function practitionerName(source,staffId){var lane=source&&source.closest?source.closest('.lane'):null;var heading=lane?one('h3',lane):null;if(heading&&heading.textContent)return heading.textContent.trim();var context=one('.view-practitioner[data-staff-id="'+staffId+'"]');return context&&context.textContent?context.textContent.trim():'Practitioner #'+staffId;}
function eligibleTargets(action,date){var seen={};var targets=[];all('[data-calendar-operation="'+action+'"]'+(date?'[data-date="'+CSS.escape(String(date))+'"]':'')).forEach(function(button){var staffId=Number(button.dataset.staffId);if(!Number.isSafeInteger(staffId)||staffId<1||seen[staffId])return;seen[staffId]=true;targets.push({staffId:staffId,name:practitionerName(button,staffId)});});return targets.sort(function(a,b){return a.name.localeCompare(b.name);});}
function clearSelector(){all('[data-availability-practitioner-field]').forEach(function(node){node.remove();});all('[data-availability-form]').forEach(function(form){delete form.dataset.availabilityPractitionerCreate;delete form.dataset.availabilitySourceStaffId;});}
function decorateCreateForm(kind,source){var panel=one('[data-calendar-availability-panel]');if(!panel||!panel.open)return;var form=one('[data-availability-form="'+kind+'"]',panel);if(!form||form.hidden)return;clearSelector();var action=kind==='block'?'add-block':'add-leave';var targets=eligibleTargets(action,source.dataset.date||'');if(!targets.length)return;var sourceStaffId=Number(source.dataset.staffId);form.dataset.availabilityPractitionerCreate='true';form.dataset.availabilitySourceStaffId=String(sourceStaffId);var label=document.createElement('label');label.dataset.availabilityPractitionerField='true';label.appendChild(document.createTextNode('Practitioner'));var select=document.createElement('select');select.name='practitionerStaffId';select.setAttribute('aria-label','Practitioner');targets.forEach(function(target){var option=document.createElement('option');option.value=String(target.staffId);option.textContent=target.name;if(target.staffId===sourceStaffId)option.selected=true;select.appendChild(option);});select.addEventListener('change',function(){var selected=targets.find(function(target){return String(target.staffId)===select.value;});var summary=one('[data-availability-practitioner]',panel);if(summary&&selected)summary.textContent=selected.name;});label.appendChild(select);form.insertBefore(label,form.firstChild);}
async function json(response){try{return await response.json();}catch(_error){return{};}}
async function csrf(){var response=await fetch(AUTH+'/csrf',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','Accept':'application/json'},body:'{}'});if(!response.ok)throw new Error('Your secure Calendar session has expired.');var body=await json(response);if(!body.csrfToken)throw new Error('A secure operation token could not be issued.');return body.csrfToken;}
async function create(path,payload){var token=await csrf();var response=await fetch(API+path,{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','Accept':'application/json','x-shiloh-csrf-token':token},body:JSON.stringify(payload)});token='';var body=await json(response);if(!response.ok){var error=new Error(body.error||'The canonical Calendar operation failed closed.');error.code=body.code;throw error;}return body;}
async function submitSelectedCreate(form){var kind=form.dataset.availabilityForm;var selected=Number(form.elements.practitionerStaffId&&form.elements.practitionerStaffId.value);if(!Number.isSafeInteger(selected)||selected<1)throw new Error('Choose a practitioner before saving.');if(kind==='block'){var startsAt=isoStart(form.elements.date.value,form.elements.starts.value);var endsAt=isoStart(form.elements.date.value,form.elements.ends.value);if(new Date(endsAt).getTime()<=new Date(startsAt).getTime())throw new Error('Block end time must be after the start time.');var title=String(form.elements.title.value||'').trim();if(!title)throw new Error('Add a short block label before saving.');return create('/blocks',{staffId:selected,locationId:null,startsAt:startsAt,endsAt:endsAt,blockType:'other',title:title,requestId:operationId()});}var reason=String(form.elements.reason.value||'').trim();if(!reason)throw new Error('Add a leave reason before saving.');return create('/leave',{staffId:selected,locationId:null,date:form.elements.date.value,reason:reason,requestId:operationId()});}
document.addEventListener('click',function(event){var button=event.target.closest&&event.target.closest('[data-calendar-operation]');if(!button)return;var action=button.dataset.calendarOperation;if(action==='add-block')decorateCreateForm('block',button);else if(action==='add-leave')decorateCreateForm('leave',button);else if(action==='manage-block'||action==='manage-leave')clearSelector();});
document.addEventListener('submit',function(event){var form=event.target;if(!form||form.dataset.availabilityPractitionerCreate!=='true'||!form.elements.practitionerStaffId)return;event.preventDefault();event.stopImmediatePropagation();status('Validating and saving against canonical Shiloh state…','working');submitSelectedCreate(form).then(function(){status(form.dataset.availabilityForm==='block'?'Block saved. Refreshing canonical Calendar…':'Leave saved. Refreshing canonical Calendar…','ready');window.location.reload();}).catch(function(error){status(error.message||'Nothing was changed. Reload Calendar and retry.','error');});},true);
})();`;
}

module.exports = { calendarAvailabilityPractitionerSelectClientScript };
