'use strict';

function bootstrapPage() {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Set up Shiloh</title><style>:root{color-scheme:light;--ink:#20322b;--muted:#6c7d75;--paper:#f7f5ef;--panel:#fffdf9;--line:#dfe5df;--leaf:#496b5a;--leaf-deep:#294c3c;--leaf-soft:#e7eee9;--error:#8a3f3f}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.shell{min-height:100vh;display:grid;place-items:center;padding:24px 16px}.card{width:min(520px,100%);background:var(--panel);border:1px solid var(--line);border-radius:20px;padding:24px;box-shadow:0 10px 34px rgba(32,50,43,.08)}.eyebrow{font-size:.72rem;text-transform:uppercase;letter-spacing:.12em;color:var(--muted);font-weight:800}h1{margin:7px 0 8px;font-size:1.65rem;line-height:1.12}p{margin:0;color:var(--muted);line-height:1.5}.status{margin-top:18px;min-height:3em;border-radius:13px;padding:13px;background:var(--leaf-soft);color:var(--leaf-deep);font-weight:700;line-height:1.4}.status.error{background:#f5ebe6;color:var(--error)}.privacy{margin-top:16px;font-size:.78rem}.action{display:none;width:100%;min-height:48px;margin-top:14px;border:1px solid var(--leaf-deep);border-radius:999px;padding:10px 16px;background:var(--leaf-deep);color:#fff;font:inherit;font-weight:800;cursor:pointer}.action.show{display:block}@media(max-width:560px){.shell{padding:14px 10px}.card{padding:20px 16px;border-radius:17px}}</style><script src="/calendar/staff-auth/passkeys/bootstrap.js" defer></script></head><body><main class="shell"><section class="card" data-shiloh-passkey-bootstrap><span class="eyebrow">Secure staff setup</span><h1>Set up Shiloh</h1><p>Shiloh will register a secure sign-in credential on this device. Your face, fingerprint or device PIN stays with the device.</p><div class="status" role="status" aria-live="polite" data-bootstrap-status>Preparing secure setup…</div><button class="action" type="button" data-bootstrap-retry>Try again</button><p class="privacy">This setup link works once. If it has expired or setup is interrupted, send “Hi” to Shiloh on WhatsApp again for a new link.</p></section></main></body></html>`;
}

function bootstrapScript() {
  return `(function(){'use strict';
var status=document.querySelector('[data-bootstrap-status]'),retry=document.querySelector('[data-bootstrap-retry]');var optionsCache=null;var running=false;
function msg(v,error){if(!status)return;status.textContent=v||'';status.classList.toggle('error',!!error);}function bytes(v){var s=String(v||'').replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';var raw=atob(s),a=new Uint8Array(raw.length);for(var i=0;i<raw.length;i++)a[i]=raw.charCodeAt(i);return a.buffer;}function enc(v){if(v==null)return null;var a=new Uint8Array(v),s='';for(var i=0;i<a.length;i++)s+=String.fromCharCode(a[i]);return btoa(s).replace(/\\+/g,'-').replace(/\\//g,'_').replace(/=+$/,'');}function safe(r){return r.json().catch(function(){return {};});}
function tokenFromHash(){var raw=String(location.hash||'').replace(/^#/,'');var p=new URLSearchParams(raw);var token=p.get('setup')||'';history.replaceState(null,'',location.pathname);return token;}
async function createCredential(){if(running||!optionsCache)return;running=true;retry&&retry.classList.remove('show');try{var o=JSON.parse(JSON.stringify(optionsCache));o.challenge=bytes(o.challenge);o.user.id=bytes(o.user.id);(o.excludeCredentials||[]).forEach(function(c){c.id=bytes(c.id);});msg('Approve secure Shiloh setup on this device…');var c=await navigator.credentials.create({publicKey:o});if(!c)throw new Error('cancelled');var transports=c.response.getTransports?c.response.getTransports():[];msg('Finishing secure setup…');var finish=await fetch('/calendar/staff-auth/passkeys/bootstrap/finish',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Accept':'application/json','Content-Type':'application/json'},body:JSON.stringify({response:{id:c.id,rawId:enc(c.rawId),type:c.type,response:{clientDataJSON:enc(c.response.clientDataJSON),attestationObject:enc(c.response.attestationObject),transports:transports}}})});var body=await safe(finish);if(!finish.ok||!body.authenticated)throw new Error('finish');msg('Shiloh is ready. Opening Workspace…');location.replace('/calendar/workspace');}catch(error){if(error&&error.name==='NotAllowedError')msg('Device verification was cancelled. Tap Try again, or send “Hi” to Shiloh for a new setup link if this page is no longer active.',true);else if(error&&error.name==='SecurityError')msg('This browser cannot create the Shiloh device credential on the current secure origin.',true);else msg('Secure setup could not be completed. Send “Hi” to Shiloh on WhatsApp for a fresh setup link.',true);retry&&retry.classList.add('show');}finally{running=false;}}
async function start(){if(!window.PublicKeyCredential||!navigator.credentials){msg('Secure device sign-in is not supported in this browser. Open the link on the phone or laptop you want to use for Shiloh.',true);return;}var token=tokenFromHash();if(!/^[A-Za-z0-9_-]{43}$/.test(token)){msg('This setup link is missing, expired or has already been used. Send “Hi” to Shiloh on WhatsApp for a fresh link.',true);return;}try{var r=await fetch('/calendar/staff-auth/passkeys/bootstrap/start',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Accept':'application/json','Content-Type':'application/json'},body:JSON.stringify({token:token})});var b=await safe(r);if(!r.ok||!b.options){msg('This setup link is expired, already used, or your Workspace access has changed. Send “Hi” to Shiloh for a fresh link.',true);return;}optionsCache=b.options;msg('Ready to secure '+String(b.displayName||'your Shiloh access')+'.');await createCredential();}catch(_){msg('Shiloh could not prepare secure setup. Try again when you are connected.',true);}}
if(retry)retry.addEventListener('click',createCredential);start();
})();`;
}

module.exports = { bootstrapPage, bootstrapScript };
