require("dotenv").config();
const express = require("express");
const { validateEnv } = require("./src/config/env");
const logger = require("./src/lib/logger");
const requestContext = require("./src/middleware/requestContext");
const startupTestRequest = require("./config/shiloh-test-request.json");
validateEnv();
const webhookRoutes=require("./src/routes/webhook"),adminRoutes=require("./src/routes/admin"),auditReadRoutes=require("./src/routes/auditRead"),calendarRoutes=require("./src/routes/calendar"),walkinRoutes=require("./src/routes/walkin");
const {checkDatabase}=require("./src/services/memory"),{applyPendingMigrations}=require("./src/services/migrations"),{repairJeanPierreIdentity}=require("./src/services/identityRepair"),{inspectCheniqueIdentity}=require("./src/services/cheniqueDiagnostic"),{startGoldieSyncScheduler}=require("./src/services/goldieSync"),{startGoogleBusinessProfileSyncScheduler}=require("./src/services/googleBusinessProfileSync"),{startAppointmentLifecycleScheduler}=require("./src/services/appointmentLifecycle"),{startCustomerCareScheduler}=require("./src/services/customerCare"),{runStartupTestCommand}=require("./src/services/startupTestCommand"),{runGoldieFutureImportFromEnv}=require("./src/services/goldieFutureImport"),{runFromEnv:runGoogleCalendarReconciliationFromEnv}=require("./src/services/googleCalendarReconciliation"),{runGoogleCalendarAccessSetupFromEnv}=require("./src/services/googleCalendarAccessSetup"),{repairNatashaStaffAssignment}=require("./src/services/natashaStaffRepair"),{runCrm6ProductionSmokeTest}=require("./src/services/crm6ProductionSmokeTest"),{runCalendarPresentationReconciliation}=require("./src/services/calendarPresentationReconciliation"),{runP2StaffRolloutSmokeTest}=require("./src/services/p2StaffRolloutSmokeTest"),{runMarietjieCalendarRolloutFromEnv}=require("./src/services/marietjieCalendarRollout"),{runAbigailCalendarRolloutFromEnv}=require("./src/services/abigailCalendarRollout"),{runCataloguePolishFromEnv}=require("./src/services/cataloguePolish");
const app=express();app.disable("x-powered-by");app.use(express.json({limit:"2mb"}));app.use(requestContext);app.get("/",(req,res)=>res.status(200).json({service:"shiloh-whatsapp-bot",status:"running"}));app.get("/health",async(req,res)=>{const ok=await checkDatabase();return res.status(ok?200:503).json({status:ok?"ok":"degraded",database:ok?"ok":"unavailable",timestamp:new Date().toISOString()});});app.use("/audit-read",auditReadRoutes);app.use("/admin",adminRoutes);app.use("/calendar",calendarRoutes);app.use("/",walkinRoutes);app.use("/",webhookRoutes);app.use((err,req,res,next)=>{const log=req.log||logger;log.error({err},"Unhandled Express error");if(res.headersSent)return next(err);return res.status(500).json({error:"Internal server error",requestId:req.id});});
const PORT=process.env.PORT||3000;let server;
async function start(){if(process.env.RUN_DB_MIGRATIONS_ON_STARTUP==="true"){const r=await applyPendingMigrations();logger.info({applied:r.applied},"Explicit startup database migrations applied");}if(process.env.RUN_JEAN_PIERRE_IDENTITY_REPAIR==="true")logger.info(await repairJeanPierreIdentity(),"Guarded Jean-Pierre identity repair completed");if(process.env.RUN_CHENIQUE_IDENTITY_DIAGNOSTIC==="true")logger.info(await inspectCheniqueIdentity(),"Read-only Chenique identity diagnostic completed");if(process.env.RUN_NATASHA_STAFF_REPAIR==="true")logger.info(await repairNatashaStaffAssignment(),"Guarded Natasha practitioner repair completed");if(process.env.RUN_CRM6_SMOKE_TEST==="true")await runCrm6ProductionSmokeTest();if(process.env.RUN_P2_STAFF_ROLLOUT_SMOKE_TEST==="true")await runP2StaffRolloutSmokeTest();if(process.env.RUN_MARIETJIE_CALENDAR_ROLLOUT==="true")await runMarietjieCalendarRolloutFromEnv();if(process.env.RUN_ABIGAIL_CALENDAR_ROLLOUT==="true")await runAbigailCalendarRolloutFromEnv();if(process.env.RUN_CATALOGUE_POLISH==="true")await runCataloguePolishFromEnv();server=app.listen(PORT,()=>{logger.info({port:PORT},"Shiloh started");startGoldieSyncScheduler();startGoogleBusinessProfileSyncScheduler();startAppointmentLifecycleScheduler();startCustomerCareScheduler();setImmediate(()=>{runStartupTestCommand(startupTestRequest).catch(e=>logger.error({err:e},"Deploy-triggered Shiloh test command did not complete"));runGoldieFutureImportFromEnv().catch(e=>logger.error({err:e},"Goldie future booking import did not complete"));runGoogleCalendarReconciliationFromEnv().catch(e=>logger.error({err:e},"Google Calendar future reconciliation did not complete"));runGoogleCalendarAccessSetupFromEnv().catch(e=>logger.error({err:e},"Google Calendar staff access setup did not complete"));runCalendarPresentationReconciliation().catch(e=>logger.error({err:e},"CRM-6 calendar presentation reconciliation did not complete"));});});}
start().catch(error=>{logger.fatal({err:error},"Shiloh failed during startup");process.exit(1);});function shutdown(signal){logger.info({signal},"Shutting down Shiloh");if(!server)return process.exit(0);server.close(()=>{logger.info("HTTP server closed");process.exit(0);});setTimeout(()=>{logger.error("Forced shutdown after timeout");process.exit(1);},10000).unref();}process.on("SIGTERM",()=>shutdown("SIGTERM"));process.on("SIGINT",()=>shutdown("SIGINT"));