const { pool } = require('../db/pool');
const { normalizePhone } = require('./clientIdentityOnboarding');
const { listAvailableSlots } = require('./availabilityService');
const { findClients } = require('./adminClientLookup');
const { prepareAdminBooking, confirmAdminBooking, cancelPendingBooking } = require('./adminBooking');

const sessions = new Map();
const PAGE_SIZE = 7;
function key(sender){return normalizePhone(sender);}
function clean(v=''){return String(v||'').trim().replace(/\s+/g,' ');}
function norm(v=''){return clean(v).toLowerCase();}
function has(admin,p){return admin?.permissions?.[p]===true;}
function short(v='',max=24){const s=clean(v);return s.length<=max?s:`${s.slice(0,Math.max(1,max-1)).trim()}…`;}
async function getAdmin(sender){const r=await pool.query(`SELECT id,staff_id,display_name,role,permissions FROM staff_admin_accounts WHERE normalized_whatsapp=$1 AND active=TRUE`,[key(sender)]);return r.rows[0]||null;}
async function audit(id,action,metadata={}){await pool.query(`INSERT INTO crm_audit_events (actor_admin_id,action,entity_type,entity_id,metadata) VALUES ($1,$2,'admin_mobile_booking',NULL,$3::jsonb)`,[id,action,JSON.stringify(metadata)]);}
function fmtDate(v){return new Intl.DateTimeFormat('en-ZA',{timeZone:'Africa/Johannesburg',weekday:'short',day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${v}T12:00:00+02:00`));}
function fmtTime(v){return new Intl.DateTimeFormat('en-ZA',{timeZone:'Africa/Johannesburg',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v));}
function parseDate(v){const s=clean(v);const m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);if(!m)return null;const d=Number(m[1]),mo=Number(m[2]),y=Number(m[3]);const p=new Date(Date.UTC(y,mo-1,d));if(p.getUTCFullYear()!==y||p.getUTCMonth()+1!==mo||p.getUTCDate()!==d)return null;return `${y}-${String(mo).padStart(2,'0')}-${String(d).padStart(2,'0')}`;}
function localDateTime(date,instant){return `${date.split('-').reverse().join('/')} ${fmtTime(instant)}`;}
function displayServiceName(name=''){return clean(name).replace(/^\d+\.\s*/,'').replace(/^[-–—]\s*/,'');}
function bookingScope(admin){const name=norm(admin?.display_name);if(name==='marietjie')return{key:'marietjie',staffNames:['marietjie'],label:'Marietjie services'};if(name==='christel'||name==='abigail')return{key:'christel_abigail',staffNames:['christel','abigail'],label:'Christel & Abigail services'};return{key:'business_admin',staffNames:null,label:'All client-bookable services'};}
async function scopedActiveServiceRows(admin){const scope=bookingScope(admin);if(!scope.staffNames){const r=await pool.query(`SELECT DISTINCT s.id,s.name,s.duration_minutes,s.processing_time_minutes,s.extra_time_minutes FROM services s JOIN staff_services ss ON ss.service_id=s.id JOIN staff st ON st.id=ss.staff_id WHERE s.status='active' AND st.status='active' AND st.client_bookable=TRUE ORDER BY s.name,s.id`);return r.rows;}const r=await pool.query(`SELECT DISTINCT s.id,s.name,s.duration_minutes,s.processing_time_minutes,s.extra_time_minutes FROM services s JOIN staff_services ss ON ss.service_id=s.id JOIN staff st ON st.id=ss.staff_id WHERE s.status='active' AND st.status='active' AND st.client_bookable=TRUE AND LOWER(st.display_name)=ANY($1::text[]) ORDER BY s.name,s.id`,[scope.staffNames]);return r.rows;}
async function staffRowsForService(serviceId,admin){const scope=bookingScope(admin);if(!scope.staffNames){const r=await pool.query(`SELECT st.id,st.display_name,st.scheduling_type FROM staff_services ss JOIN staff st ON st.id=ss.staff_id WHERE ss.service_id=$1 AND st.status='active' AND st.client_bookable=TRUE ORDER BY st.display_name,st.id`,[serviceId]);return r.rows;}const r=await pool.query(`SELECT st.id,st.display_name,st.scheduling_type FROM staff_services ss JOIN staff st ON st.id=ss.staff_id WHERE ss.service_id=$1 AND st.status='active' AND st.client_bookable=TRUE AND LOWER(st.display_name)=ANY($2::text[]) ORDER BY st.display_name,st.id`,[serviceId,scope.staffNames]);return r.rows;}
function clientLabel(c){const contact=(c.contacts||[]).find(x=>x.isPrimary)||(c.contacts||[])[0];const digits=normalizePhone(contact?.normalizedValue||contact?.value||'');return `${c.display_name||'Unnamed client'} — CRM #${c.id}${digits.length>=4?` · …${digits.slice(-4)}`:''}`;}
const CATEGORY_ORDER=['Massage & Body','Facials & Skin','Needling & Aesthetics','Permanent Makeup','Feet & Pedicure','Other'];
function categoryForService(name=''){const n=displayServiceName(name).toLowerCase();if(/massage|lymphatic|cupping|psoas|back & neck|back, neck|upper back|sports|pregnancy|pressotherapy|ozone|infrared|sculp|renew & revive|body/.test(n))return 'Massage & Body';if(/facial|peel|derma|brightening|hydrate|acne|pigmentation|clarity|glow|firm & lift|contour|hybrid|skin/.test(n))return 'Facials & Skin';if(/microneedl|needling|plasma|profosma|hifu|growth factor|lip plump|sqt|stretch mark|aesthetic/.test(n))return 'Needling & Aesthetics';if(/permanent makeup|permanant makeup|brows|eyeliner|areola/.test(n))return 'Permanent Makeup';if(/pedicure|heel|foot massage|feet|toe gel/.test(n))return 'Feet & Pedicure';return 'Other';}
function groupServices(services){const map=new Map(CATEGORY_ORDER.map(c=>[c,[]]));for(const service of services)map.get(categoryForService(service.name)).push(service);return CATEGORY_ORDER.filter(c=>map.get(c).length).map(name=>({name,services:map.get(name)}));}
function listInteractive(body,buttonText,rows,sectionTitle='Choose'){return{type:'list',body,buttonText,rows,sectionTitle};}
function buttonInteractive(body,buttons){return{type:'button',body,buttons};}
function cancelRow(){return{id:'admin_booking_cancel_flow',title:'Cancel booking',description:'Exit without creating anything'};}
function pageRows(items,page,rowFor){const start=page*PAGE_SIZE;const slice=items.slice(start,start+PAGE_SIZE);const rows=slice.map(rowFor);if(page>0)rows.push({id:`admin_booking_page:${page-1}`,title:'← Previous',description:'Show the previous choices'});if(start+PAGE_SIZE<items.length)rows.push({id:`admin_booking_page:${page+1}`,title:'Next →',description:'Show more choices'});rows.push(cancelRow());return rows;}
function categoryInteractive(scope,categories){return listInteractive(`*Find & book an appointment*\n\nAvailable catalogue: *${scope.label}*.\nChoose a service category.`, 'Choose category', [...categories.map((c,i)=>({id:`admin_booking_category:${i}`,title:short(c.name),description:`${c.services.length} service${c.services.length===1?'':'s'}`})),cancelRow()], 'Service category');}
function serviceInteractive(scope,category,page=0){return listInteractive(`*${scope.label} — ${category.name}*\n\nChoose the treatment.`, 'Choose service', pageRows(category.services,page,s=>({id:`admin_booking_service:${s.id}`,title:short(displayServiceName(s.name)),description:'Select this service'})), short(category.name));}
function staffInteractive(service,staff){return listInteractive(`*${displayServiceName(service.name)}*\n\nChoose the eligible practitioner.`, 'Practitioner', [...staff.slice(0,9).map(s=>({id:`admin_booking_staff:${s.id}`,title:short(s.display_name),description:'Eligible for this service'})),cancelRow()], 'Eligible practitioner');}
function slotsInteractive(session,page=0){return listInteractive(`*${fmtDate(session.date)} — Choose a time*\n\n${session.staff.display_name} · ${displayServiceName(session.service.name)}`, 'Choose time', pageRows(session.slots,page,(s,i)=>({id:`admin_booking_slot:${page*PAGE_SIZE+i}`,title:`${fmtTime(s.starts_at)}–${fmtTime(s.ends_at)}`,description:'Available slot'})), 'Available times');}
function clientsInteractive(clients){return listInteractive('*Choose client*\n\nSelect the matching CRM client.', 'Choose client', [...clients.slice(0,9).map(c=>({id:`admin_booking_client:${c.id}`,title:short(c.display_name||'Unnamed client'),description:short(clientLabel(c),72)})),cancelRow()], 'CRM clients');}
async function begin(sender,admin){const scope=bookingScope(admin);const services=await scopedActiveServiceRows(admin);if(!services.length)return{handled:true,admin,reply:`No active ${scope.label.toLowerCase()} are configured in CRM.`};const categories=groupServices(services);sessions.set(key(sender),{step:'category',categories,scopeKey:scope.key});await audit(admin.id,'mobile_booking.started',{activeServiceCount:services.length,selectionOrder:'service_first',bookingScope:scope.key,ux:'whatsapp_interactive_list'});return{handled:true,admin,interactive:categoryInteractive(scope,categories)};}
async function prepareCurrent(k,admin,current){const result=await prepareAdminBooking({adminId:admin.id,clientId:current.client.id,staffName:current.staff.display_name,serviceName:current.service.name,localDateTime:localDateTime(current.date,current.slot.starts_at)});await audit(admin.id,'mobile_booking.prepared',{status:result.status,clientId:current.client.id,staffId:current.staff.id,serviceId:current.service.id,startsAt:current.slot.starts_at,bookingScope:bookingScope(admin).key});if(result.status!=='pending_confirmation'){sessions.delete(k);return{handled:true,admin,reply:`That slot changed before the booking could be prepared. Nothing was written.\n\n${result.reply}`};}sessions.set(k,{step:'confirm'});return{handled:true,admin,interactive:buttonInteractive(`${result.reply}\n\n*Ready to finish*\nNothing is written until you confirm.`,[{id:'admin_booking_confirm',title:'Confirm booking'},{id:'admin_booking_cancel',title:'Cancel booking'}])};}
async function processAdminMobileBookingFlowMessage(sender,text){
 const raw=clean(text),v=raw.toLowerCase(),k=key(sender),session=sessions.get(k);const direct=/^(find an available time|find availability|make a booking|new booking|find & book|find and book)$/i.test(raw);if(!session&&!direct)return{handled:false};const admin=await getAdmin(sender);if(!admin)return{handled:false};if(!has(admin,'appointment:view')||!has(admin,'appointment:create'))return{handled:true,admin,reply:'Your admin account needs both appointment view and create permission for the guided booking flow.'};if(v==='menu'||v==='home'){if(session?.step==='confirm')await cancelPendingBooking(admin.id);sessions.delete(k);return{handled:false};}if(!session)return begin(sender,admin);
 if(v==='admin_booking_cancel_flow'){if(session?.step==='confirm')await cancelPendingBooking(admin.id);sessions.delete(k);await audit(admin.id,'mobile_booking.cancelled',{step:session.step,source:'interactive'});return{handled:true,admin,reply:'Booking flow cancelled. Nothing was written. Reply MENU to return to Shiloh Admin.'};}
 if(session.step==='confirm'){if(v==='1'||v==='confirm booking'){const result=await confirmAdminBooking(admin);sessions.delete(k);await audit(admin.id,'mobile_booking.confirmed',{status:result.status,appointmentId:result.appointmentId||null});return{handled:true,admin,reply:result.reply};}if(v==='2'||v==='0'||v==='cancel booking'){const cancelled=await cancelPendingBooking(admin.id);sessions.delete(k);await audit(admin.id,'mobile_booking.cancelled',{step:'confirm',hadPendingBooking:cancelled});return{handled:true,admin,reply:cancelled?'Booking cancelled. Nothing was written.':'There is no pending booking to cancel.'};}return{handled:true,admin,interactive:buttonInteractive('Choose whether to confirm or cancel this pending booking.',[{id:'admin_booking_confirm',title:'Confirm booking'},{id:'admin_booking_cancel',title:'Cancel booking'}])};}
 if(v==='0'){sessions.delete(k);await audit(admin.id,'mobile_booking.cancelled',{step:session.step});return{handled:true,admin,reply:'Booking flow cancelled. Nothing was written. Reply MENU to return to Shiloh Admin.'};}
 if(session.step==='category'){const m=v.match(/^admin_booking_category:(\d+)$/);const n=m?Number(m[1]):Number(v)-1;if(!Number.isInteger(n)||n<0||n>=session.categories.length)return{handled:true,admin,interactive:categoryInteractive(bookingScope(admin),session.categories)};const category=session.categories[n];sessions.set(k,{step:'service',category,serviceRows:category.services,categories:session.categories,scopeKey:session.scopeKey,page:0});return{handled:true,admin,interactive:serviceInteractive(bookingScope(admin),category,0)};}
 if(session.step==='service'){const pageMatch=v.match(/^admin_booking_page:(\d+)$/);if(pageMatch){const page=Number(pageMatch[1]);sessions.set(k,{...session,page});return{handled:true,admin,interactive:serviceInteractive(bookingScope(admin),session.category,page)};}const m=v.match(/^admin_booking_service:(\d+)$/);let service=m?session.serviceRows.find(s=>String(s.id)===m[1]):null;if(!service&&/^\d+$/.test(v))service=session.serviceRows[Number(v)-1];if(!service)return{handled:true,admin,interactive:serviceInteractive(bookingScope(admin),session.category,session.page||0)};const staff=await staffRowsForService(service.id,admin);if(!staff.length){return{handled:true,admin,reply:[`*${displayServiceName(service.name)}*`,'','This service is inside your booking catalogue, but no eligible practitioner in your booking scope is currently mapped to perform it.','Nothing has been booked. Start again from Make a booking or reply MENU.'].join('\n')};}sessions.set(k,{step:'staff',service,staffRows:staff});return{handled:true,admin,interactive:staffInteractive(service,staff)};}
 if(session.step==='staff'){const m=v.match(/^admin_booking_staff:(\d+)$/);let staff=m?session.staffRows.find(s=>String(s.id)===m[1]):null;if(!staff&&/^\d+$/.test(v))staff=session.staffRows[Number(v)-1];if(!staff)return{handled:true,admin,interactive:staffInteractive(session.service,session.staffRows)};sessions.set(k,{step:'date',staff,service:session.service});return{handled:true,admin,reply:[`*${displayServiceName(session.service.name)} — ${staff.display_name}*`,'','What date should I check?','Send DD/MM/YYYY, for example 18/08/2026.','','Type 0 to cancel.'].join('\n')};}
 if(session.step==='date'){const date=parseDate(raw);if(!date)return{handled:true,admin,reply:'Send a valid date as DD/MM/YYYY, for example 18/08/2026, or 0 to cancel.'};const result=await listAvailableSlots({staffId:session.staff.id,serviceId:session.service.id,date,intervalMinutes:15});if(!result.slots.length){sessions.set(k,{...session,date});return{handled:true,admin,reply:[`*No slots — ${fmtDate(date)}*`,'',`No authoritative bookable slots were found for ${session.staff.display_name} — ${displayServiceName(session.service.name)}.`,'','Send another date as DD/MM/YYYY, or 0 to cancel.'].join('\n')};}sessions.set(k,{step:'slot',staff:session.staff,service:session.service,date,slots:result.slots,page:0});return{handled:true,admin,interactive:slotsInteractive({staff:session.staff,service:session.service,date,slots:result.slots},0)};}
 if(session.step==='slot'){const pageMatch=v.match(/^admin_booking_page:(\d+)$/);if(pageMatch){const page=Number(pageMatch[1]);sessions.set(k,{...session,page});return{handled:true,admin,interactive:slotsInteractive(session,page)};}const m=v.match(/^admin_booking_slot:(\d+)$/);let slot=m?session.slots[Number(m[1])]:null;if(!slot&&/^\d+$/.test(v))slot=session.slots[Number(v)-1];if(!slot)return{handled:true,admin,interactive:slotsInteractive(session,session.page||0)};sessions.set(k,{step:'client-query',staff:session.staff,service:session.service,date:session.date,slot});return{handled:true,admin,reply:[`*Selected: ${fmtDate(session.date)} · ${fmtTime(slot.starts_at)}–${fmtTime(slot.ends_at)}*`,'',`Practitioner: ${session.staff.display_name}`,`Service: ${displayServiceName(session.service.name)}`,'','Who is the client?','Send a client name or mobile number.','','Type 0 to cancel.'].join('\n')};}
 if(session.step==='client-query'){const found=await findClients(raw,10);if(!found.clients.length)return{handled:true,admin,reply:`I couldn't find a canonical CRM client matching “${raw}”. Send another name/mobile number, or 0 to cancel.`};if(found.clients.length===1){const current={...session,client:found.clients[0]};sessions.set(k,{...current,step:'prepare'});return prepareCurrent(k,admin,current);}sessions.set(k,{step:'client-pick',...session,clientRows:found.clients});return{handled:true,admin,interactive:clientsInteractive(found.clients)};}
 if(session.step==='client-pick'){const m=v.match(/^admin_booking_client:(\d+)$/);let client=m?session.clientRows.find(c=>String(c.id)===m[1]):null;if(!client&&/^\d+$/.test(v))client=session.clientRows[Number(v)-1];if(!client)return{handled:true,admin,interactive:clientsInteractive(session.clientRows)};const current={...session,client};sessions.set(k,{...current,step:'prepare'});return prepareCurrent(k,admin,current);}
 return{handled:false};
}
module.exports={processAdminMobileBookingFlowMessage,bookingScope,scopedActiveServiceRows,staffRowsForService,groupServices,categoryInteractive,serviceInteractive,staffInteractive,slotsInteractive,clientsInteractive};
