const { pool } = require('../db/pool');
const { normalizePhone } = require('./clientIdentityOnboarding');
const { checkClinicHours } = require('./clinicHours');
const { checkAuthoritativeSchedule } = require('./adminAvailability');
const { checkCalendarAvailability, updateBookingEvent } = require('./googleBookingCalendar');

const sessions=new Map();
function key(sender){return normalizePhone(sender);}
function norm(v=''){return String(v||'').trim().toLowerCase().replace(/\s+/g,' ');}
function privileged(admin){return ['jean-pierre','christel'].includes(norm(admin.display_name))||norm(admin.role)==='owner'||norm(admin.role)==='admin';}
function formatDT(v){return new Intl.DateTimeFormat('en-ZA',{timeZone:'Africa/Johannesburg',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v));}
function parseLocal(v=''){const m=String(v).trim().match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})\s+(\d{1,2}):(\d{2})$/);if(!m)return null;const [,d,mo,y,h,mi]=m;const iso=`${y}-${String(mo).padStart(2,'0')}-${String(d).padStart(2,'0')}T${String(h).padStart(2,'0')}:${mi}:00+02:00`;const dt=new Date(iso);return Number.isNaN(dt.getTime())?null:dt;}
async function adminFor(sender){const r=await pool.query(`SELECT id,staff_id,display_name,role,permissions FROM staff_admin_accounts WHERE normalized_whatsapp=$1 AND active=TRUE`,[key(sender)]);return r.rows[0]||null;}
async function loadAppointment(admin,id){const r=await pool.query(`SELECT a.id,a.client_id,a.location_id,a.starts_at,a.ends_at,a.status,a.total_price,a.currency,COALESCE(c.display_name,a.source_client_name,'Client') client_name,l.name location_name,ace.event_id FROM appointments a LEFT JOIN clients c ON c.id=a.client_id LEFT JOIN locations l ON l.id=a.location_id LEFT JOIN appointment_calendar_events ace ON ace.appointment_id=a.id AND ace.provider='google_calendar' AND ace.sync_status='synced' WHERE a.id=$1 AND a.status<>'cancelled'`,[id]);if(!r.rowCount)return null;const a=r.rows[0];const staff=(await pool.query(`SELECT ast.staff_id,ast.staff_name_snapshot,s.display_name FROM appointment_staff ast LEFT JOIN staff s ON s.id=ast.staff_id WHERE ast.appointment_id=$1 ORDER BY ast.position`,[id])).rows;const services=(await pool.query(`SELECT aps.id,aps.service_id,aps.service_name_snapshot,aps.price_snapshot,aps.duration_minutes_snapshot,s.name,s.duration_minutes,s.processing_time_minutes,s.extra_time_minutes FROM appointment_services aps LEFT JOIN services s ON s.id=aps.service_id WHERE aps.appointment_id=$1 ORDER BY aps.position`,[id])).rows;if(!privileged(admin)){if(!admin.staff_id||!staff.some(x=>Number(x.staff_id)===Number(admin.staff_id)))return {forbidden:true};}return {...a,staff,services};}
async function syncCalendar(a){if(!a.event_id)return;const staffName=a.staff.map(x=>x.display_name||x.staff_name_snapshot).join(' + ');const serviceName=a.services.map(x=>x.name||x.service_name_snapshot).join(' + ');await updateBookingEvent({eventId:a.event_id,appointmentId:a.id,startsAt:a.starts_at,endsAt:a.ends_at,clientName:a.client_name,serviceName,staffName,locationName:a.location_name});}
async function audit(admin,appointmentId,action,metadata){await pool.query(`INSERT INTO crm_audit_events(actor_admin_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'appointment',$3,$4::jsonb)`,[admin.id,action,String(appointmentId),JSON.stringify(metadata)]);}
async function transaction(work){const db=await pool.connect();try{await db.query('BEGIN');const result=await work(db);await db.query('COMMIT');return result;}catch(error){await db.query('ROLLBACK');throw error;}finally{db.release();}}
function menu(a){const service=a.services.map(x=>x.name||x.service_name_snapshot).join(' + ');const staff=a.staff.map(x=>x.display_name||x.staff_name_snapshot).join(' + ');return [`*Manage booking #${a.id}*`,`👤 ${a.client_name}`,`✨ ${service}`,`💆 ${staff}`,`🕘 ${formatDT(a.starts_at)}–${new Intl.DateTimeFormat('en-ZA',{timeZone:'Africa/Johannesburg',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(a.ends_at))}`,`💰 ${a.total_price==null?'Not set':`R${Number(a.total_price).toFixed(2)}`}`,'','1️⃣ Change service','2️⃣ Change practitioner','3️⃣ Change date / time','4️⃣ Change booked price','0️⃣ Back','','No customer message is sent until Shiloh customer-change notifications are enabled.'].join('\n');}
async function validateWindow(a,staffId,staffName,startsAt,endsAt){const clinic=await checkClinicHours({locationId:a.location_id,startsAt,endsAt});if(!clinic.covered)return 'That time falls outside clinic hours.';const schedule=await checkAuthoritativeSchedule({staffId,locationId:a.location_id,startsAt,endsAt});if(schedule.partialUnavailable||(schedule.allDayUnavailable&&!schedule.insideAvailableException)||!schedule.covered)return 'That time falls outside the practitioner’s allowed schedule.';const c=await pool.query(`SELECT a.id FROM appointments a JOIN appointment_staff ast ON ast.appointment_id=a.id WHERE ast.staff_id=$1 AND a.id<>$2 AND a.status<>'cancelled' AND a.starts_at<$4 AND a.ends_at>$3 LIMIT 1`,[staffId,a.id,startsAt,endsAt]);if(c.rowCount)return 'That practitioner already has another CRM appointment at that time.';const external=await checkCalendarAvailability({startsAt,endsAt,staffName,ignoreEventId:a.event_id||null});if(external.enabled&&!external.available)return 'The shared Shiloh calendar has another conflicting event at that time.';return null;}
async function processAdminBookingUpdateMessage(sender,text){const admin=await adminFor(sender);if(!admin)return{handled:false};const raw=String(text||'').trim(),n=norm(raw),k=key(sender);let s=sessions.get(k);
 if(['menu','admin menu','home','admin'].includes(n)||/^(hi|hello|hey|howzit|hiya|good morning|good afternoon|good evening)[!. ]*$/i.test(raw)){sessions.delete(k);return{handled:false};}
 if(['manage booking','update booking','edit booking'].includes(n)){sessions.set(k,{step:'id'});return{handled:true,admin,reply:['*Manage booking*','','Send the Shiloh appointment number.','Example: *369*','','0️⃣ Back'].join('\n')};}
 if(!s)return{handled:false};if(n==='0'||n==='back'||n==='cancel'){sessions.delete(k);return{handled:true,admin,reply:'Booking update closed. Send *Menu* to return to Admin.'};}
 if(s.step==='id'){if(!/^\d+$/.test(raw))return{handled:true,admin,reply:'Please send the numeric Shiloh appointment number.'};const a=await loadAppointment(admin,Number(raw));if(!a)return{handled:true,admin,reply:'I could not find an active booking with that appointment number.'};if(a.forbidden){sessions.delete(k);return{handled:true,admin,reply:"You don't have permission to manage that booking."};}sessions.set(k,{step:'menu',appointmentId:a.id});return{handled:true,admin,reply:menu(a)};}
 const a=await loadAppointment(admin,s.appointmentId);if(!a||a.forbidden){sessions.delete(k);return{handled:true,admin,reply:'That booking is no longer available to manage.'};}
 if(s.step==='menu'){if(n==='1'||n==='change service'){if(a.services.length!==1)return{handled:true,admin,reply:'This is a multi-service booking. For safety, service replacement is currently limited to single-service bookings. You can still change practitioner, time, or booked price.'};sessions.set(k,{step:'service',appointmentId:a.id});return{handled:true,admin,reply:'Send the exact new service name.'};}if(n==='2'||n==='change practitioner'){sessions.set(k,{step:'staff',appointmentId:a.id});return{handled:true,admin,reply:'Send the exact practitioner name.'};}if(n==='3'||n==='change date / time'||n==='change date/time'){sessions.set(k,{step:'time',appointmentId:a.id});return{handled:true,admin,reply:'Send the new date and time as *DD/MM/YYYY HH:MM*.'};}if(n==='4'||n==='change booked price'||n==='change price'){sessions.set(k,{step:'price',appointmentId:a.id});return{handled:true,admin,reply:'Send the new booked price, for example *650* or *R650*.'};}return{handled:true,admin,reply:'Choose 1, 2, 3, 4, or 0.'};}
 if(s.step==='service'){const r=await pool.query(`SELECT id,name,duration_minutes,processing_time_minutes,extra_time_minutes,price FROM services WHERE status='active' AND LOWER(name)=LOWER($1)`,[raw]);if(r.rowCount!==1)return{handled:true,admin,reply:'Send the exact name of one active canonical service.'};const service=r.rows[0];for(const st of a.staff){const ok=await pool.query(`SELECT 1 FROM staff_services WHERE staff_id=$1 AND service_id=$2`,[st.staff_id,service.id]);if(!ok.rowCount)return{handled:true,admin,reply:`${st.display_name||st.staff_name_snapshot} is not authorized for ${service.name}. Choose another service or change practitioner first.`};}const minutes=Number(service.duration_minutes||0)+Number(service.processing_time_minutes||0)+Number(service.extra_time_minutes||0);const starts=new Date(a.starts_at),ends=new Date(starts.getTime()+minutes*60000);if(a.staff.length===1){const problem=await validateWindow(a,a.staff[0].staff_id,a.staff[0].display_name||a.staff[0].staff_name_snapshot,starts,ends);if(problem)return{handled:true,admin,reply:problem};}await transaction(async db=>{await db.query(`UPDATE appointment_services SET service_id=$1,service_name_snapshot=$2,duration_minutes_snapshot=$3,price_snapshot=$4 WHERE id=$5`,[service.id,service.name,service.duration_minutes,service.price,a.services[0].id]);await db.query(`UPDATE appointments SET ends_at=$1,title=$2,updated_at=NOW() WHERE id=$3`,[ends,service.name,a.id]);});const after=await loadAppointment(admin,a.id);await syncCalendar(after);await audit(admin,a.id,'appointment.service_updated',{from:a.services[0].name||a.services[0].service_name_snapshot,to:service.name});sessions.set(k,{step:'menu',appointmentId:a.id});return{handled:true,admin,reply:`✅ Service changed to *${service.name}* and the Google Calendar event was updated.\n\n${menu(after)}`};}
 if(s.step==='staff'){const r=await pool.query(`SELECT id,display_name FROM staff WHERE status='active' AND resource_type='practitioner' AND LOWER(display_name)=LOWER($1)`,[raw]);if(r.rowCount!==1)return{handled:true,admin,reply:'Send the exact name of one active practitioner.'};const st=r.rows[0];if(!privileged(admin)&&Number(admin.staff_id)!==Number(st.id))return{handled:true,admin,reply:"You can only manage bookings inside your own practitioner scope."};for(const svc of a.services){const ok=await pool.query(`SELECT 1 FROM staff_services WHERE staff_id=$1 AND service_id=$2`,[st.id,svc.service_id]);if(!ok.rowCount)return{handled:true,admin,reply:`${st.display_name} is not authorized for ${svc.name||svc.service_name_snapshot}.`};}const problem=await validateWindow(a,st.id,st.display_name,a.starts_at,a.ends_at);if(problem)return{handled:true,admin,reply:problem};await transaction(async db=>{await db.query(`DELETE FROM appointment_staff WHERE appointment_id=$1`,[a.id]);await db.query(`INSERT INTO appointment_staff(appointment_id,staff_id,position,staff_name_snapshot) VALUES($1,$2,1,$3)`,[a.id,st.id,st.display_name]);});const after=await loadAppointment(admin,a.id);await syncCalendar(after);await audit(admin,a.id,'appointment.staff_updated',{from:a.staff.map(x=>x.display_name||x.staff_name_snapshot),to:st.display_name});sessions.set(k,{step:'menu',appointmentId:a.id});return{handled:true,admin,reply:`✅ Practitioner changed to *${st.display_name}* and the Google Calendar event was updated.\n\n${menu(after)}`};}
 if(s.step==='time'){const starts=parseLocal(raw);if(!starts)return{handled:true,admin,reply:'Use *DD/MM/YYYY HH:MM*, for example 15/08/2026 09:00.'};if(starts.getTime()<=Date.now())return{handled:true,admin,reply:'Choose a future date and time.'};const duration=new Date(a.ends_at)-new Date(a.starts_at),ends=new Date(starts.getTime()+duration);if(a.staff.length!==1)return{handled:true,admin,reply:'Multi-practitioner time changes are not supported in this guarded flow yet.'};const st=a.staff[0];const problem=await validateWindow(a,st.staff_id,st.display_name||st.staff_name_snapshot,starts,ends);if(problem)return{handled:true,admin,reply:problem};await pool.query(`UPDATE appointments SET starts_at=$1,ends_at=$2,updated_at=NOW() WHERE id=$3`,[starts,ends,a.id]);const after=await loadAppointment(admin,a.id);await syncCalendar(after);await audit(admin,a.id,'appointment.time_updated',{fromStart:a.starts_at,fromEnd:a.ends_at,toStart:starts,toEnd:ends});sessions.set(k,{step:'menu',appointmentId:a.id});return{handled:true,admin,reply:`✅ Date/time updated and Google Calendar synchronized.\n\n${menu(after)}`};}
 if(s.step==='price'){const m=n.match(/^r?\s*(\d+(?:\.\d{1,2})?)$/);if(!m)return{handled:true,admin,reply:'Send a valid booked price, for example *650* or *R650*.'};const price=Number(m[1]);if(price<0||price>100000)return{handled:true,admin,reply:'That price is outside the allowed range.'};await transaction(async db=>{await db.query(`UPDATE appointments SET total_price=$1,updated_at=NOW() WHERE id=$2`,[price,a.id]);if(a.services.length===1)await db.query(`UPDATE appointment_services SET price_snapshot=$1 WHERE id=$2`,[price,a.services[0].id]);});await audit(admin,a.id,'appointment.price_updated',{from:a.total_price==null?null:Number(a.total_price),to:price});const after=await loadAppointment(admin,a.id);sessions.set(k,{step:'menu',appointmentId:a.id});return{handled:true,admin,reply:`✅ Booked price updated to *R${price.toFixed(2)}*. The calendar title remains price-free.\n\n${menu(after)}`};}
 return{handled:false};}
module.exports={processAdminBookingUpdateMessage};