const { pool } = require('../db/pool');
const { normalizePhone } = require('./clientIdentityOnboarding');
const { DAYS, getWorkingHours, replaceWorkingHoursDay, clearWorkingHoursDayOverride, addScheduleException, removeScheduleException, formatWorkingHours } = require('./staffScheduleService');

const sessions = new Map();
const MONTHS={jan:1,feb:2,mar:3,apr:4,may:5,jun:6,jul:7,aug:8,sep:9,oct:10,nov:11,dec:12};
function key(sender){return normalizePhone(sender);}
function clean(v=''){return String(v||'').trim().replace(/\s+/g,' ');}
function has(admin,p){return admin?.permissions?.[p]===true;}
async function getAdmin(sender){const r=await pool.query(`SELECT id,display_name,permissions FROM staff_admin_accounts WHERE normalized_whatsapp=$1 AND active=TRUE`,[key(sender)]);return r.rows[0]||null;}
async function audit(id,action,metadata={}){await pool.query(`INSERT INTO crm_audit_events(actor_admin_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'admin_schedule_mobile',NULL,$3::jsonb)`,[id,action,JSON.stringify(metadata)]);}
async function regularStaff(){const r=await pool.query(`SELECT id,display_name,scheduling_type FROM staff WHERE status='active' AND scheduling_type='regular' ORDER BY display_name,id`);return r.rows;}
function fmtDate(v){return new Intl.DateTimeFormat('en-ZA',{timeZone:'Africa/Johannesburg',weekday:'short',day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${v}T12:00:00+02:00`));}
function parseDate(v){const s=clean(v);let m=s.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(m)return valid(Number(m[1]),Number(m[2]),Number(m[3]));m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);if(m)return valid(Number(m[3]),Number(m[2]),Number(m[1]));m=s.match(/^(\d{1,2})\s+([A-Za-z]{3,9})(?:\s+(\d{4}))?$/);if(!m)return null;const mon=MONTHS[m[2].slice(0,3).toLowerCase()];if(!mon)return null;const now=new Date(new Date().toLocaleString('en-US',{timeZone:'Africa/Johannesburg'}));let y=m[3]?Number(m[3]):now.getFullYear();let d=valid(y,mon,Number(m[1]));if(!d)return null;const today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;if(!m[3]&&d<today)d=valid(y+1,mon,Number(m[1]));return d;}
function valid(y,m,d){const dt=new Date(Date.UTC(y,m-1,d));if(dt.getUTCFullYear()!==y||dt.getUTCMonth()+1!==m||dt.getUTCDate()!==d)return null;return `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;}
function parseHours(v){const m=clean(v).match(/^([0-2]\d:[0-5]\d)\s*-\s*([0-2]\d:[0-5]\d)$/);if(!m||m[2]<=m[1])return null;return {start:m[1],end:m[2]};}
function pickStaffReply(rows,title){return [`*${title}*`,'','Choose a practitioner:','',...rows.map((r,i)=>`${i+1}️⃣ ${r.display_name}`),'','0️⃣ Back'].join('\n');}
function staffHoursMenu(staff){return [`*${staff.display_name} — Staff hours*`,'','1️⃣ View current hours','2️⃣ Change a day','','0️⃣ Back'].join('\n');}
function dayMenu(staff){return [`*${staff.display_name} — Change a day*`,'',...DAYS.map((d,i)=>`${i+1}️⃣ ${d}`),'','0️⃣ Back'].join('\n');}
function dayAction(staff,day){return [`*${staff.display_name} — ${DAYS[day]}*`,'','1️⃣ Use clinic hours (inherit)','2️⃣ Closed','3️⃣ Custom hours','','0️⃣ Back'].join('\n');}
function exceptionMenu(staff){return [`*${staff.display_name} — Leave / special availability*`,'','1️⃣ Add full-day leave','2️⃣ Add unavailable hours','3️⃣ Add special available hours','4️⃣ View upcoming exceptions','5️⃣ Remove an exception','','0️⃣ Back'].join('\n');}
function listExceptions(staff,data,title='Upcoming exceptions'){const rows=data.exceptions||[];const lines=[`*${staff.display_name} — ${title}*`,''];if(!rows.length)lines.push('No upcoming exceptions are configured.');else rows.slice(0,10).forEach((x,i)=>lines.push(`${i+1}️⃣ #${x.id} · ${fmtDate(String(x.exception_date).slice(0,10))} · ${x.exception_type} · ${x.starts_local?`${x.starts_local.slice(0,5)}–${x.ends_local.slice(0,5)}`:'all day'}${x.reason?` · ${x.reason}`:''}`));lines.push('','0️⃣ Back');return lines.join('\n');}
async function beginHours(sender,admin){const rows=await regularStaff();sessions.set(key(sender),{step:'hours-staff',rows});return {handled:true,admin,reply:pickStaffReply(rows,'Staff hours')};}
async function beginExceptions(sender,admin){const rows=await regularStaff();sessions.set(key(sender),{step:'exceptions-staff',rows});return {handled:true,admin,reply:pickStaffReply(rows,'Leave / special availability')};}
async function processAdminStaffScheduleFlowMessage(sender,text){
 const raw=clean(text),v=raw.toLowerCase(),k=key(sender),session=sessions.get(k);const directHours=/^(staff hours|regular staff hours)$/i.test(raw);const directExceptions=/^(leave|leave and special availability|leave \/ special availability|special availability)$/i.test(raw);if(!session&&!directHours&&!directExceptions)return {handled:false};const admin=await getAdmin(sender);if(!admin)return {handled:false};if(!has(admin,'schedule:manage'))return {handled:true,admin,reply:"You don't have permission to manage staff schedules."};if(v==='menu'||v==='home'){sessions.delete(k);return {handled:false};}if(!session)return directHours?beginHours(sender,admin):beginExceptions(sender,admin);if(v==='0'&&['hours-staff','exceptions-staff'].includes(session.step)){sessions.delete(k);return {handled:true,admin,reply:'Reply *More* to return to schedule management.'};}
 if(session.step==='hours-staff'){const n=Number(v);if(!Number.isInteger(n)||n<1||n>session.rows.length)return {handled:true,admin,reply:'Choose the practitioner number shown, or 0 to go back.'};const staff=session.rows[n-1];sessions.set(k,{step:'hours-menu',staff});return {handled:true,admin,reply:staffHoursMenu(staff)};}
 if(session.step==='hours-menu'){if(v==='0')return beginHours(sender,admin);if(v==='1'){const data=await getWorkingHours(session.staff.id);return {handled:true,admin,reply:`${formatWorkingHours(data)}\n\n0️⃣ Back`};}if(v==='2'){sessions.set(k,{step:'hours-day',staff:session.staff});return {handled:true,admin,reply:dayMenu(session.staff)};}return {handled:true,admin,reply:'Choose 1, 2, or 0.'};}
 if(session.step==='hours-day'){if(v==='0'){sessions.set(k,{step:'hours-menu',staff:session.staff});return {handled:true,admin,reply:staffHoursMenu(session.staff)};}const n=Number(v);if(!Number.isInteger(n)||n<1||n>7)return {handled:true,admin,reply:'Choose the day number shown, or 0 to go back.'};const day=n-1;sessions.set(k,{step:'hours-day-action',staff:session.staff,day});return {handled:true,admin,reply:dayAction(session.staff,day)};}
 if(session.step==='hours-day-action'){if(v==='0'){sessions.set(k,{step:'hours-day',staff:session.staff});return {handled:true,admin,reply:dayMenu(session.staff)};}if(v==='1'){const r=await clearWorkingHoursDayOverride({staffId:session.staff.id,dayOfWeek:session.day,actorAdminId:admin.id});sessions.set(k,{step:'hours-menu',staff:session.staff});return {handled:true,admin,reply:r.status==='updated'?`✅ ${session.staff.display_name} — ${DAYS[session.day]} now uses clinic hours (inherited).\n\n${staffHoursMenu(session.staff)}`:(r.reply||'Schedule update rejected.')};}if(v==='2'){const r=await replaceWorkingHoursDay({staffId:session.staff.id,dayOfWeek:session.day,windows:[],actorAdminId:admin.id});sessions.set(k,{step:'hours-menu',staff:session.staff});return {handled:true,admin,reply:r.status==='updated'?`✅ ${session.staff.display_name} — ${DAYS[session.day]} is closed by staff override.\n\n${staffHoursMenu(session.staff)}`:(r.reply||'Schedule update rejected.')};}if(v==='3'){sessions.set(k,{step:'hours-custom',staff:session.staff,day:session.day});return {handled:true,admin,reply:[`*${session.staff.display_name} — ${DAYS[session.day]}*`,'','Send custom hours, for example 09:00-17:00.','','0️⃣ Back'].join('\n')};}return {handled:true,admin,reply:'Choose 1, 2, 3, or 0.'};}
 if(session.step==='hours-custom'){if(v==='0'){sessions.set(k,{step:'hours-day-action',staff:session.staff,day:session.day});return {handled:true,admin,reply:dayAction(session.staff,session.day)};}const h=parseHours(raw);if(!h)return {handled:true,admin,reply:'Send hours as HH:MM-HH:MM, for example 09:00-17:00.'};const r=await replaceWorkingHoursDay({staffId:session.staff.id,dayOfWeek:session.day,windows:[{startsLocal:h.start,endsLocal:h.end}],actorAdminId:admin.id});sessions.set(k,{step:'hours-menu',staff:session.staff});return {handled:true,admin,reply:r.status==='updated'?`✅ ${session.staff.display_name} — ${DAYS[session.day]} set to ${h.start}–${h.end}.\n\n${staffHoursMenu(session.staff)}`:(r.reply||'Schedule update rejected.')};}
 if(session.step==='exceptions-staff'){const n=Number(v);if(!Number.isInteger(n)||n<1||n>session.rows.length)return {handled:true,admin,reply:'Choose the practitioner number shown, or 0 to go back.'};const staff=session.rows[n-1];sessions.set(k,{step:'exceptions-menu',staff});return {handled:true,admin,reply:exceptionMenu(staff)};}
 if(session.step==='exceptions-menu'){if(v==='0')return beginExceptions(sender,admin);if(v==='4'){const data=await getWorkingHours(session.staff.id);return {handled:true,admin,reply:listExceptions(session.staff,data)};}if(v==='5'){const data=await getWorkingHours(session.staff.id);if(!data.exceptions.length)return {handled:true,admin,reply:listExceptions(session.staff,data)};sessions.set(k,{step:'exception-remove-pick',staff:session.staff,rows:data.exceptions.slice(0,10)});return {handled:true,admin,reply:listExceptions(session.staff,data,'Choose exception to remove')};}if(['1','2','3'].includes(v)){const mode=v==='1'?'leave':v==='2'?'unavailable':'available';sessions.set(k,{step:'exception-date',staff:session.staff,mode});return {handled:true,admin,reply:[`*${session.staff.display_name} — ${mode==='leave'?'Full-day leave':mode==='unavailable'?'Unavailable hours':'Special available hours'}*`,'','What date?','Example: 18 Aug or 18/08/2026','','0️⃣ Back'].join('\n')};}return {handled:true,admin,reply:'Choose 1, 2, 3, 4, 5, or 0.'};}
 if(session.step==='exception-date'){if(v==='0'){sessions.set(k,{step:'exceptions-menu',staff:session.staff});return {handled:true,admin,reply:exceptionMenu(session.staff)};}const date=parseDate(raw);if(!date)return {handled:true,admin,reply:'Send a valid date, for example 18 Aug or 18/08/2026.'};if(session.mode==='leave'){sessions.set(k,{step:'exception-reason',staff:session.staff,mode:session.mode,date,hours:null});return {handled:true,admin,reply:[`*${session.staff.display_name} — ${fmtDate(date)}*`,'','Optional reason? Send a short reason, or reply SKIP.','','0️⃣ Back'].join('\n')};}sessions.set(k,{step:'exception-hours',staff:session.staff,mode:session.mode,date});return {handled:true,admin,reply:[`*${session.staff.display_name} — ${fmtDate(date)}*`,'',session.mode==='unavailable'?'What hours are unavailable?':'What hours are specially available?','Example: 10:00-14:00','','0️⃣ Back'].join('\n')};}
 if(session.step==='exception-hours'){if(v==='0'){sessions.set(k,{step:'exceptions-menu',staff:session.staff});return {handled:true,admin,reply:exceptionMenu(session.staff)};}const h=parseHours(raw);if(!h)return {handled:true,admin,reply:'Send hours as HH:MM-HH:MM.'};sessions.set(k,{step:'exception-reason',staff:session.staff,mode:session.mode,date:session.date,hours:h});return {handled:true,admin,reply:'Optional reason? Send a short reason, or reply SKIP.\n\n0️⃣ Back'};}
 if(session.step==='exception-reason'){if(v==='0'){sessions.set(k,{step:'exceptions-menu',staff:session.staff});return {handled:true,admin,reply:exceptionMenu(session.staff)};}const reason=v==='skip'?null:raw;const type=session.mode==='available'?'available':'unavailable';const r=await addScheduleException({staffId:session.staff.id,date:session.date,type,startsLocal:session.hours?.start||null,endsLocal:session.hours?.end||null,reason,actorAdminId:admin.id});sessions.set(k,{step:'exceptions-menu',staff:session.staff});if(r.status!=='created')return {handled:true,admin,reply:r.reply||'Schedule exception rejected.'};const range=session.hours?`${session.hours.start}–${session.hours.end}`:'all day';return {handled:true,admin,reply:`✅ ${session.staff.display_name} — ${fmtDate(session.date)} · ${type} · ${range}${reason?` · ${reason}`:''}.\n\n${exceptionMenu(session.staff)}`};}
 if(session.step==='exception-remove-pick'){if(v==='0'){sessions.set(k,{step:'exceptions-menu',staff:session.staff});return {handled:true,admin,reply:exceptionMenu(session.staff)};}const n=Number(v);if(!Number.isInteger(n)||n<1||n>session.rows.length)return {handled:true,admin,reply:'Choose the exception number shown, or 0 to go back.'};const row=session.rows[n-1];sessions.set(k,{step:'exception-remove-confirm',staff:session.staff,row});return {handled:true,admin,reply:[`*Remove exception #${row.id}?*`,'',`${fmtDate(String(row.exception_date).slice(0,10))} · ${row.exception_type} · ${row.starts_local?`${row.starts_local.slice(0,5)}–${row.ends_local.slice(0,5)}`:'all day'}`,'','1️⃣ Confirm remove','0️⃣ Cancel'].join('\n')};}
 if(session.step==='exception-remove-confirm'){if(v==='0'){sessions.set(k,{step:'exceptions-menu',staff:session.staff});return {handled:true,admin,reply:exceptionMenu(session.staff)};}if(v!=='1')return {handled:true,admin,reply:'Choose 1 to confirm removal, or 0 to cancel.'};const r=await removeScheduleException({staffId:session.staff.id,exceptionId:session.row.id,actorAdminId:admin.id});sessions.set(k,{step:'exceptions-menu',staff:session.staff});return {handled:true,admin,reply:r.status==='removed'?`✅ Exception #${session.row.id} removed.\n\n${exceptionMenu(session.staff)}`:'That exception was not found.'};}
 return {handled:false};
}
module.exports={processAdminStaffScheduleFlowMessage};
