const { pool } = require('../db/pool');
const { normalizePhone } = require('./clientIdentityOnboarding');

const sessions=new Map();
function key(sender){return normalizePhone(sender);}
function norm(v=''){return String(v||'').trim().toLowerCase().replace(/\s+/g,' ');}
function businessWide(admin){return ['owner','business_admin'].includes(admin?.business_role)||admin?.service_scope==='all_services';}
function canManagePricing(admin){return admin?.permissions?.['service:pricing']===true;}
async function adminFor(sender){const r=await pool.query(`SELECT id,staff_id,display_name,role,permissions,service_scope,business_role,calendar_scope FROM staff_admin_accounts WHERE normalized_whatsapp=$1 AND active=TRUE`,[key(sender)]);return r.rows[0]||null;}
async function allowedServices(admin,q=''){const args=[];let where=`s.status='active'`;if(q){args.push(`%${q}%`);where+=` AND s.name ILIKE $${args.length}`;}if(!businessWide(admin)){if(!admin.staff_id)return [];args.push(admin.staff_id);where+=` AND EXISTS(SELECT 1 FROM staff_services ss WHERE ss.service_id=s.id AND ss.staff_id=$${args.length})`;}
 const r=await pool.query(`SELECT s.id,s.name,s.price,s.variable_price,sc.name category FROM services s LEFT JOIN service_categories sc ON sc.id=s.category_id WHERE ${where} ORDER BY s.name LIMIT 12`,args);return r.rows;}
async function processAdminServicePricingMessage(sender,text){const admin=await adminFor(sender);if(!admin)return{handled:false};const v=String(text||'').trim();const n=norm(v);const k=key(sender);let s=sessions.get(k);
 if(['manage services & pricing','service pricing','manage pricing','pricing','my services & pricing'].includes(n)){if(!canManagePricing(admin))return{handled:true,admin,reply:'Your Shiloh role does not include permission to change service pricing.'};sessions.set(k,{step:'service'});return{handled:true,admin,reply:[businessWide(admin)?'*Services & pricing*':'*My services & pricing*','',businessWide(admin)?'Send the service name you want to update.':'Send one of your assigned service names to update its price.','Example: Full Body Swedish','','0️⃣ Back'].join('\n')};}
 if(!s)return{handled:false};if(!canManagePricing(admin)){sessions.delete(k);return{handled:true,admin,reply:'Your Shiloh role does not include permission to change service pricing.'};}if(n==='0'||n==='back'||n==='cancel'){sessions.delete(k);return{handled:true,admin,reply:'Pricing update cancelled. Send *Menu* to return to Admin.'};}
 if(s.step==='service'){const rows=await allowedServices(admin,v);if(!rows.length)return{handled:true,admin,reply:"I couldn't find an active service in your allowed catalogue. Try the exact service name."};if(rows.length>1&&!rows.some(r=>norm(r.name)===n)){return{handled:true,admin,reply:['I found several matches:','',...rows.map(r=>`• ${r.name}`),'','Send the exact service name.'].join('\n')};}const service=rows.find(r=>norm(r.name)===n)||rows[0];sessions.set(k,{step:'price',service});const current=service.price==null?'Not set':service.variable_price?`From R${Number(service.price).toFixed(2)} (variable)`:`R${Number(service.price).toFixed(2)}`;return{handled:true,admin,reply:[`*${service.name}*`,`Current price: ${current}`,'','Send the new amount, for example *650* or *R650*.','Send *variable 650* for “from R650”.','Send *unset* to remove the price.'].join('\n')};}
 if(s.step==='price'){let price=null,variable=false;if(n==='unset'){price=null;}else{const m=n.match(/^(variable\s+)?r?\s*(\d+(?:\.\d{1,2})?)$/i);if(!m)return{handled:true,admin,reply:'Please send a valid amount, e.g. *650*, *R650*, *variable 650*, or *unset*.'};variable=!!m[1];price=Number(m[2]);if(price<0||price>100000)return{handled:true,admin,reply:'That price is outside the allowed range.'};}
 const before=s.service.price==null?null:Number(s.service.price);await pool.query(`UPDATE services SET price=$1,variable_price=$2,updated_at=NOW() WHERE id=$3`,[price,variable,s.service.id]);await pool.query(`INSERT INTO crm_audit_events(actor_admin_id,action,entity_type,entity_id,metadata) VALUES($1,'service.price_updated','service',$2,$3::jsonb)`,[admin.id,String(s.service.id),JSON.stringify({service:s.service.name,businessRole:admin.business_role,beforePrice:before,beforeVariable:!!s.service.variable_price,afterPrice:price,afterVariable:variable})]);sessions.delete(k);const display=price==null?'not set':variable?`from R${price.toFixed(2)}`:`R${price.toFixed(2)}`;return{handled:true,admin,reply:`✅ ${s.service.name} pricing updated to *${display}*. Existing confirmed bookings keep their booked price.`};}
 return{handled:false};}
module.exports={processAdminServicePricingMessage};