const { pool } = require("../db/pool");
const { normalizePhone } = require("./clientIdentityOnboarding");
const { menu } = require('./adminMobileMenu');
function normalizeHelpText(text=""){return String(text).trim().toLowerCase().replace(/\s+/g," ");}
function isHelpRequest(text=""){const value=normalizeHelpText(text);return ["help","admin help","what can i do","what can you do","what can i do as admin","show admin commands","show commands"].includes(value)||/^help\s+/.test(value);}
function hasPermission(admin,p){return admin?.permissions?.[p]===true;}
function walkinHelp(admin){if(!hasPermission(admin,"walkin:create"))return "You don't have permission to add walk-ins.";return ["*Add a walk-in*","","Send: Add walk-in","","Shiloh will guide you through the client details and show a summary before creation."].join("\n");}
function clientHelp(admin){if(!hasPermission(admin,"client:lookup"))return "You don't have permission to find clients.";return ["*Find a client*","","Send: Find client NAME OR NUMBER","","Example: Find client Chenique"].join("\n");}
function scheduleHelp(admin){if(!hasPermission(admin,"schedule:manage"))return "You don't have permission to manage staff schedules.";return ["*Schedule*","","Recurring hours, leave, special availability, freelancer availability and holiday hours are managed in Shiloh Calendar.","","Send *Open Calendar* for a secure one-time handoff. WhatsApp will not change diary authority."].join("\n");}
function appointmentsHelp(admin){if(!hasPermission(admin,"appointment:view"))return "You don't have permission to view appointments.";return ["*Appointments*","","• Today — quick operational view","• Tomorrow — quick operational view","• Open Calendar — create, reschedule, reassign, cancel or block time","","WhatsApp does not perform those diary mutations. Reply *Menu* for the retained staff options."].join("\n");}
function getAdminHelpReply(admin,text){if(!isHelpRequest(text))return null;const value=normalizeHelpText(text);if(/^help\s+walk[- ]?in$/.test(value)||value==="help walkin")return walkinHelp(admin);if(value==="help client"||value==="help clients")return clientHelp(admin);if(value==="help schedule"||value==="help scheduling"||value==="help working hours")return scheduleHelp(admin);if(value==="help appointment"||value==="help appointments")return appointmentsHelp(admin);return menu(admin);}
async function processAdminHelpMessage(sender,text){if(!isHelpRequest(text))return {handled:false};const result=await pool.query(`SELECT id, staff_id, display_name, role, permissions FROM staff_admin_accounts WHERE normalized_whatsapp = $1 AND active = TRUE`,[normalizePhone(sender)]);const admin=result.rows[0]||null;if(!admin)return {handled:false};return {handled:true,admin,reply:getAdminHelpReply(admin,text)};}
module.exports={processAdminHelpMessage,getAdminHelpReply,isHelpRequest};
