const { processAdminMobileMenuMessage } = require('./adminMobileMenu');
const { processAdminAppointmentFinalizationMessage } = require('./adminAppointmentFinalization');
const { processAdminAppointmentsByDateMessage } = require('./adminAppointmentsByDate');
const { processAdminHelpMessage } = require('./adminHelp');
const { processJeanPierreControlPlaneMessage } = require('./jeanPierreAdminControlPlane');
const { processAdminMarietjieEarningsMessage } = require('./adminMarietjieEarnings');
const { processAdminTestClientResetMessage } = require('./adminTestClientReset');
const { processAdminPendingBookingApprovalsMessage } = require('./adminPendingBookingApprovals');
const { abigailEarningsButtons, christelEarningsButtons, marietjieEarningsButtons } = require('./adminEarningsButtons');
const SECTION_ORDER=['Appointments','Reports','Clients','Services','Schedule','More'];
const APPOINTMENT_PRIORITY=['finalize','booking','manage_booking','today','tomorrow'];
const ACTIONS=[
{key:'today',labels:["Today's clients",'My clients today'],command:'today',description:'View today’s appointments'},
{key:'tomorrow',labels:["Tomorrow's clients",'My clients tomorrow'],command:'tomorrow',description:'View tomorrow’s appointments'},
{key:'availability',labels:['Find an available time'],command:'Find an available time',description:'Check the authoritative diary'},
{key:'demo_client',labels:['🧪 Demo Client','Demo Client'],command:'Demo Client',description:'Controlled regression harness'},
{key:'today_report',labels:["Today's report",'My report today'],command:"Today's report",description:'View today’s scoped business report'},
{key:'christel_earnings',labels:['💰 Christel earnings','Christel earnings'],command:'Christel earnings',description:'Completed-only earnings report'},
{key:'abigail_earnings',labels:['💰 Abigail earnings','Abigail earnings'],command:'Abigail earnings',description:'Completed-only earnings report'},
{key:'marietjie_earnings',labels:['💰 Marietjie earnings','Marietjie earnings'],command:'Marietjie earnings',description:'Completed-only earnings report'},
{key:'booking',labels:['Make a booking'],command:'Make a booking',description:'Book using authoritative availability'},
{key:'manage_booking',labels:['Manage a booking'],command:'Manage a booking',description:'Reschedule or cancel an existing appointment'},
{key:'finalize',labels:['Finalize past visits'],command:'Finalize past appointments',description:'Completed, No-show, Reschedule or leave unresolved'},
{key:'client',labels:['Find a client','Find my client','Client details','My client details'],command:'Find a client',description:'View full authorized CRM client details'},
{key:'reset_juvan',labels:['Reset Juvan profile'],command:'Reset test client Juvan',description:'Reset dedicated booking-test client'},
{key:'walkin',labels:['Add a walk-in'],command:'Add a walk-in',description:'Register a walk-in client'},
{key:'staff_services',labels:['Staff services','My services'],command:'Staff services',description:'View authorized service mappings'},
{key:'pricing',labels:['Services & pricing','My services & pricing'],command:'Services & pricing',description:'View or manage service pricing'},
{key:'schedule',labels:['Schedule management','My schedule'],command:'Schedule',description:'Manage authorized diary settings'},
{key:'calendar_integrity',labels:['🛡️ Calendar integrity','Calendar integrity'],command:'Calendar integrity scan',description:'Check booking/calendar integrity'},
{key:'help',labels:['Help'],command:'Help',description:'Show admin help'}];
function normalizeLabel(v=''){return String(v).replace(/[🧪💰🛡️]/gu,'').trim().toLowerCase().replace(/\s+/g,' ')}
function actionForLabel(label){const n=normalizeLabel(label);return ACTIONS.find(a=>a.labels.some(c=>normalizeLabel(c)===n))||null}
function actionForId(id){const m=String(id||'').trim().match(/^admin_action_([a-z0-9_]+)$/);return m?ACTIONS.find(a=>a.key===m[1])||null:null}
function parseVisibleMenu(body=''){const sections=new Map();let current=null;for(const line of String(body).split('\n')){const s=line.trim().match(/^\*(Appointments|Reports|Clients|Services|Schedule|More)\*$/);if(s){current=s[1];if(!sections.has(current))sections.set(current,[]);continue}const o=line.trim().match(/^\d+️⃣\s+(.+)$/u);if(!o||!current)continue;const action=actionForLabel(o[1]);if(action)sections.get(current).push({action,title:o[1].trim()})}return sections}
function isActionVisibleInMenu(action,body=''){if(!action?.key)return false;for(const e of parseVisibleMenu(body).values())if(e.some(x=>x.action.key===action.key))return true;return false}
function compactMenuBody(body=''){const c=[];let p=false;for(const line of String(body).split('\n')){const t=line.trim();if(/^\*(Appointments|Reports|Clients|Services|Schedule|More)\*$/.test(t)||/^\d+️⃣\s+/u.test(t))continue;if(/^Use the real \*/.test(t)){if(!p)c.push('Choose a section below.');p=true;continue}c.push(line)}while(c.length&&!c[c.length-1].trim())c.pop();return c.join('\n').replace(/\n{3,}/g,'\n\n')}
function visibleEntriesBySection(body=''){const parsed=parseVisibleMenu(body);const sections=new Map(parsed);const clients=(sections.get('Clients')||[]).filter(({action})=>action.key!=='walkin'&&action.key!=='client');const more=(sections.get('More')||[]).filter(({action})=>action.key!=='calendar_integrity'&&action.key!=='help');const client=(parsed.get('Clients')||[]).find(({action})=>action.key==='client');if(client&&!more.some(({action})=>action.key==='client'))more.unshift({...client,title:'Client details'});sections.set('Clients',clients);sections.set('More',more);return sections}
function topLevelInteractive(body){const s=visibleEntriesBySection(body);return{type:'list',body:compactMenuBody(body),buttonText:'Admin menu',rows:SECTION_ORDER.filter(x=>(s.get(x)||[]).length>0).map(x=>({id:`admin_section_${x.toLowerCase()}`,title:x,description:`Open ${x.toLowerCase()} admin actions`})),sectionTitle:'Shiloh Admin'}}
function sectionInteractive(section,body){let entries=visibleEntriesBySection(body).get(section)||[];if(!entries.length)return null;if(section==='Appointments')entries=entries.filter(({action})=>action.key!=='availability'&&action.key!=='demo_client').sort((a,b)=>APPOINTMENT_PRIORITY.indexOf(a.action.key)-APPOINTMENT_PRIORITY.indexOf(b.action.key));if(!entries.length)return null;const rows=entries.map(({action,title})=>({id:`admin_action_${action.key}`,title:title.length<=24?title:title.slice(0,24),description:action.description}));rows.push({id:'menu',title:'← Back to Admin',description:'Return to the main admin menu'});return{type:'list',body:`*${section}*\nChoose what you want to do.`,buttonText:section.length<=20?section:'Open options',rows,sectionTitle:section}}
function normalizedAdminName(a){return String(a?.display_name||'').trim().toLowerCase()}
function isJeanPierreBusinessAdmin(a){return normalizedAdminName(a)==='jean-pierre'&&a?.business_role==='business_admin'&&a?.calendar_scope==='all_business'&&a?.service_scope==='all_services'}
function isChristelOwnerAdmin(a){return normalizedAdminName(a)==='christel'&&['owner','business_admin'].includes(a?.business_role)&&a?.calendar_scope==='all_business'}
function isMarietjieAdmin(a){return normalizedAdminName(a)==='marietjie'&&Boolean(a?.staff_id)}
function enrichPrivilegedReportsMenu(result){if(!result?.handled||!result?.interactive?.body)return result;const jp=isJeanPierreBusinessAdmin(result.admin),ch=isChristelOwnerAdmin(result.admin),ma=isMarietjieAdmin(result.admin);let body=String(result.interactive.body);if(result.admin?.permissions?.['booking:update']===true&&result.admin?.permissions?.['appointment:view']===true&&!/Finalize past visits/i.test(body))body+='\n\n*Appointments*\n93️⃣ Finalize past visits';if(!jp&&!ch&&!ma)return{...result,interactive:{...result.interactive,body}};if(jp&&!/Christel earnings/i.test(body))body+='\n\n*Reports*\n98️⃣ 💰 Christel earnings';if(!/Marietjie earnings/i.test(body))body+='\n\n*Reports*\n99️⃣ 💰 Marietjie earnings';if((jp||ch)&&!/Reset Juvan profile/i.test(body))body+='\n\n*Clients*\n95️⃣ Reset Juvan profile';return{...result,interactive:{...result.interactive,body}}}
function enrichJeanPierreMenu(r){return enrichPrivilegedReportsMenu(r)}
async function getRoleScopedMenu(sender){const r=await processAdminMobileMenuMessage(sender,'Menu');if(!r?.handled||!r?.interactive?.body)return r;return enrichPrivilegedReportsMenu(r)}
async function dispatchStableAction(sender,action){if(action.key==='today'||action.key==='tomorrow')return processAdminAppointmentsByDateMessage(sender,action.command);if(action.key==='help')return processAdminHelpMessage(sender,action.command);if(action.key==='finalize')return processAdminAppointmentFinalizationMessage(sender,action.command);if(action.key==='abigail_earnings')return{handled:true,interactive:abigailEarningsButtons()};if(action.key==='christel_earnings')return{handled:true,interactive:christelEarningsButtons()};if(action.key==='marietjie_earnings')return{handled:true,interactive:marietjieEarningsButtons()};if(action.key==='reset_juvan')return processAdminTestClientResetMessage(sender,action.command);const p=await processJeanPierreControlPlaneMessage(sender,action.command);if(p.handled)return p;return processAdminMobileMenuMessage(sender,action.command)}
async function processAdminInteractiveMenuMessage(sender,text){const pa=await processAdminPendingBookingApprovalsMessage(sender,text);if(pa.handled)return pa;const f=await processAdminAppointmentFinalizationMessage(sender,text);if(f.handled)return f;const tr=await processAdminTestClientResetMessage(sender,text);if(tr.handled)return tr;const me=await processAdminMarietjieEarningsMessage(sender,text);if(me.handled)return me;const jp=await processJeanPierreControlPlaneMessage(sender,text);if(jp.handled)return jp;const raw=String(text||'').trim();const sm=raw.match(/^admin_section_(appointments|reports|clients|services|schedule|more)$/i);if(sm){const m=await getRoleScopedMenu(sender);if(!m?.handled||!m?.interactive?.body)return{handled:true,admin:m?.admin,reply:'Admin menu could not be refreshed safely. Send *Menu* to restart Admin.'};const section=SECTION_ORDER.find(v=>v.toLowerCase()===sm[1].toLowerCase());const interactive=sectionInteractive(section,m.interactive.body);if(!interactive)return{handled:true,admin:m.admin,reply:'That admin section is not available for your account. Send *Menu* to refresh your options.'};return{handled:true,admin:m.admin,interactive}}const action=actionForId(raw);if(action){if(action.key==='walkin')return{handled:true,reply:'That admin action is no longer available. Send *Menu* to refresh your options.'};const m=await getRoleScopedMenu(sender);if(!m?.handled||!m?.interactive?.body)return{handled:true,admin:m?.admin,reply:'Admin menu could not be refreshed safely. Send *Menu* to restart Admin.'};if(!isActionVisibleInMenu(action,m.interactive.body))return{handled:true,admin:m.admin,reply:'That admin action is not available for your account. Send *Menu* to refresh your options.'};return dispatchStableAction(sender,action)}if(/^admin_action_/i.test(raw))return{handled:true,reply:'That admin action is no longer available. Send *Menu* to refresh your options.'};const r=enrichPrivilegedReportsMenu(await processAdminMobileMenuMessage(sender,text));if(r?.handled&&r?.interactive?.type==='button'&&/^\*Shiloh Admin 🌿\*/.test(r.interactive.body||''))return{...r,interactive:topLevelInteractive(r.interactive.body)};return r}
module.exports={ACTIONS,actionForId,actionForLabel,compactMenuBody,dispatchStableAction,enrichJeanPierreMenu,enrichPrivilegedReportsMenu,isActionVisibleInMenu,parseVisibleMenu,processAdminInteractiveMenuMessage,sectionInteractive,topLevelInteractive};
