const { pool } = require('../db/pool');
const { parseGoldieDateTime } = require('./appointmentReconciliationPlan');

const EXEC_CONFIRMATION = 'EXECUTE_SAFE_GOLDIE_CALENDAR_BLOCKS';
function norm(v){return String(v||'').normalize('NFKC').trim().toLowerCase().replace(/\s+/g,' ');}
function splitList(v){return String(v||'').split(',').map(x=>x.trim()).filter(Boolean);}
function blockType(v){const t=norm(v);if(['time off','timeoff','unavailable','blocked'].includes(t))return 'time_off';if(['personal','personal event'].includes(t))return 'personal_event';return 'other';}

async function buildCalendarBlockPlan({appointmentBatchId='2'}={}){
  const [rows,staff]=await Promise.all([
    pool.query(`SELECT id,external_id,source_payload FROM external_records WHERE import_batch_id=$1 AND source='goldie' AND entity_type='appointment' AND reconciliation_status='unmatched' ORDER BY id`,[appointmentBatchId]),
    pool.query(`SELECT id,display_name,source_name FROM staff`),
  ]);
  const sm=new Map();for(const r of staff.rows){sm.set(norm(r.display_name),String(r.id));if(r.source_name)sm.set(norm(r.source_name),String(r.id));}
  const typeCounts=new Map(), blockers=new Map(), eligible=[];
  for(const rec of rows.rows){const p=rec.source_payload||{};if(norm(p.Type)==='appointment')continue;const type=p.Type||'';typeCounts.set(type,(typeCounts.get(type)||0)+1);const reasons=[];const start=parseGoldieDateTime(p.Date,p['Start Time']),end=parseGoldieDateTime(p.Date,p['End Time']);if(!(start&&end&&end>start))reasons.push('invalid_time_range');const names=splitList(p.Staff);let staffId=null;if(names.length!==1)reasons.push(names.length?'multiple_staff':'staff_blank');else{staffId=sm.get(norm(names[0]))||sm.get(norm(names[0].replace(/\s+\.$/,'')))||null;if(!staffId)reasons.push('staff_unresolved');}if(reasons.length){for(const r of reasons)blockers.set(r,(blockers.get(r)||0)+1);}else eligible.push({externalRecordId:String(rec.id),externalId:rec.external_id,type,blockType:blockType(type),staffId,staffName:names[0],startsAt:start.toISOString(),endsAt:end.toISOString(),title:p.Title||null,notes:p.Notes||null,recurrence:p.Recurrence||null});}
  return {mode:'dry_run',writesPerformed:false,summary:{nonAppointmentRows:[...typeCounts.values()].reduce((a,b)=>a+b,0),eligible:eligible.length,blocked:[...blockers.values()].reduce((a,b)=>a+b,0)},typeCounts:[...typeCounts.entries()].map(([type,count])=>({type,count})).sort((a,b)=>b.count-a.count),blockerCounts:[...blockers.entries()].map(([reason,count])=>({reason,count})).sort((a,b)=>b.count-a.count),eligibleSample:eligible.slice(0,20),policy:{requiresNonAppointmentType:true,requiresValidTimeRange:true,requiresExactlyOneResolvedStaff:true,typeMapping:{personal:'personal_event','personal event':'personal_event','time off':'time_off',timeoff:'time_off',unavailable:'time_off',blocked:'time_off',fallback:'other'},writesEnabled:false}};
}

async function executeCalendarBlockPromotion({appointmentBatchId='2',confirmation}={}){
 if(confirmation!==EXEC_CONFIRMATION){const e=new Error(`Execution requires confirmation value: ${EXEC_CONFIRMATION}`);e.code='CONFIRMATION_REQUIRED';throw e;}
 const plan=await buildCalendarBlockPlan({appointmentBatchId});if(!plan.summary.eligible)return {mode:'execute',writesPerformed:false,created:0,skipped:plan.summary.blocked};
 const db=await pool.connect();try{await db.query('BEGIN');let created=0;for(const i of plan.eligibleSample.length===plan.summary.eligible?plan.eligibleSample:[]){/* never execute partial sample */}const [rows,staff]=await Promise.all([db.query(`SELECT id,external_id,source_payload FROM external_records WHERE import_batch_id=$1 AND source='goldie' AND entity_type='appointment' AND reconciliation_status='unmatched' ORDER BY id FOR UPDATE`,[appointmentBatchId]),db.query(`SELECT id,display_name,source_name FROM staff`)]);const sm=new Map();for(const r of staff.rows){sm.set(norm(r.display_name),String(r.id));if(r.source_name)sm.set(norm(r.source_name),String(r.id));}let skipped=0;for(const rec of rows.rows){const p=rec.source_payload||{};if(norm(p.Type)==='appointment')continue;const start=parseGoldieDateTime(p.Date,p['Start Time']),end=parseGoldieDateTime(p.Date,p['End Time']);const names=splitList(p.Staff);const staffId=names.length===1?(sm.get(norm(names[0]))||sm.get(norm(names[0].replace(/\s+\.$/,'')))||null):null;if(!(start&&end&&end>start&&staffId)){skipped++;continue;}const ins=await db.query(`INSERT INTO calendar_blocks (staff_id,block_type,starts_at,ends_at,title,notes,recurrence_text,source,external_id,external_key,source_staff_name) VALUES ($1,$2,$3,$4,$5,$6,$7,'goldie',$8,$8,$9) ON CONFLICT (source,external_id) DO NOTHING RETURNING id`,[staffId,blockType(p.Type),start.toISOString(),end.toISOString(),p.Title||p.Type||null,p.Notes||null,p.Recurrence||null,rec.external_id,p.Staff||null]);let id=ins.rows[0]?.id;if(!id){const ex=await db.query(`SELECT id FROM calendar_blocks WHERE source='goldie' AND external_id=$1`,[rec.external_id]);id=ex.rows[0]?.id;}if(!id)throw new Error(`Could not resolve calendar block ${rec.external_id}`);if(ins.rowCount)created++;await db.query(`UPDATE external_records SET shiloh_entity_type='calendar_block',shiloh_entity_id=$2,reconciliation_status='matched',match_method='safe_goldie_calendar_block_promotion',match_confidence=1.0,reconciled_at=NOW(),updated_at=NOW() WHERE id=$1`,[rec.id,id]);}await db.query('COMMIT');return {mode:'execute',writesPerformed:true,created,skipped};}catch(e){try{await db.query('ROLLBACK')}catch(_){}throw e;}finally{db.release();}
}
async function runConfiguredCalendarBlockPromotion(logger=console){const confirmation=process.env.GOLDIE_CALENDAR_BLOCK_PROMOTION_CONFIRMATION;if(!confirmation)return {skipped:true,reason:'confirmation_not_configured'};const r=await executeCalendarBlockPromotion({confirmation});logger.info({goldieCalendarBlockPromotion:r},'Goldie calendar block promotion completed');return r;}
module.exports={buildCalendarBlockPlan,executeCalendarBlockPromotion,runConfiguredCalendarBlockPromotion,EXEC_CONFIRMATION};
