const crypto = require("crypto");
const { prepareCalendarWrite } = require('./clientBookingCalendarRecovery');

const TOKEN_URL = "https://oauth2.googleapis.com/token";
const CALENDAR_API = "https://www.googleapis.com/calendar/v3";
const SCOPE = "https://www.googleapis.com/auth/calendar";
const DEFAULT_TIMEZONE = "Africa/Johannesburg";
const STAFF_CALENDAR_ENV = Object.freeze({
  christel: "GOOGLE_CHRISTEL_CALENDAR_ID",
  abigail: "GOOGLE_ABIGAIL_CALENDAR_ID",
  marietjie: "GOOGLE_MARIETJIE_CALENDAR_ID",
});
let cachedToken=null,cachedTokenExpiresAt=0;
function calendarEnabled(){return String(process.env.GOOGLE_CALENDAR_ENABLED||"").toLowerCase()==="true";}
function authMode(){return String(process.env.GOOGLE_CALENDAR_AUTH_MODE||"service_account").trim().toLowerCase();}
function requireCalendarConfig(){const calendarId=String(process.env.GOOGLE_BOOKING_CALENDAR_ID||"").trim();if(!calendarId)throw new Error("Google Calendar is enabled but GOOGLE_BOOKING_CALENDAR_ID is missing.");return{calendarId};}
function requireServiceAccountConfig(){const clientEmail=String(process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL||"").trim(),privateKey=String(process.env.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY||"").replace(/\\n/g,"\n");if(!clientEmail||!privateKey)throw new Error("GOOGLE_CALENDAR_AUTH_MODE=service_account requires GOOGLE_SERVICE_ACCOUNT_EMAIL and GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY.");return{clientEmail,privateKey};}
function cleanOAuthEnv(v){return String(v||"").trim();} function requireOAuthConfig(){const clientId=cleanOAuthEnv(process.env.GOOGLE_OAUTH_CLIENT_ID),clientSecret=cleanOAuthEnv(process.env.GOOGLE_OAUTH_CLIENT_SECRET),refreshToken=cleanOAuthEnv(process.env.GOOGLE_OAUTH_REFRESH_TOKEN);if(!clientId||!clientSecret||!refreshToken)throw new Error("GOOGLE_CALENDAR_AUTH_MODE=oauth_refresh_token requires GOOGLE_OAUTH_CLIENT_ID, GOOGLE_OAUTH_CLIENT_SECRET, and GOOGLE_OAUTH_REFRESH_TOKEN.");return{clientId,clientSecret,refreshToken};}
function base64url(input){return Buffer.from(input).toString("base64url");} function normalizeName(v=""){return String(v).trim().toLowerCase().replace(/\s+/g," ");}
function practitionerCalendarIdForStaff(staffName=""){const envName=STAFF_CALENDAR_ENV[normalizeName(staffName)];return envName?String(process.env[envName]||"").trim()||null:null;}
async function getServiceAccountAccessToken(){const{clientEmail,privateKey}=requireServiceAccountConfig(),now=Math.floor(Date.now()/1000),header=base64url(JSON.stringify({alg:"RS256",typ:"JWT"})),payload=base64url(JSON.stringify({iss:clientEmail,scope:SCOPE,aud:TOKEN_URL,iat:now,exp:now+3600})),unsigned=`${header}.${payload}`,signature=crypto.sign("RSA-SHA256",Buffer.from(unsigned),privateKey).toString("base64url"),response=await fetch(TOKEN_URL,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion:`${unsigned}.${signature}`})});if(!response.ok)throw new Error(`Google service-account token request failed (${response.status}): ${(await response.text()).slice(0,500)}`);return response.json();}
async function getOAuthRefreshAccessToken(){const{clientId,clientSecret,refreshToken}=requireOAuthConfig(),response=await fetch(TOKEN_URL,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:clientId,client_secret:clientSecret,refresh_token:refreshToken,grant_type:"refresh_token"})});if(!response.ok)throw new Error(`Google OAuth refresh-token request failed (${response.status}): ${(await response.text()).slice(0,500)}`);return response.json();}
async function getAccessToken(){if(cachedToken&&Date.now()<cachedTokenExpiresAt-60000)return cachedToken;const token=authMode()==="oauth_refresh_token"?await getOAuthRefreshAccessToken():await getServiceAccountAccessToken();cachedToken=token.access_token;cachedTokenExpiresAt=Date.now()+Number(token.expires_in||3600)*1000;return cachedToken;}
async function googleRequest(path,options={}){requireCalendarConfig();const token=await getAccessToken(),response=await fetch(`${CALENDAR_API}${path}`,{...options,headers:{authorization:`Bearer ${token}`,"content-type":"application/json",...(options.headers||{})}});if(response.status===204)return null;const text=await response.text();let body;try{body=text?JSON.parse(text):null;}catch(_){body=text;}if(!response.ok){const e=new Error(`Google Calendar API request failed (${response.status})`);e.status=response.status;e.body=body;throw e;}return body;}
function deterministicEventId(k){return crypto.createHash("sha256").update(String(k)).digest("hex").slice(0,40);} function eventIdForAppointment(appointmentId){if(!appointmentId)throw new Error("appointmentId is required for Google Calendar synchronization.");return deterministicEventId(`shiloh-appointment:${appointmentId}`);} function eventAppliesToStaff(event,staffName){if(!staffName)return true;const requested=normalizeName(staffName),tagged=normalizeName(event.extendedProperties?.private?.shilohStaffName||"");if(tagged)return tagged===requested;const searchable=normalizeName(`${event.summary||""} ${event.description||""}`);if(searchable.includes(requested))return true;return !/\bstaff\s*:/i.test(String(event.description||""));}
function serviceIcon(n=""){n=normalizeName(n);if(/massage|lymphatic|swedish|hot stone|pregnancy/.test(n))return"💆";if(/pedicure|foot|heel|toe/.test(n))return"🦶";if(/facial|hifu|plasma|microneed|needling|ozone|pelvic|vaginal|brow|permanent makeup/.test(n))return"✨";return"🌿";} function bookingSummary({clientName,serviceName,staffName}){return`${serviceIcon(serviceName)} ${serviceName||"Booking"} — ${clientName||"Client"}${staffName?` — ${staffName}`:""}`;} function bookingDescription({appointmentId,clientName,serviceName,staffName,locationName,source}){return[`Shiloh CRM appointment #${appointmentId}`,clientName?`Client: ${clientName}`:null,serviceName?`Service: ${serviceName}`:null,staffName?`Practitioner: ${staffName}`:null,locationName?`Location: ${locationName}`:null,source?`Source: ${source}`:null].filter(Boolean).join("\n");}
async function checkCalendarAvailability({startsAt,endsAt,staffName=null,ignoreEventId=null}){if(!calendarEnabled())return{enabled:false,available:true,conflicts:[]};const sharedCalendarId=requireCalendarConfig().calendarId;const shared=await checkCalendarAvailabilityOnCalendar(sharedCalendarId,{startsAt,endsAt,staffName,ignoreEventId});const practitionerCalendarId=practitionerCalendarIdForStaff(staffName);if(!practitionerCalendarId||practitionerCalendarId===sharedCalendarId)return shared;const practitioner=await checkCalendarAvailabilityOnCalendar(practitionerCalendarId,{startsAt,endsAt,staffName:null,ignoreEventId});return{enabled:true,available:shared.available&&practitioner.available,conflicts:[...shared.conflicts,...practitioner.conflicts],sharedConflicts:shared.conflicts,practitionerConflicts:practitioner.conflicts,practitionerCalendarId};}
async function checkCalendarAvailabilityOnCalendar(calendarId,{startsAt,endsAt,staffName=null,ignoreEventId=null}){const q=new URLSearchParams({timeMin:new Date(startsAt).toISOString(),timeMax:new Date(endsAt).toISOString(),singleEvents:"true",orderBy:"startTime",showDeleted:"false",maxResults:"50"}),r=await googleRequest(`/calendars/${encodeURIComponent(calendarId)}/events?${q}`),conflicts=(r.items||[]).filter(e=>{if(ignoreEventId&&e.id===ignoreEventId)return false;if(e.status==="cancelled"||e.transparency==="transparent")return false;if(!eventAppliesToStaff(e,staffName))return false;const s=e.start?.dateTime||e.start?.date,en=e.end?.dateTime||e.end?.date;return s&&en&&new Date(s)<new Date(endsAt)&&new Date(en)>new Date(startsAt);});return{enabled:true,available:!conflicts.length,conflicts};}
async function createBookingEvent(data){if(!calendarEnabled())return{enabled:false,event:null};const calendarId=requireCalendarConfig().calendarId,eventId=eventIdForAppointment(data.appointmentId);await prepareCalendarWrite({provider:'shared_google',calendarId,eventId,appointmentId:data.appointmentId,staffName:data.staffName,startsAt:data.startsAt,endsAt:data.endsAt,cancelEvent:cancelBookingEventOnCalendar});return createBookingEventOnCalendar(calendarId,data);}
async function createBookingEventOnCalendar(calendarId,{appointmentId,clientName,serviceName,staffName,locationName,startsAt,endsAt,source="shiloh"}){const eventId=eventIdForAppointment(appointmentId),body={id:eventId,summary:bookingSummary({clientName,serviceName,staffName}),description:bookingDescription({appointmentId,clientName,serviceName,staffName,locationName,source}),start:{dateTime:new Date(startsAt).toISOString(),timeZone:DEFAULT_TIMEZONE},end:{dateTime:new Date(endsAt).toISOString(),timeZone:DEFAULT_TIMEZONE},extendedProperties:{private:{shilohAppointmentId:String(appointmentId),shilohSource:String(source),...(staffName?{shilohStaffName:String(staffName)}:{}),...(serviceName?{shilohServiceName:String(serviceName)}:{})}}};try{return{enabled:true,event:await googleRequest(`/calendars/${encodeURIComponent(calendarId)}/events`,{method:"POST",body:JSON.stringify(body)})};}catch(e){if(e.status!==409)throw e;return{enabled:true,event:await getBookingEventOnCalendar(eventId,calendarId),idempotentReplay:true};}}
async function getBookingEvent(eventId){if(!calendarEnabled())return null;return getBookingEventOnCalendar(eventId,requireCalendarConfig().calendarId);} async function getBookingEventOnCalendar(eventId,calendarId){try{return await googleRequest(`/calendars/${encodeURIComponent(calendarId)}/events/${encodeURIComponent(eventId)}`);}catch(e){if(e.status===404||e.status===410)return null;throw e;}}
async function findBookingEventByAppointmentId(id){if(!calendarEnabled())return null;return findBookingEventByAppointmentIdOnCalendar(id,requireCalendarConfig().calendarId);} async function findBookingEventByAppointmentIdOnCalendar(id,calendarId){const q=new URLSearchParams({privateExtendedProperty:`shilohAppointmentId=${id}`,singleEvents:"true",showDeleted:"false",maxResults:"10"}),r=await googleRequest(`/calendars/${encodeURIComponent(calendarId)}/events?${q}`);return(r.items||[])[0]||null;}
function buildBookingPatch(current,{appointmentId,startsAt,endsAt,clientName,serviceName,staffName,locationName}){const p=current.extendedProperties?.private||{},aid=appointmentId||p.shilohAppointmentId||null,source=p.shilohSource||"shiloh",service=serviceName||p.shilohServiceName||null,staff=staffName||p.shilohStaffName||null,patch={summary:bookingSummary({clientName,serviceName:service,staffName:staff}),description:bookingDescription({appointmentId:aid||"",clientName,serviceName:service,staffName:staff,locationName,source}),extendedProperties:{private:{...p,...(aid?{shilohAppointmentId:String(aid)}:{}),shilohSource:String(source),...(staff?{shilohStaffName:String(staff)}:{}),...(service?{shilohServiceName:String(service)}:{})}}};if(startsAt)patch.start={dateTime:new Date(startsAt).toISOString(),timeZone:DEFAULT_TIMEZONE};if(endsAt)patch.end={dateTime:new Date(endsAt).toISOString(),timeZone:DEFAULT_TIMEZONE};return patch;}
async function updateBookingEventOnCalendar(calendarId,{eventId,appointmentId,startsAt,endsAt,clientName,serviceName,staffName,locationName}){if(!calendarEnabled())return{enabled:false,event:null};const current=await getBookingEventOnCalendar(eventId,calendarId);if(!current)throw new Error(`Google Calendar event ${eventId} was not found for update.`);const patch=buildBookingPatch(current,{appointmentId,startsAt,endsAt,clientName,serviceName,staffName,locationName});return{enabled:true,event:await googleRequest(`/calendars/${encodeURIComponent(calendarId)}/events/${encodeURIComponent(eventId)}`,{method:"PATCH",body:JSON.stringify(patch)})};}
async function upsertBookingEventOnCalendar(calendarId,data){const eventId=data.eventId||eventIdForAppointment(data.appointmentId);const existing=await getBookingEventOnCalendar(eventId,calendarId);if(existing)return updateBookingEventOnCalendar(calendarId,{...data,eventId});return createBookingEventOnCalendar(calendarId,data);}
async function updateBookingEvent(data){if(!calendarEnabled())return{enabled:false,event:null};const sharedCalendarId=requireCalendarConfig().calendarId;const current=await getBookingEventOnCalendar(data.eventId,sharedCalendarId);if(!current)throw new Error(`Google Calendar event ${data.eventId} was not found for update.`);const oldStaff=current.extendedProperties?.private?.shilohStaffName||null;const shared=await updateBookingEventOnCalendar(sharedCalendarId,data);const oldCalendarId=practitionerCalendarIdForStaff(oldStaff),newCalendarId=practitionerCalendarIdForStaff(data.staffName||oldStaff);if(oldCalendarId&&oldCalendarId!==newCalendarId){await cancelBookingEventOnCalendar(data.eventId,oldCalendarId);}let practitioner=null;if(newCalendarId&&newCalendarId!==sharedCalendarId){practitioner=await upsertBookingEventOnCalendar(newCalendarId,{...data,eventId:data.eventId});}return{...shared,practitionerEvent:practitioner?.event||null,practitionerCalendarId:newCalendarId||null};}
async function cancelBookingEventOnCalendar(eventId,calendarId){if(!calendarEnabled())return{enabled:false,cancelled:false};try{await googleRequest(`/calendars/${encodeURIComponent(calendarId)}/events/${encodeURIComponent(eventId)}`,{method:"DELETE"});return{enabled:true,cancelled:true};}catch(e){if(e.status===404||e.status===410)return{enabled:true,cancelled:true,alreadyMissing:true};throw e;}}
async function cancelBookingEvent(eventId){if(!calendarEnabled())return{enabled:false,cancelled:false};const sharedCalendarId=requireCalendarConfig().calendarId,current=await getBookingEventOnCalendar(eventId,sharedCalendarId),staffName=current?.extendedProperties?.private?.shilohStaffName||null,practitionerCalendarId=practitionerCalendarIdForStaff(staffName);let practitioner=null;if(practitionerCalendarId&&practitionerCalendarId!==sharedCalendarId){practitioner=await cancelBookingEventOnCalendar(eventId,practitionerCalendarId);}const shared=await cancelBookingEventOnCalendar(eventId,sharedCalendarId);return{...shared,practitionerCancelled:Boolean(practitioner?.cancelled),practitionerCalendarId:practitionerCalendarId||null};}
module.exports={calendarEnabled,authMode,practitionerCalendarIdForStaff,checkCalendarAvailability,checkCalendarAvailabilityOnCalendar,createBookingEvent,createBookingEventOnCalendar,getBookingEvent,getBookingEventOnCalendar,findBookingEventByAppointmentId,findBookingEventByAppointmentIdOnCalendar,updateBookingEvent,updateBookingEventOnCalendar,cancelBookingEvent,cancelBookingEventOnCalendar,deterministicEventId,eventIdForAppointment,bookingSummary,serviceIcon};