const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const {evaluateCalendarAuthority,retrospectiveClientAllows,allowsRetrospectiveBookingTarget,RETROSPECTIVE_CLIENT_IDS_KEY}=require('../src/services/calendarAuthorization');
const {permissionClientRestriction,clientRestrictionAllows}=require('../src/services/calendarRetrospectiveBooking');
const {policyProjection,normalizedRetrospectiveClientIds}=require('../src/services/workspaceStaffAccessPolicy');
function authority(overrides={}){return evaluateCalendarAuthority({id:7,staff_id:17,admin_active:true,staff_status:'active',business_role:'employee_practitioner',calendar_scope:'own_appointments',service_scope:'own_services',permissions:{'appointment:create':true,'appointment:record_past':true,...overrides}},{allowedServiceIds:[44]});}
test('retrospective requires both dedicated and ordinary creation capabilities',()=>{for(const permissions of [{},{'appointment:create':true},{'appointment:record_past':true}])assert.equal(allowsRetrospectiveBookingTarget(evaluateCalendarAuthority({id:7,staff_id:17,admin_active:true,staff_status:'active',calendar_scope:'own_appointments',service_scope:'own_services',permissions},{allowedServiceIds:[44]}),{clientId:81,staffId:17,serviceId:44}),false);assert.equal(allowsRetrospectiveBookingTarget(authority(),{clientId:81,staffId:17,serviceId:44}),true)});
test('conditioned canonical client IDs allow only exact IDs and malformed conditions deny all',()=>{const allowed=authority({[RETROSPECTIVE_CLIENT_IDS_KEY]:[81,'81']});assert.deepEqual(allowed.retrospectiveClientIds,[81]);assert.equal(retrospectiveClientAllows(allowed,81),true);assert.equal(retrospectiveClientAllows(allowed,82),false);assert.deepEqual(authority({[RETROSPECTIVE_CLIENT_IDS_KEY]:'81'}).retrospectiveClientIds,[])});
test('unrestricted grant remains subject to existing staff and service scopes',()=>{const a=authority();assert.equal(retrospectiveClientAllows(a,999),true);assert.equal(allowsRetrospectiveBookingTarget(a,{clientId:999,staffId:18,serviceId:44}),false);assert.equal(allowsRetrospectiveBookingTarget(a,{clientId:999,staffId:17,serviceId:45}),false)});
test('condition helpers never use names and fail closed for malformed data',()=>{assert.deepEqual(permissionClientRestriction({permissions:{[RETROSPECTIVE_CLIENT_IDS_KEY]:[4,3,4]}}),[3,4]);assert.deepEqual(permissionClientRestriction({permissions:{[RETROSPECTIVE_CLIENT_IDS_KEY]:'JP'}}),[]);assert.equal(clientRestrictionAllows({permissions:{[RETROSPECTIVE_CLIENT_IDS_KEY]:[4]}},5),false)});
test('Staff Access projects a bounded retrospective editor only for an active linked creator',()=>{const staff={id:17,status:'active',resource_type:'practitioner',business_role:'employee_practitioner'};const row={id:3,staff_id:17,active:true,role:'practitioner',business_role:'employee_practitioner',calendar_scope:'own_appointments',service_scope:'own_services',permissions:{'appointment:create':true,'appointment:record_past':true,[RETROSPECTIVE_CLIENT_IDS_KEY]:[81]}};const p=policyProjection(staff,[row]);assert.equal(p.supported,true);assert.deepEqual(p.capabilities,['appointment:record_past']);assert.deepEqual(p.retrospectiveClientIds,[81]);assert.deepEqual(p.definitions.map(x=>x.key),['appointment:record_past','appointment:adjust_end']);assert.equal(policyProjection({...staff,status:'inactive'},[row]).supported,false)});
test('Staff Access condition normalization accepts positive canonical IDs and rejects malformed values',()=>{assert.deepEqual(normalizedRetrospectiveClientIds({[RETROSPECTIVE_CLIENT_IDS_KEY]:[9,'8',9]}),[8,9]);assert.equal(normalizedRetrospectiveClientIds({[RETROSPECTIVE_CLIENT_IDS_KEY]:['name']}),false);assert.equal(normalizedRetrospectiveClientIds({}),null)});
test('service enforces ended-at strictly and persists unresolved canonical shape plus mandatory audit transaction',()=>{const source=fs.readFileSync(require.resolve('../src/services/calendarRetrospectiveBooking'),'utf8');assert.match(source,/end\.getTime\(\) >= now\(\)\.getTime\(\)/);assert.match(source,/INSERT INTO appointments/);assert.match(source,/'unknown'/);assert.match(source,/calendar\.past_appointment_recorded/);assert.match(source,/await client\.query\('COMMIT'\)/);assert.match(source,/await client\.query\('ROLLBACK'\)/);assert.doesNotMatch(source,/sendWhatsApp|queueCustomer|appointmentLifecycle|payment|deposit/i)});
test('route remains session, same-origin and CSRF guarded without future client:lookup service',()=>{const source=fs.readFileSync(require.resolve('../src/routes/calendarRetrospectiveBooking'),'utf8');assert.match(source,/sameOrigin, requireSession, requireCsrf/);assert.match(source,/service\.searchClients/);assert.doesNotMatch(source,/createCalendarCreateBookingService/)});
test('review UI states billing, notification and future automation effects',()=>{const source=fs.readFileSync(require.resolve('../src/presentation/calendarRetrospectiveBookingUx'),'utf8');assert.match(source,/does not change historical billing or subscription state/);assert.match(source,/queue or resend client notifications/);assert.match(source,/alter future automation state/)});
