-- Shiloh CRM client foundation.
-- Adds canonical client identities and contact methods alongside legacy user_profiles.
-- Existing WhatsApp/profile behaviour is intentionally left unchanged.

CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name TEXT,
  preferred_language TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  preferences JSONB NOT NULL DEFAULT '{}'::jsonb,
  tags TEXT[] NOT NULL DEFAULT '{}'::text[],
  custom_attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
  source TEXT NOT NULL DEFAULT 'shiloh',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS client_contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  contact_type TEXT NOT NULL,
  value TEXT NOT NULL,
  normalized_value TEXT NOT NULL,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT client_contacts_type_check
    CHECK (contact_type IN ('whatsapp', 'mobile', 'email', 'other')),
  CONSTRAINT client_contacts_type_normalized_unique
    UNIQUE (contact_type, normalized_value)
);

CREATE INDEX IF NOT EXISTS idx_client_contacts_client_id
  ON client_contacts(client_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_client_contacts_one_primary_per_type
  ON client_contacts(client_id, contact_type)
  WHERE is_primary = TRUE;

CREATE INDEX IF NOT EXISTS idx_clients_status
  ON clients(status);

-- Backfill current WhatsApp profiles without modifying user_profiles.
-- A procedural loop preserves a direct one-profile-to-one-client mapping while
-- remaining idempotent when the migration is retried in a non-production copy.
DO $$
DECLARE
  profile RECORD;
  new_client_id BIGINT;
  normalized_phone TEXT;
BEGIN
  FOR profile IN
    SELECT
      phone,
      name,
      preferred_language,
      customer_status,
      preferences,
      tags,
      custom_attributes,
      created_at,
      updated_at
    FROM user_profiles
    ORDER BY created_at, phone
  LOOP
    normalized_phone := regexp_replace(profile.phone, '[^0-9]', '', 'g');

    IF normalized_phone = '' OR EXISTS (
      SELECT 1
      FROM client_contacts
      WHERE contact_type = 'whatsapp'
        AND normalized_value = normalized_phone
    ) THEN
      CONTINUE;
    END IF;

    INSERT INTO clients (
      display_name,
      preferred_language,
      status,
      preferences,
      tags,
      custom_attributes,
      source,
      created_at,
      updated_at
    )
    VALUES (
      profile.name,
      profile.preferred_language,
      COALESCE(NULLIF(profile.customer_status, ''), 'active'),
      COALESCE(profile.preferences, '{}'::jsonb),
      COALESCE(profile.tags, '{}'::text[]),
      COALESCE(profile.custom_attributes, '{}'::jsonb),
      'legacy_user_profile',
      COALESCE(profile.created_at, NOW()),
      COALESCE(profile.updated_at, NOW())
    )
    RETURNING id INTO new_client_id;

    INSERT INTO client_contacts (
      client_id,
      contact_type,
      value,
      normalized_value,
      is_primary,
      created_at,
      updated_at
    )
    VALUES (
      new_client_id,
      'whatsapp',
      profile.phone,
      normalized_phone,
      TRUE,
      COALESCE(profile.created_at, NOW()),
      COALESCE(profile.updated_at, NOW())
    );
  END LOOP;
END $$;
