-- Shiloh CRM clinic catalogue and resources foundation.
-- Generated from Goldie export dated 2026-08-09.
-- Preserves Goldie names/IDs as source data; does not change legacy bot tables.

CREATE TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  timezone TEXT NOT NULL DEFAULT 'Africa/Johannesburg',
  phone TEXT,
  email TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  external_source TEXT,
  external_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT locations_status_check CHECK (status IN ('active','inactive')),
  CONSTRAINT locations_external_unique UNIQUE (external_source, external_id)
);

CREATE TABLE IF NOT EXISTS service_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  display_order INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT service_categories_status_check CHECK (status IN ('active','inactive'))
);

CREATE TABLE IF NOT EXISTS staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name TEXT NOT NULL,
  resource_type TEXT NOT NULL DEFAULT 'practitioner',
  status TEXT NOT NULL DEFAULT 'active',
  source_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT staff_resource_type_check CHECK (resource_type IN ('practitioner','business_resource')),
  CONSTRAINT staff_status_check CHECK (status IN ('active','inactive')),
  CONSTRAINT staff_source_name_unique UNIQUE (source_name)
);

CREATE TABLE IF NOT EXISTS services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT REFERENCES service_categories(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  duration_minutes INTEGER NOT NULL,
  processing_time_minutes INTEGER NOT NULL DEFAULT 0,
  extra_time_minutes INTEGER NOT NULL DEFAULT 0,
  variable_price BOOLEAN NOT NULL DEFAULT FALSE,
  price NUMERIC(12,2),
  display_price TEXT,
  color_value BIGINT,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  status TEXT NOT NULL DEFAULT 'active',
  external_source TEXT,
  external_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT services_duration_check CHECK (duration_minutes >= 0 AND processing_time_minutes >= 0 AND extra_time_minutes >= 0),
  CONSTRAINT services_status_check CHECK (status IN ('active','inactive')),
  CONSTRAINT services_external_unique UNIQUE (external_source, external_id)
);

CREATE TABLE IF NOT EXISTS staff_services (
  staff_id BIGINT NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
  service_id BIGINT NOT NULL REFERENCES services(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (staff_id, service_id)
);

CREATE INDEX IF NOT EXISTS idx_services_category_id ON services(category_id);
CREATE INDEX IF NOT EXISTS idx_services_status ON services(status);
CREATE INDEX IF NOT EXISTS idx_staff_status ON staff(status);
CREATE INDEX IF NOT EXISTS idx_staff_services_service_id ON staff_services(service_id);

INSERT INTO locations (name, timezone, phone, email, status, external_source, external_id)
VALUES ('Shiloh Massage Therapy and Aesthetic Clinic', 'Africa/Johannesburg', '+27662399138', 'shilohmtc@gmail.com', 'active', 'goldie', 'ac38b19d-0751-4a01-9a3c-c8870562b83f')
ON CONFLICT (external_source, external_id) DO UPDATE SET
  name=EXCLUDED.name, timezone=EXCLUDED.timezone, phone=EXCLUDED.phone, email=EXCLUDED.email, status='active', updated_at=NOW();

INSERT INTO service_categories (name, display_order) VALUES ('Pedicures & Foot Care', 1) ON CONFLICT (name) DO UPDATE SET display_order=EXCLUDED.display_order, status='active', updated_at=NOW();
INSERT INTO service_categories (name, display_order) VALUES ('Facials', 2) ON CONFLICT (name) DO UPDATE SET display_order=EXCLUDED.display_order, status='active', updated_at=NOW();
INSERT INTO service_categories (name, display_order) VALUES ('Massage', 3) ON CONFLICT (name) DO UPDATE SET display_order=EXCLUDED.display_order, status='active', updated_at=NOW();
INSERT INTO service_categories (name, display_order) VALUES ('Permanant Makeup', 4) ON CONFLICT (name) DO UPDATE SET display_order=EXCLUDED.display_order, status='active', updated_at=NOW();
INSERT INTO service_categories (name, display_order) VALUES ('Mikroneedling', 5) ON CONFLICT (name) DO UPDATE SET display_order=EXCLUDED.display_order, status='active', updated_at=NOW();
INSERT INTO service_categories (name, display_order) VALUES ('Profosma Jet Plasma', 6) ON CONFLICT (name) DO UPDATE SET display_order=EXCLUDED.display_order, status='active', updated_at=NOW();
INSERT INTO service_categories (name, display_order) VALUES ('Plasma Fybroblast Consultation', 7) ON CONFLICT (name) DO UPDATE SET display_order=EXCLUDED.display_order, status='active', updated_at=NOW();
INSERT INTO service_categories (name, display_order) VALUES ('Pressotherapy', 8) ON CONFLICT (name) DO UPDATE SET display_order=EXCLUDED.display_order, status='active', updated_at=NOW();
INSERT INTO service_categories (name, display_order) VALUES ('Plasma Fybroblast Prices', 9) ON CONFLICT (name) DO UPDATE SET display_order=EXCLUDED.display_order, status='active', updated_at=NOW();
INSERT INTO service_categories (name, display_order) VALUES ('Ozone & Far Infrared', 10) ON CONFLICT (name) DO UPDATE SET display_order=EXCLUDED.display_order, status='active', updated_at=NOW();
INSERT INTO service_categories (name, display_order) VALUES ('1. SQT BoiMicroneedling', 11) ON CONFLICT (name) DO UPDATE SET display_order=EXCLUDED.display_order, status='active', updated_at=NOW();
INSERT INTO service_categories (name, display_order) VALUES ('2. SQT BioMicroneedling', 12) ON CONFLICT (name) DO UPDATE SET display_order=EXCLUDED.display_order, status='active', updated_at=NOW();
INSERT INTO service_categories (name, display_order) VALUES ('Facial Waxing', 13) ON CONFLICT (name) DO UPDATE SET display_order=EXCLUDED.display_order, status='active', updated_at=NOW();
INSERT INTO service_categories (name, display_order) VALUES ('HIFU', 14) ON CONFLICT (name) DO UPDATE SET display_order=EXCLUDED.display_order, status='active', updated_at=NOW();
INSERT INTO service_categories (name, display_order) VALUES ('Neo Pelvic Therapy', 15) ON CONFLICT (name) DO UPDATE SET display_order=EXCLUDED.display_order, status='active', updated_at=NOW();
INSERT INTO service_categories (name, display_order) VALUES ('Vaginal Tightening & Rejuvenation', 16) ON CONFLICT (name) DO UPDATE SET display_order=EXCLUDED.display_order, status='active', updated_at=NOW();

INSERT INTO staff (display_name, resource_type, status, source_name) VALUES ('Abigail', 'practitioner', 'active', 'Abigail .') ON CONFLICT (source_name) DO UPDATE SET display_name=EXCLUDED.display_name, resource_type=EXCLUDED.resource_type, status=EXCLUDED.status, updated_at=NOW();
INSERT INTO staff (display_name, resource_type, status, source_name) VALUES ('Alexia', 'practitioner', 'inactive', 'Alexia .') ON CONFLICT (source_name) DO UPDATE SET display_name=EXCLUDED.display_name, resource_type=EXCLUDED.resource_type, status=EXCLUDED.status, updated_at=NOW();
INSERT INTO staff (display_name, resource_type, status, source_name) VALUES ('Christel', 'practitioner', 'active', 'Christel .') ON CONFLICT (source_name) DO UPDATE SET display_name=EXCLUDED.display_name, resource_type=EXCLUDED.resource_type, status=EXCLUDED.status, updated_at=NOW();
INSERT INTO staff (display_name, resource_type, status, source_name) VALUES ('ILince', 'practitioner', 'inactive', 'ILince .') ON CONFLICT (source_name) DO UPDATE SET display_name=EXCLUDED.display_name, resource_type=EXCLUDED.resource_type, status=EXCLUDED.status, updated_at=NOW();
INSERT INTO staff (display_name, resource_type, status, source_name) VALUES ('Layla', 'practitioner', 'inactive', 'Layla .') ON CONFLICT (source_name) DO UPDATE SET display_name=EXCLUDED.display_name, resource_type=EXCLUDED.resource_type, status=EXCLUDED.status, updated_at=NOW();
INSERT INTO staff (display_name, resource_type, status, source_name) VALUES ('Marietjie', 'practitioner', 'active', 'Marietjie .') ON CONFLICT (source_name) DO UPDATE SET display_name=EXCLUDED.display_name, resource_type=EXCLUDED.resource_type, status=EXCLUDED.status, updated_at=NOW();
INSERT INTO staff (display_name, resource_type, status, source_name) VALUES ('Pieter', 'practitioner', 'active', 'Pieter .') ON CONFLICT (source_name) DO UPDATE SET display_name=EXCLUDED.display_name, resource_type=EXCLUDED.resource_type, status=EXCLUDED.status, updated_at=NOW();
INSERT INTO staff (display_name, resource_type, status, source_name) VALUES ('SHILOH MTC', 'business_resource', 'active', 'SHILOH MTC') ON CONFLICT (source_name) DO UPDATE SET display_name=EXCLUDED.display_name, resource_type=EXCLUDED.resource_type, status=EXCLUDED.status, updated_at=NOW();
INSERT INTO staff (display_name, resource_type, status, source_name) VALUES ('Savanna Massage Practitioner', 'practitioner', 'active', 'Savanna Massage Practitioner') ON CONFLICT (source_name) DO UPDATE SET display_name=EXCLUDED.display_name, resource_type=EXCLUDED.resource_type, status=EXCLUDED.status, updated_at=NOW();
INSERT INTO staff (display_name, resource_type, status, source_name) VALUES ('Yolanda', 'practitioner', 'inactive', 'Yolanda .') ON CONFLICT (source_name) DO UPDATE SET display_name=EXCLUDED.display_name, resource_type=EXCLUDED.resource_type, status=EXCLUDED.status, updated_at=NOW();

-- The 52 Goldie services and staff/service mappings will be loaded by the controlled import step after this schema migration is verified.
