-- Shiloh CRM canonical appointment and calendar model.
-- Designed from Goldie export dated 2026-08-09.
-- Supports multi-service appointments, multi-staff assignments, personal events and time off.
-- Does not import Goldie appointment data yet.

CREATE TABLE IF NOT EXISTS appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
  location_id BIGINT REFERENCES locations(id) ON DELETE SET NULL,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL DEFAULT 'scheduled',
  title TEXT,
  notes TEXT,
  total_price NUMERIC(12,2),
  currency CHAR(3) NOT NULL DEFAULT 'ZAR',
  source TEXT NOT NULL DEFAULT 'shiloh',
  external_id TEXT,
  external_key TEXT,
  source_client_name TEXT,
  source_recurrence TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT appointments_time_check CHECK (ends_at > starts_at),
  CONSTRAINT appointments_status_check CHECK (status IN ('scheduled','confirmed','completed','cancelled','no_show','unknown')),
  CONSTRAINT appointments_external_unique UNIQUE (source, external_id),
  CONSTRAINT appointments_external_key_unique UNIQUE (source, external_key)
);

CREATE INDEX IF NOT EXISTS idx_appointments_client_id ON appointments(client_id);
CREATE INDEX IF NOT EXISTS idx_appointments_location_id ON appointments(location_id);
CREATE INDEX IF NOT EXISTS idx_appointments_starts_at ON appointments(starts_at);
CREATE INDEX IF NOT EXISTS idx_appointments_status ON appointments(status);

CREATE TABLE IF NOT EXISTS appointment_services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id BIGINT NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
  service_id BIGINT REFERENCES services(id) ON DELETE SET NULL,
  position INTEGER NOT NULL DEFAULT 1,
  service_name_snapshot TEXT NOT NULL,
  price_snapshot NUMERIC(12,2),
  duration_minutes_snapshot INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT appointment_services_position_unique UNIQUE (appointment_id, position),
  CONSTRAINT appointment_services_duration_check CHECK (duration_minutes_snapshot IS NULL OR duration_minutes_snapshot >= 0)
);

CREATE INDEX IF NOT EXISTS idx_appointment_services_service_id ON appointment_services(service_id);

CREATE TABLE IF NOT EXISTS appointment_staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id BIGINT NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
  staff_id BIGINT REFERENCES staff(id) ON DELETE SET NULL,
  position INTEGER NOT NULL DEFAULT 1,
  staff_name_snapshot TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT appointment_staff_position_unique UNIQUE (appointment_id, position)
);

CREATE INDEX IF NOT EXISTS idx_appointment_staff_staff_id ON appointment_staff(staff_id);

CREATE TABLE IF NOT EXISTS appointment_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id BIGINT NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
  from_status TEXT,
  to_status TEXT NOT NULL,
  changed_by TEXT,
  reason TEXT,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_appointment_status_history_appointment_id
  ON appointment_status_history(appointment_id, changed_at);

CREATE TABLE IF NOT EXISTS calendar_blocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT REFERENCES staff(id) ON DELETE SET NULL,
  location_id BIGINT REFERENCES locations(id) ON DELETE SET NULL,
  block_type TEXT NOT NULL,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  title TEXT,
  notes TEXT,
  recurrence_text TEXT,
  source TEXT NOT NULL DEFAULT 'shiloh',
  external_id TEXT,
  external_key TEXT,
  source_staff_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT calendar_blocks_type_check CHECK (block_type IN ('time_off','personal_event','other')),
  CONSTRAINT calendar_blocks_time_check CHECK (ends_at > starts_at),
  CONSTRAINT calendar_blocks_external_unique UNIQUE (source, external_id),
  CONSTRAINT calendar_blocks_external_key_unique UNIQUE (source, external_key)
);

CREATE INDEX IF NOT EXISTS idx_calendar_blocks_staff_id ON calendar_blocks(staff_id);
CREATE INDEX IF NOT EXISTS idx_calendar_blocks_starts_at ON calendar_blocks(starts_at);
CREATE INDEX IF NOT EXISTS idx_calendar_blocks_type ON calendar_blocks(block_type);

-- Note: Goldie appointment/calendar rows are imported separately after client reconciliation.
-- Goldie's CSV does not expose stable appointment IDs, so the import will use deterministic external_key hashes.
