-- Shiloh OS external identity and client reconciliation foundation.
-- Designed for safe Goldie migration without treating phone numbers as canonical identity.
-- This migration adds provenance, import batches, source-record staging and reconciliation workflow.
-- It does not import Goldie client rows yet and does not modify legacy WhatsApp tables.

CREATE TABLE IF NOT EXISTS import_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source TEXT NOT NULL,
  source_file TEXT,
  source_exported_at TIMESTAMPTZ,
  checksum TEXT,
  status TEXT NOT NULL DEFAULT 'staged',
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  CONSTRAINT import_batches_status_check
    CHECK (status IN ('staged','processing','completed','failed','cancelled'))
);

CREATE INDEX IF NOT EXISTS idx_import_batches_source_created_at
  ON import_batches(source, created_at DESC);

CREATE TABLE IF NOT EXISTS external_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_batch_id BIGINT REFERENCES import_batches(id) ON DELETE SET NULL,
  source TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  external_id TEXT NOT NULL,
  shiloh_entity_type TEXT,
  shiloh_entity_id BIGINT,
  reconciliation_status TEXT NOT NULL DEFAULT 'unmatched',
  match_method TEXT,
  match_confidence NUMERIC(5,4),
  source_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  reconciled_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT external_records_source_identity_unique
    UNIQUE (source, entity_type, external_id),
  CONSTRAINT external_records_reconciliation_status_check
    CHECK (reconciliation_status IN ('unmatched','matched','ambiguous','ignored','error')),
  CONSTRAINT external_records_confidence_check
    CHECK (match_confidence IS NULL OR (match_confidence >= 0 AND match_confidence <= 1)),
  CONSTRAINT external_records_shiloh_link_check
    CHECK (
      (shiloh_entity_type IS NULL AND shiloh_entity_id IS NULL)
      OR (shiloh_entity_type IS NOT NULL AND shiloh_entity_id IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_external_records_source_entity
  ON external_records(source, entity_type);
CREATE INDEX IF NOT EXISTS idx_external_records_reconciliation_status
  ON external_records(reconciliation_status);
CREATE INDEX IF NOT EXISTS idx_external_records_shiloh_entity
  ON external_records(shiloh_entity_type, shiloh_entity_id)
  WHERE shiloh_entity_id IS NOT NULL;

-- Goldie client records are staged here before they are merged into canonical clients.
-- Contact values are intentionally non-unique because Goldie contains shared/duplicated phone numbers.
CREATE TABLE IF NOT EXISTS external_client_records (
  external_record_id BIGINT PRIMARY KEY REFERENCES external_records(id) ON DELETE CASCADE,
  external_client_id TEXT NOT NULL,
  display_name TEXT,
  email TEXT,
  phone TEXT,
  normalized_phone TEXT,
  secondary_phone TEXT,
  normalized_secondary_phone TEXT,
  address TEXT,
  notes TEXT,
  has_photo BOOLEAN NOT NULL DEFAULT FALSE,
  is_blocked BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT external_client_records_external_id_unique UNIQUE (external_client_id)
);

CREATE INDEX IF NOT EXISTS idx_external_client_records_normalized_phone
  ON external_client_records(normalized_phone)
  WHERE normalized_phone IS NOT NULL AND normalized_phone <> '';
CREATE INDEX IF NOT EXISTS idx_external_client_records_email_lower
  ON external_client_records(LOWER(email))
  WHERE email IS NOT NULL AND email <> '';
CREATE INDEX IF NOT EXISTS idx_external_client_records_display_name_lower
  ON external_client_records(LOWER(display_name))
  WHERE display_name IS NOT NULL AND display_name <> '';

CREATE TABLE IF NOT EXISTS client_reconciliation_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_record_id BIGINT NOT NULL UNIQUE REFERENCES external_records(id) ON DELETE CASCADE,
  candidate_client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  reason TEXT NOT NULL,
  candidate_score NUMERIC(5,4),
  evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
  resolution TEXT,
  resolved_client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
  resolved_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at TIMESTAMPTZ,
  CONSTRAINT client_reconciliation_queue_status_check
    CHECK (status IN ('pending','matched','create_new','ignored','needs_review')),
  CONSTRAINT client_reconciliation_queue_score_check
    CHECK (candidate_score IS NULL OR (candidate_score >= 0 AND candidate_score <= 1))
);

CREATE INDEX IF NOT EXISTS idx_client_reconciliation_queue_status
  ON client_reconciliation_queue(status, created_at);
CREATE INDEX IF NOT EXISTS idx_client_reconciliation_queue_candidate
  ON client_reconciliation_queue(candidate_client_id)
  WHERE candidate_client_id IS NOT NULL;

-- Audit trail for every reconciliation decision, including automated matches.
CREATE TABLE IF NOT EXISTS client_reconciliation_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_record_id BIGINT NOT NULL REFERENCES external_records(id) ON DELETE CASCADE,
  client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  method TEXT,
  confidence NUMERIC(5,4),
  evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
  performed_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT client_reconciliation_history_action_check
    CHECK (action IN ('matched','created','unmatched','ambiguous','ignored','relinked')),
  CONSTRAINT client_reconciliation_history_confidence_check
    CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))
);

CREATE INDEX IF NOT EXISTS idx_client_reconciliation_history_external_record
  ON client_reconciliation_history(external_record_id, created_at);
CREATE INDEX IF NOT EXISTS idx_client_reconciliation_history_client
  ON client_reconciliation_history(client_id, created_at)
  WHERE client_id IS NOT NULL;

-- No Goldie client rows are imported by this migration. The next controlled import
-- will stage all 975 source records here, preserve every Goldie UUID, and reconcile
-- them against canonical Shiloh clients without violating client_contacts uniqueness.
