-- CRM-1: WhatsApp Admin Assistant / walk-in registration.
-- Adds staff-authenticated admin accounts, persistent walk-in sessions, and CRM audit events.

CREATE TABLE IF NOT EXISTS staff_admin_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT REFERENCES staff(id) ON DELETE SET NULL,
  display_name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'manager',
  whatsapp_number TEXT NOT NULL UNIQUE,
  normalized_whatsapp TEXT NOT NULL UNIQUE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  permissions JSONB NOT NULL DEFAULT '{"walkin:create":true,"client:lookup":true}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS walkin_registration_sessions (
  admin_id BIGINT PRIMARY KEY REFERENCES staff_admin_accounts(id) ON DELETE CASCADE,
  state TEXT NOT NULL DEFAULT 'collect_name',
  pending_name TEXT,
  pending_phone TEXT,
  pending_date_of_birth DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT walkin_registration_state_check CHECK (
    state IN ('collect_name','collect_phone','collect_dob','confirm')
  )
);

CREATE TABLE IF NOT EXISTS crm_audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_admin_id BIGINT REFERENCES staff_admin_accounts(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id BIGINT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crm_audit_events_created_at ON crm_audit_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_crm_audit_events_entity ON crm_audit_events(entity_type, entity_id);

INSERT INTO staff_admin_accounts (staff_id, display_name, role, whatsapp_number, normalized_whatsapp)
SELECT id, 'Marietjie', 'manager', '+27828733375', '27828733375'
FROM staff WHERE LOWER(display_name) = 'marietjie' ORDER BY id LIMIT 1
ON CONFLICT (normalized_whatsapp) DO UPDATE SET staff_id=EXCLUDED.staff_id, display_name=EXCLUDED.display_name, role=EXCLUDED.role, active=TRUE, updated_at=NOW();

INSERT INTO staff_admin_accounts (staff_id, display_name, role, whatsapp_number, normalized_whatsapp)
SELECT id, 'Christel', 'manager', '+27825726381', '27825726381'
FROM staff WHERE LOWER(display_name) = 'christel' ORDER BY id LIMIT 1
ON CONFLICT (normalized_whatsapp) DO UPDATE SET staff_id=EXCLUDED.staff_id, display_name=EXCLUDED.display_name, role=EXCLUDED.role, active=TRUE, updated_at=NOW();

INSERT INTO staff_admin_accounts (staff_id, display_name, role, whatsapp_number, normalized_whatsapp)
SELECT id, 'Abigail', 'manager', '+27754034706', '27754034706'
FROM staff WHERE LOWER(display_name) = 'abigail' ORDER BY id LIMIT 1
ON CONFLICT (normalized_whatsapp) DO UPDATE SET staff_id=EXCLUDED.staff_id, display_name=EXCLUDED.display_name, role=EXCLUDED.role, active=TRUE, updated_at=NOW();
