-- CRM-3: Google Calendar booking bridge.
-- PostgreSQL remains the canonical CRM record; Google Calendar is the shared
-- operational schedule and authoritative external collision check.

CREATE TABLE IF NOT EXISTS appointment_calendar_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id BIGINT NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
  provider TEXT NOT NULL DEFAULT 'google_calendar',
  calendar_id TEXT NOT NULL,
  event_id TEXT NOT NULL,
  sync_status TEXT NOT NULL DEFAULT 'synced',
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT appointment_calendar_events_provider_check CHECK (provider IN ('google_calendar')),
  CONSTRAINT appointment_calendar_events_sync_status_check CHECK (sync_status IN ('synced','pending','error','cancelled')),
  CONSTRAINT appointment_calendar_events_appointment_unique UNIQUE (appointment_id, provider),
  CONSTRAINT appointment_calendar_events_event_unique UNIQUE (provider, calendar_id, event_id)
);

CREATE INDEX IF NOT EXISTS idx_appointment_calendar_events_event
  ON appointment_calendar_events(provider, calendar_id, event_id);

CREATE INDEX IF NOT EXISTS idx_appointment_calendar_events_sync_status
  ON appointment_calendar_events(sync_status);
