-- CRM-2 authoritative scheduling foundation.
-- New forward-only schema; does not alter historical Goldie migrations or reconciliation data.

CREATE TABLE IF NOT EXISTS staff_working_hours (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
  location_id BIGINT REFERENCES locations(id) ON DELETE CASCADE,
  day_of_week SMALLINT NOT NULL,
  starts_local TIME NOT NULL,
  ends_local TIME NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT staff_working_hours_day_check CHECK (day_of_week BETWEEN 0 AND 6),
  CONSTRAINT staff_working_hours_time_check CHECK (ends_local > starts_local)
);

CREATE INDEX IF NOT EXISTS idx_staff_working_hours_staff_day
  ON staff_working_hours(staff_id, day_of_week, active);

CREATE TABLE IF NOT EXISTS staff_schedule_exceptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
  location_id BIGINT REFERENCES locations(id) ON DELETE CASCADE,
  exception_date DATE NOT NULL,
  exception_type TEXT NOT NULL,
  starts_local TIME,
  ends_local TIME,
  reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT staff_schedule_exceptions_type_check CHECK (exception_type IN ('unavailable','available')),
  CONSTRAINT staff_schedule_exceptions_time_pair_check CHECK (
    (starts_local IS NULL AND ends_local IS NULL)
    OR (starts_local IS NOT NULL AND ends_local IS NOT NULL AND ends_local > starts_local)
  )
);

CREATE INDEX IF NOT EXISTS idx_staff_schedule_exceptions_staff_date
  ON staff_schedule_exceptions(staff_id, exception_date);
