-- CRM-2 authoritative clinic operating-hours envelope.
-- Practitioner schedules remain separate and must fit inside these location hours.

CREATE TABLE IF NOT EXISTS location_working_hours (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  day_of_week INTEGER NOT NULL,
  starts_local TIME NOT NULL,
  ends_local TIME NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT location_working_hours_day_check CHECK (day_of_week BETWEEN 0 AND 6),
  CONSTRAINT location_working_hours_time_check CHECK (ends_local > starts_local),
  CONSTRAINT location_working_hours_unique UNIQUE (location_id, day_of_week, starts_local, ends_local)
);

CREATE INDEX IF NOT EXISTS idx_location_working_hours_location_day
  ON location_working_hours(location_id, day_of_week)
  WHERE active = TRUE;

WITH clinic AS (
  SELECT id
    FROM locations
   WHERE status = 'active'
     AND name = 'Shiloh Massage Therapy and Aesthetic Clinic'
   ORDER BY id
   LIMIT 1
)
INSERT INTO location_working_hours (location_id, day_of_week, starts_local, ends_local, active)
SELECT id, d.day_of_week, d.starts_local::time, d.ends_local::time, TRUE
FROM clinic
CROSS JOIN (VALUES
  (1, '08:00', '17:00'),
  (2, '08:00', '17:00'),
  (3, '08:00', '17:00'),
  (4, '08:00', '17:00'),
  (5, '08:00', '17:00'),
  (6, '08:00', '14:00')
) AS d(day_of_week, starts_local, ends_local)
ON CONFLICT (location_id, day_of_week, starts_local, ends_local)
DO UPDATE SET active = TRUE, updated_at = NOW();

-- Sunday (0) intentionally has no active window: clinic closed.
