-- CRM-2 South African public holidays and date-specific clinic hours.
-- Public holidays are closed by default until an admin explicitly confirms CLOSED
-- or sets special opening hours for that date.

CREATE TABLE IF NOT EXISTS public_holidays (
  holiday_date DATE PRIMARY KEY,
  name TEXT NOT NULL,
  country_code TEXT NOT NULL DEFAULT 'ZA',
  observed BOOLEAN NOT NULL DEFAULT FALSE,
  source TEXT NOT NULL DEFAULT 'gov.za',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS location_hours_exceptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  exception_date DATE NOT NULL,
  exception_type TEXT NOT NULL,
  starts_local TIME,
  ends_local TIME,
  reason TEXT,
  actor_admin_id BIGINT REFERENCES staff_admin_accounts(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT location_hours_exceptions_type_check CHECK (exception_type IN ('open','closed')),
  CONSTRAINT location_hours_exceptions_shape_check CHECK (
    (exception_type='closed' AND starts_local IS NULL AND ends_local IS NULL)
    OR
    (exception_type='open' AND starts_local IS NOT NULL AND ends_local IS NOT NULL AND ends_local > starts_local)
  ),
  CONSTRAINT location_hours_exceptions_unique UNIQUE (location_id, exception_date)
);

CREATE INDEX IF NOT EXISTS idx_public_holidays_country_date
  ON public_holidays(country_code, holiday_date);
CREATE INDEX IF NOT EXISTS idx_location_hours_exceptions_location_date
  ON location_hours_exceptions(location_id, exception_date);

-- Official South African Government public-holiday calendar, 2026.
INSERT INTO public_holidays (holiday_date,name,observed,source) VALUES
('2026-01-01','New Year''s Day',FALSE,'gov.za'),
('2026-03-21','Human Rights Day',FALSE,'gov.za'),
('2026-04-03','Good Friday',FALSE,'gov.za'),
('2026-04-06','Family Day',FALSE,'gov.za'),
('2026-04-27','Freedom Day',FALSE,'gov.za'),
('2026-05-01','Workers'' Day',FALSE,'gov.za'),
('2026-06-16','Youth Day',FALSE,'gov.za'),
('2026-08-09','National Women''s Day',FALSE,'gov.za'),
('2026-08-10','National Women''s Day observed',TRUE,'gov.za'),
('2026-09-24','Heritage Day',FALSE,'gov.za'),
('2026-12-16','Day of Reconciliation',FALSE,'gov.za'),
('2026-12-25','Christmas Day',FALSE,'gov.za'),
('2026-12-26','Day of Goodwill',FALSE,'gov.za')
ON CONFLICT (holiday_date) DO UPDATE SET
  name=EXCLUDED.name, country_code='ZA', observed=EXCLUDED.observed,
  source=EXCLUDED.source, updated_at=NOW();

-- Official South African Government public-holiday calendar, 2027.
INSERT INTO public_holidays (holiday_date,name,observed,source) VALUES
('2027-01-01','New Year''s Day',FALSE,'gov.za'),
('2027-03-21','Human Rights Day',FALSE,'gov.za'),
('2027-03-22','Human Rights Day observed',TRUE,'gov.za'),
('2027-03-26','Good Friday',FALSE,'gov.za'),
('2027-03-29','Family Day',FALSE,'gov.za'),
('2027-04-27','Freedom Day',FALSE,'gov.za'),
('2027-05-01','Workers'' Day',FALSE,'gov.za'),
('2027-06-16','Youth Day',FALSE,'gov.za'),
('2027-08-09','National Women''s Day',FALSE,'gov.za'),
('2027-09-24','Heritage Day',FALSE,'gov.za'),
('2027-12-16','Day of Reconciliation',FALSE,'gov.za'),
('2027-12-25','Christmas Day',FALSE,'gov.za'),
('2027-12-26','Day of Goodwill',FALSE,'gov.za')
ON CONFLICT (holiday_date) DO UPDATE SET
  name=EXCLUDED.name, country_code='ZA', observed=EXCLUDED.observed,
  source=EXCLUDED.source, updated_at=NOW();
