-- CRM-2 regular-practitioner clinic-hours inheritance.
-- Regular practitioners inherit location hours when no explicit recurring staff window exists.
-- A recurring closed weekday is stored explicitly so "no rows" can safely mean "inherit".

CREATE TABLE IF NOT EXISTS staff_recurring_day_closures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
  location_id BIGINT REFERENCES locations(id) ON DELETE CASCADE,
  day_of_week SMALLINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT staff_recurring_day_closures_day_check CHECK (day_of_week BETWEEN 0 AND 6)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_staff_recurring_day_closures_global
  ON staff_recurring_day_closures(staff_id, day_of_week)
  WHERE location_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_staff_recurring_day_closures_location
  ON staff_recurring_day_closures(staff_id, location_id, day_of_week)
  WHERE location_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_staff_recurring_day_closures_lookup
  ON staff_recurring_day_closures(staff_id, day_of_week, location_id);
