-- P-PRIV-4: gated data-subject rights workflow.
-- Stores workflow state and minimal verification/authorization evidence only.
-- No destructive client-data operation is introduced by this migration.

CREATE TABLE IF NOT EXISTS privacy_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
  requested_action TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'identity_pending',
  verification_method TEXT,
  identity_verified_at TIMESTAMPTZ,
  owner_authorized_at TIMESTAMPTZ,
  policy_version TEXT,
  preview_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT privacy_requests_action_check
    CHECK (requested_action IN ('access','correction','deletion','deidentification','objection')),
  CONSTRAINT privacy_requests_status_check
    CHECK (status IN ('identity_pending','verified','owner_authorized','blocked','closed')),
  CONSTRAINT privacy_requests_verification_method_check
    CHECK (verification_method IS NULL OR verification_method IN ('verified_whatsapp_contact','in_person_identity_check','document_checked_offline','other_owner_attested'))
);

CREATE INDEX IF NOT EXISTS idx_privacy_requests_client_id
  ON privacy_requests(client_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_privacy_requests_status
  ON privacy_requests(status, created_at DESC);
