-- Governed staff leave requests.
-- Abigail (employee practitioner) requests leave; Christel approves/declines.
-- Approval creates canonical staff_schedule_exceptions; requests never affect availability while pending.
CREATE TABLE IF NOT EXISTS staff_leave_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL REFERENCES staff(id) ON DELETE RESTRICT,
  requested_by_admin_id BIGINT NOT NULL REFERENCES staff_admin_accounts(id) ON DELETE RESTRICT,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  decided_by_admin_id BIGINT REFERENCES staff_admin_accounts(id) ON DELETE SET NULL,
  decided_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT staff_leave_requests_dates CHECK (end_date >= start_date),
  CONSTRAINT staff_leave_requests_status CHECK (status IN ('pending','approved','declined','cancelled'))
);
CREATE INDEX IF NOT EXISTS idx_staff_leave_requests_pending ON staff_leave_requests(status, created_at);
CREATE INDEX IF NOT EXISTS idx_staff_leave_requests_staff ON staff_leave_requests(staff_id, start_date, end_date);
