-- Durable prepaid massage-package capability.
-- Sports Massage — Monthly Package: R1,400, four 50-minute sessions, valid for 30 days.
-- Package sessions are not ordinary direct-booking catalogue products.

CREATE TABLE IF NOT EXISTS service_packages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  family_name TEXT NOT NULL DEFAULT 'Massage Packages',
  session_service_id BIGINT NOT NULL REFERENCES services(id) ON DELETE RESTRICT,
  package_price NUMERIC(12,2) NOT NULL,
  sessions_included INTEGER NOT NULL,
  validity_days INTEGER NOT NULL,
  cancellation_notice_hours INTEGER NOT NULL DEFAULT 24,
  customer_description TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT service_packages_price_check CHECK (package_price >= 0),
  CONSTRAINT service_packages_sessions_check CHECK (sessions_included > 0),
  CONSTRAINT service_packages_validity_check CHECK (validity_days > 0),
  CONSTRAINT service_packages_status_check CHECK (status IN ('active','inactive'))
);

CREATE TABLE IF NOT EXISTS client_package_entitlements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  package_id BIGINT NOT NULL REFERENCES service_packages(id) ON DELETE RESTRICT,
  payment_status TEXT NOT NULL DEFAULT 'paid',
  purchase_price NUMERIC(12,2) NOT NULL,
  purchased_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  starts_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  sessions_total INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  activated_by_admin_id BIGINT REFERENCES staff_admin_accounts(id) ON DELETE SET NULL,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT client_package_entitlements_payment_check CHECK (payment_status IN ('paid','refunded','void')),
  CONSTRAINT client_package_entitlements_status_check CHECK (status IN ('active','cancelled','exhausted')),
  CONSTRAINT client_package_entitlements_sessions_check CHECK (sessions_total > 0),
  CONSTRAINT client_package_entitlements_window_check CHECK (expires_at > starts_at)
);

CREATE INDEX IF NOT EXISTS idx_client_package_entitlements_client
  ON client_package_entitlements(client_id, status, expires_at);

CREATE TABLE IF NOT EXISTS package_session_redemptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entitlement_id BIGINT NOT NULL REFERENCES client_package_entitlements(id) ON DELETE CASCADE,
  appointment_id BIGINT NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'reserved',
  reserved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  redeemed_at TIMESTAMPTZ,
  released_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT package_session_redemptions_status_check CHECK (status IN ('reserved','redeemed','released')),
  CONSTRAINT package_session_redemptions_appointment_unique UNIQUE (appointment_id)
);

CREATE INDEX IF NOT EXISTS idx_package_session_redemptions_entitlement
  ON package_session_redemptions(entitlement_id, status);

CREATE TABLE IF NOT EXISTS package_enquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
  package_id BIGINT NOT NULL REFERENCES service_packages(id) ON DELETE RESTRICT,
  normalized_whatsapp TEXT,
  status TEXT NOT NULL DEFAULT 'open',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT package_enquiries_status_check CHECK (status IN ('open','contacted','converted','closed'))
);

-- Package-only underlying calendar service. R350 is the package's effective per-session
-- value; the booking trigger below changes the appointment amount due to R0 because
-- the client has prepaid the R1,400 entitlement.
INSERT INTO services (
  category_id, name, duration_minutes, processing_time_minutes, extra_time_minutes,
  variable_price, price, display_price, display_order, is_default, status,
  external_source, external_id
)
SELECT sc.id, 'Sports Massage — Package Session', 50, 0, 0,
       FALSE, 350, 'Prepaid package session', 900, FALSE, 'active',
       'shiloh_package', 'sports-massage-monthly-session'
  FROM service_categories sc
 WHERE LOWER(sc.name) = 'massage'
ON CONFLICT (external_source, external_id) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name = EXCLUDED.name,
  duration_minutes = 50,
  price = 350,
  display_price = 'Prepaid package session',
  status = 'active',
  updated_at = NOW();

-- Package session eligibility follows the authoritative active client-bookable
-- practitioner set already mapped to at least one Sports Massage service.
INSERT INTO staff_services (staff_id, service_id)
SELECT DISTINCT ss.staff_id, package_session.id
  FROM staff_services ss
  JOIN services sports ON sports.id = ss.service_id
  JOIN staff st ON st.id = ss.staff_id
  CROSS JOIN LATERAL (
    SELECT id FROM services
     WHERE external_source = 'shiloh_package'
       AND external_id = 'sports-massage-monthly-session'
     LIMIT 1
  ) package_session
 WHERE sports.status = 'active'
   AND LOWER(sports.name) LIKE '%sports massage%'
   AND st.status = 'active'
   AND st.resource_type = 'practitioner'
   AND st.client_bookable = TRUE
ON CONFLICT (staff_id, service_id) DO NOTHING;

INSERT INTO service_packages (
  slug, name, family_name, session_service_id, package_price, sessions_included,
  validity_days, cancellation_notice_hours, customer_description, status
)
SELECT 'sports-massage-monthly',
       'Sports Massage — Monthly Package',
       'Massage Packages',
       s.id,
       1400,
       4,
       30,
       24,
       'Four 50-minute Sports Massage sessions. Paid in advance. Valid for 30 days from activation.',
       'active'
  FROM services s
 WHERE s.external_source = 'shiloh_package'
   AND s.external_id = 'sports-massage-monthly-session'
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  family_name = EXCLUDED.family_name,
  session_service_id = EXCLUDED.session_service_id,
  package_price = 1400,
  sessions_included = 4,
  validity_days = 30,
  cancellation_notice_hours = 24,
  customer_description = EXCLUDED.customer_description,
  status = 'active',
  updated_at = NOW();

-- Allocate one prepaid credit atomically whenever the package-only service is
-- attached to an appointment. This is the fail-closed entitlement boundary.
CREATE OR REPLACE FUNCTION shiloh_allocate_package_session()
RETURNS TRIGGER AS $$
DECLARE
  v_client_id BIGINT;
  v_starts_at TIMESTAMPTZ;
  v_package_id BIGINT;
  v_entitlement_id BIGINT;
  v_sessions_total INTEGER;
  v_used INTEGER;
BEGIN
  SELECT sp.id INTO v_package_id
    FROM service_packages sp
   WHERE sp.session_service_id = NEW.service_id
     AND sp.status = 'active'
   LIMIT 1;

  IF v_package_id IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT a.client_id, a.starts_at INTO v_client_id, v_starts_at
    FROM appointments a
   WHERE a.id = NEW.appointment_id
   FOR UPDATE;

  SELECT e.id, e.sessions_total INTO v_entitlement_id, v_sessions_total
    FROM client_package_entitlements e
   WHERE e.client_id = v_client_id
     AND e.package_id = v_package_id
     AND e.status = 'active'
     AND e.payment_status = 'paid'
     AND NOW() >= e.starts_at
     AND NOW() < e.expires_at
     AND v_starts_at >= e.starts_at
     AND v_starts_at < e.expires_at
   ORDER BY e.expires_at, e.id
   FOR UPDATE
   LIMIT 1;

  IF v_entitlement_id IS NULL THEN
    RAISE EXCEPTION 'PACKAGE_ENTITLEMENT_REQUIRED' USING ERRCODE = 'P0001';
  END IF;

  SELECT COUNT(*)::INTEGER INTO v_used
    FROM package_session_redemptions r
   WHERE r.entitlement_id = v_entitlement_id
     AND r.status IN ('reserved','redeemed');

  IF v_used >= v_sessions_total THEN
    RAISE EXCEPTION 'PACKAGE_CREDITS_EXHAUSTED' USING ERRCODE = 'P0001';
  END IF;

  NEW.price_snapshot := 0;
  INSERT INTO package_session_redemptions (entitlement_id, appointment_id, status)
  VALUES (v_entitlement_id, NEW.appointment_id, 'reserved');

  UPDATE appointments
     SET total_price = 0,
         notes = CONCAT_WS(E'\n', NULLIF(notes, ''), 'Prepaid Sports Massage monthly package session'),
         updated_at = NOW()
   WHERE id = NEW.appointment_id;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_allocate_package_session ON appointment_services;
CREATE TRIGGER trg_allocate_package_session
BEFORE INSERT ON appointment_services
FOR EACH ROW EXECUTE FUNCTION shiloh_allocate_package_session();

-- Completed appointments consume a credit. Cancelled/no-show appointments release
-- it; the 24-hour cancellation notice is communicated to clients but no automatic
-- punitive forfeiture is invented without an explicit clinic rule.
CREATE OR REPLACE FUNCTION shiloh_sync_package_redemption_status()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = OLD.status THEN
    RETURN NEW;
  END IF;

  IF NEW.status = 'completed' THEN
    UPDATE package_session_redemptions
       SET status = 'redeemed', redeemed_at = NOW(), released_at = NULL, updated_at = NOW()
     WHERE appointment_id = NEW.id AND status = 'reserved';
  ELSIF NEW.status IN ('cancelled','no_show') THEN
    UPDATE package_session_redemptions
       SET status = 'released', released_at = NOW(), updated_at = NOW()
     WHERE appointment_id = NEW.id AND status = 'reserved';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sync_package_redemption_status ON appointments;
CREATE TRIGGER trg_sync_package_redemption_status
AFTER UPDATE OF status ON appointments
FOR EACH ROW EXECUTE FUNCTION shiloh_sync_package_redemption_status();
