-- Couples Massage self-service foundation.
-- Business authority: 90 minutes, R1080, fixed Abigail + Christel.
-- Companion mobile is appointment-scoped booking backup contact only; it is not CRM/marketing identity.

CREATE TABLE IF NOT EXISTS couples_booking_intents (
  phone VARCHAR(32) PRIMARY KEY,
  lead_client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
  state TEXT NOT NULL DEFAULT 'choose_date',
  selected_date DATE,
  selected_starts_at TIMESTAMPTZ,
  selected_ends_at TIMESTAMPTZ,
  companion_name TEXT,
  companion_mobile VARCHAR(32),
  policy_version TEXT,
  policy_accepted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT couples_booking_intents_state_check CHECK (
    state IN ('choose_date','choose_time','companion_name','companion_mobile','review','awaiting_policy_acceptance')
  ),
  CONSTRAINT couples_booking_intents_interval_check CHECK (
    (selected_starts_at IS NULL AND selected_ends_at IS NULL)
    OR (selected_starts_at IS NOT NULL AND selected_ends_at IS NOT NULL AND selected_ends_at > selected_starts_at)
  )
);

CREATE TABLE IF NOT EXISTS appointment_companions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id BIGINT NOT NULL UNIQUE REFERENCES appointments(id) ON DELETE CASCADE,
  display_name TEXT NOT NULL,
  normalized_mobile VARCHAR(32) NOT NULL,
  contact_role TEXT NOT NULL DEFAULT 'booking_backup',
  marketing_consent BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT appointment_companions_contact_role_check CHECK (contact_role = 'booking_backup'),
  CONSTRAINT appointment_companions_no_marketing_check CHECK (marketing_consent = FALSE)
);

CREATE INDEX IF NOT EXISTS idx_appointment_companions_mobile
  ON appointment_companions(normalized_mobile);

DO $$
DECLARE
  massage_category_id BIGINT;
  couples_service_id BIGINT;
  abigail_id BIGINT;
  christel_id BIGINT;
  conflicting_service_count INTEGER;
  extra_mapping_count INTEGER;
BEGIN
  SELECT id INTO STRICT massage_category_id
    FROM service_categories
   WHERE name = 'Massage' AND status = 'active';

  SELECT COUNT(*)::int INTO conflicting_service_count
    FROM services
   WHERE LOWER(TRIM(name)) = 'couples massage'
     AND NOT (external_source = 'shiloh_special' AND external_id = 'couples-massage-v1');
  IF conflicting_service_count <> 0 THEN
    RAISE EXCEPTION 'Couples Massage foundation blocked: conflicting canonical service identity exists';
  END IF;

  INSERT INTO services (
    category_id, name, duration_minutes, processing_time_minutes, extra_time_minutes,
    variable_price, price, display_price, display_order, status, external_source, external_id
  ) VALUES (
    massage_category_id, 'Couples Massage', 90, 0, 0,
    FALSE, 1080.00, 'R1,080', -100, 'active', 'shiloh_special', 'couples-massage-v1'
  )
  ON CONFLICT (external_source, external_id) DO UPDATE SET
    category_id = EXCLUDED.category_id,
    name = EXCLUDED.name,
    duration_minutes = EXCLUDED.duration_minutes,
    processing_time_minutes = 0,
    extra_time_minutes = 0,
    variable_price = FALSE,
    price = EXCLUDED.price,
    display_price = EXCLUDED.display_price,
    display_order = EXCLUDED.display_order,
    status = 'active',
    updated_at = NOW()
  RETURNING id INTO couples_service_id;

  SELECT id INTO STRICT abigail_id
    FROM staff
   WHERE LOWER(TRIM(display_name)) = 'abigail'
     AND status = 'active'
     AND resource_type = 'practitioner';

  SELECT id INTO STRICT christel_id
    FROM staff
   WHERE LOWER(TRIM(display_name)) = 'christel'
     AND status = 'active'
     AND resource_type = 'practitioner';

  INSERT INTO staff_services (staff_id, service_id)
  VALUES (abigail_id, couples_service_id), (christel_id, couples_service_id)
  ON CONFLICT (staff_id, service_id) DO NOTHING;

  SELECT COUNT(*)::int INTO extra_mapping_count
    FROM staff_services
   WHERE service_id = couples_service_id
     AND staff_id NOT IN (abigail_id, christel_id);
  IF extra_mapping_count <> 0 THEN
    RAISE EXCEPTION 'Couples Massage foundation blocked: service has an unapproved practitioner mapping';
  END IF;

  IF (SELECT COUNT(*) FROM staff_services WHERE service_id = couples_service_id AND staff_id IN (abigail_id, christel_id)) <> 2 THEN
    RAISE EXCEPTION 'Couples Massage foundation blocked: exact Abigail + Christel mapping was not established';
  END IF;
END;
$$;
