-- SHILOH-STAFF-BROWSER-SESSION-BOUNDARY
-- Server-side opaque, revocable staff/Admin browser sessions.
-- Stores only cryptographic hashes of browser session and authentication challenge secrets.

CREATE TABLE IF NOT EXISTS staff_browser_auth_challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id BIGINT NOT NULL REFERENCES staff_admin_accounts(id) ON DELETE CASCADE,
  challenge_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  attempt_count INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL DEFAULT 5,
  last_attempt_at TIMESTAMPTZ,
  request_fingerprint_hash TEXT,
  CONSTRAINT staff_browser_auth_challenge_hash_check CHECK (challenge_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT staff_browser_auth_challenge_expiry_check CHECK (expires_at > created_at),
  CONSTRAINT staff_browser_auth_challenge_attempt_count_check CHECK (attempt_count >= 0),
  CONSTRAINT staff_browser_auth_challenge_max_attempts_check CHECK (max_attempts BETWEEN 1 AND 10),
  CONSTRAINT staff_browser_auth_challenge_fingerprint_check CHECK (request_fingerprint_hash IS NULL OR request_fingerprint_hash ~ '^[0-9a-f]{64}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_staff_browser_open_challenge_per_admin
  ON staff_browser_auth_challenges(admin_id)
  WHERE consumed_at IS NULL AND revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_staff_browser_auth_challenges_expiry
  ON staff_browser_auth_challenges(expires_at);

CREATE TABLE IF NOT EXISTS staff_browser_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id BIGINT NOT NULL REFERENCES staff_admin_accounts(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  csrf_hash TEXT NOT NULL,
  issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,
  revoke_reason TEXT,
  last_used_at TIMESTAMPTZ,
  rotated_from_session_id BIGINT REFERENCES staff_browser_sessions(id) ON DELETE SET NULL,
  client_fingerprint_hash TEXT,
  CONSTRAINT staff_browser_session_token_hash_check CHECK (token_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT staff_browser_session_csrf_hash_check CHECK (csrf_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT staff_browser_session_expiry_check CHECK (expires_at > issued_at),
  CONSTRAINT staff_browser_session_revoke_reason_check CHECK (revoke_reason IS NULL OR length(revoke_reason) BETWEEN 1 AND 40),
  CONSTRAINT staff_browser_session_fingerprint_check CHECK (client_fingerprint_hash IS NULL OR client_fingerprint_hash ~ '^[0-9a-f]{64}$')
);

CREATE INDEX IF NOT EXISTS idx_staff_browser_sessions_admin_active
  ON staff_browser_sessions(admin_id, expires_at DESC)
  WHERE revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_staff_browser_sessions_expiry
  ON staff_browser_sessions(expires_at)
  WHERE revoked_at IS NULL;
