-- SHILOH-EMERGENCY-CHRISTEL-CALENDAR-BOOKING
-- One-time browser bootstrap secrets are never stored in plaintext.
-- This table is not scheduling truth; it only bridges Christel's authenticated
-- WhatsApp Admin identity into the existing opaque staff_browser_sessions boundary.

CREATE TABLE IF NOT EXISTS staff_browser_emergency_bootstraps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id BIGINT NOT NULL REFERENCES staff_admin_accounts(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  issued_via TEXT NOT NULL,
  CONSTRAINT staff_browser_emergency_bootstrap_token_hash_check CHECK (token_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT staff_browser_emergency_bootstrap_expiry_check CHECK (expires_at > issued_at),
  CONSTRAINT staff_browser_emergency_bootstrap_channel_check CHECK (issued_via = 'whatsapp_admin')
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_staff_browser_open_emergency_bootstrap_per_admin
  ON staff_browser_emergency_bootstraps(admin_id)
  WHERE consumed_at IS NULL AND revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_staff_browser_emergency_bootstraps_expiry
  ON staff_browser_emergency_bootstraps(expires_at)
  WHERE consumed_at IS NULL AND revoked_at IS NULL;
