-- SHILOH-WS-10-PROVIDER-INDEPENDENT-STAFF-AUTH
-- Additive TOTP, recovery-code, rate-limit, break-glass, and audit state.
-- Plaintext TOTP seeds, otpauth URIs, OTP values, recovery codes, session
-- tokens, and encryption keys are deliberately not represented in this schema.

ALTER TABLE staff_browser_sessions
  ADD COLUMN IF NOT EXISTS auth_method TEXT NOT NULL DEFAULT 'whatsapp_otp',
  ADD COLUMN IF NOT EXISTS reauthenticated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS recovery_required BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE staff_browser_sessions
   SET reauthenticated_at = issued_at
 WHERE reauthenticated_at IS NULL;

ALTER TABLE staff_browser_sessions
  ALTER COLUMN reauthenticated_at SET NOT NULL,
  ALTER COLUMN reauthenticated_at SET DEFAULT NOW();

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'staff_browser_session_auth_method_check') THEN
    ALTER TABLE staff_browser_sessions ADD CONSTRAINT staff_browser_session_auth_method_check
      CHECK (auth_method IN ('whatsapp_otp', 'totp', 'recovery_code', 'emergency_bootstrap', 'break_glass'));
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS staff_totp_credentials (
  admin_id BIGINT PRIMARY KEY REFERENCES staff_admin_accounts(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending',
  secret_ciphertext TEXT,
  secret_nonce TEXT,
  secret_auth_tag TEXT,
  secret_key_version TEXT,
  pending_secret_ciphertext TEXT,
  pending_secret_nonce TEXT,
  pending_secret_auth_tag TEXT,
  pending_secret_key_version TEXT,
  enrollment_started_at TIMESTAMPTZ,
  enrollment_expires_at TIMESTAMPTZ,
  confirmed_at TIMESTAMPTZ,
  last_accepted_timestep BIGINT,
  failure_window_started_at TIMESTAMPTZ,
  failed_attempt_count INTEGER NOT NULL DEFAULT 0,
  locked_until TIMESTAMPTZ,
  recovery_generation INTEGER NOT NULL DEFAULT 0,
  replacement_required_at TIMESTAMPTZ,
  disabled_at TIMESTAMPTZ,
  disabled_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT staff_totp_credential_status_check CHECK (status IN ('pending', 'active', 'disabled')),
  CONSTRAINT staff_totp_failed_attempt_count_check CHECK (failed_attempt_count >= 0),
  CONSTRAINT staff_totp_recovery_generation_check CHECK (recovery_generation >= 0),
  CONSTRAINT staff_totp_enrollment_expiry_check CHECK (
    enrollment_expires_at IS NULL OR
    (enrollment_started_at IS NOT NULL AND enrollment_expires_at > enrollment_started_at)
  ),
  CONSTRAINT staff_totp_ciphertext_check CHECK (secret_ciphertext IS NULL OR secret_ciphertext ~ '^[A-Za-z0-9_-]+$'),
  CONSTRAINT staff_totp_nonce_check CHECK (secret_nonce IS NULL OR secret_nonce ~ '^[A-Za-z0-9_-]{16}$'),
  CONSTRAINT staff_totp_auth_tag_check CHECK (secret_auth_tag IS NULL OR secret_auth_tag ~ '^[A-Za-z0-9_-]{22}$'),
  CONSTRAINT staff_totp_pending_ciphertext_check CHECK (pending_secret_ciphertext IS NULL OR pending_secret_ciphertext ~ '^[A-Za-z0-9_-]+$'),
  CONSTRAINT staff_totp_pending_nonce_check CHECK (pending_secret_nonce IS NULL OR pending_secret_nonce ~ '^[A-Za-z0-9_-]{16}$'),
  CONSTRAINT staff_totp_pending_auth_tag_check CHECK (pending_secret_auth_tag IS NULL OR pending_secret_auth_tag ~ '^[A-Za-z0-9_-]{22}$')
);

CREATE TABLE IF NOT EXISTS staff_auth_recovery_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id BIGINT NOT NULL REFERENCES staff_admin_accounts(id) ON DELETE CASCADE,
  generation INTEGER NOT NULL,
  code_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  consumed_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  CONSTRAINT staff_auth_recovery_generation_check CHECK (generation > 0),
  CONSTRAINT staff_auth_recovery_hash_check CHECK (code_hash ~ '^scrypt\\$[0-9]+\\$[0-9]+\\$[0-9]+\\$[A-Za-z0-9_-]+\\$[A-Za-z0-9_-]+$')
);

CREATE INDEX IF NOT EXISTS idx_staff_auth_recovery_codes_active
  ON staff_auth_recovery_codes(admin_id, generation)
  WHERE consumed_at IS NULL AND revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS staff_auth_rate_limits (
  source_fingerprint_hash TEXT PRIMARY KEY,
  window_started_at TIMESTAMPTZ NOT NULL,
  failed_attempt_count INTEGER NOT NULL DEFAULT 0,
  locked_until TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT staff_auth_rate_source_hash_check CHECK (source_fingerprint_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT staff_auth_rate_attempt_count_check CHECK (failed_attempt_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_staff_auth_rate_limits_expiry
  ON staff_auth_rate_limits(updated_at);

CREATE TABLE IF NOT EXISTS staff_auth_break_glass_bootstraps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id BIGINT NOT NULL REFERENCES staff_admin_accounts(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  operator_reference TEXT NOT NULL,
  control_reference TEXT NOT NULL,
  CONSTRAINT staff_auth_break_glass_token_hash_check CHECK (token_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT staff_auth_break_glass_expiry_check CHECK (expires_at > issued_at),
  CONSTRAINT staff_auth_break_glass_operator_check CHECK (length(operator_reference) BETWEEN 2 AND 120),
  CONSTRAINT staff_auth_break_glass_control_check CHECK (length(control_reference) BETWEEN 2 AND 120)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_staff_auth_open_break_glass_per_admin
  ON staff_auth_break_glass_bootstraps(admin_id)
  WHERE consumed_at IS NULL AND revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS staff_auth_security_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL,
  operator_admin_id BIGINT,
  subject_admin_id BIGINT,
  auth_method TEXT,
  reason TEXT,
  request_fingerprint_hash TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT staff_auth_event_type_check CHECK (event_type ~ '^[a-z][a-z0-9_]{2,63}$'),
  CONSTRAINT staff_auth_event_method_check CHECK (auth_method IS NULL OR auth_method IN ('whatsapp_otp', 'totp', 'recovery_code', 'emergency_bootstrap', 'break_glass', 'control')),
  CONSTRAINT staff_auth_event_reason_check CHECK (reason IS NULL OR length(reason) BETWEEN 1 AND 240),
  CONSTRAINT staff_auth_event_fingerprint_check CHECK (request_fingerprint_hash IS NULL OR request_fingerprint_hash ~ '^[0-9a-f]{64}$')
);

CREATE INDEX IF NOT EXISTS idx_staff_auth_security_events_subject
  ON staff_auth_security_events(subject_admin_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_staff_auth_security_events_created
  ON staff_auth_security_events(created_at DESC);

-- JP receives the explicit ability to reset another staff authenticator.
-- Runtime authorization also rejects privileged self-reset.
UPDATE staff_admin_accounts
   SET permissions = COALESCE(permissions, '{}'::jsonb) || '{"staff_auth:reset":true}'::jsonb,
       updated_at = NOW()
 WHERE normalized_whatsapp = '27725128605'
   AND active = TRUE;
