-- SHILOH-CALENDAR-OPERATIONAL-ASSURANCE-CUTOVER
-- Authenticated Calendar role/capability authority, browser mutation idempotency,
-- and durable post-commit provider synchronization outbox.

ALTER TABLE staff_admin_accounts
  ADD COLUMN IF NOT EXISTS calendar_role TEXT NOT NULL DEFAULT 'read_only';

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='staff_admin_calendar_role_check') THEN
    ALTER TABLE staff_admin_accounts ADD CONSTRAINT staff_admin_calendar_role_check
      CHECK (calendar_role IN ('super_admin','operations_admin','read_only'));
  END IF;
END $$;

-- Approved operating model: JP governs, Christel operates, all other active Admin/staff accounts read only.
UPDATE staff_admin_accounts
   SET calendar_role = CASE
         WHEN LOWER(display_name) = 'jean-pierre' THEN 'super_admin'
         WHEN LOWER(display_name) = 'christel' THEN 'operations_admin'
         ELSE 'read_only'
       END,
       calendar_scope = CASE WHEN active = TRUE THEN 'all_business' ELSE calendar_scope END,
       permissions = COALESCE(permissions, '{}'::jsonb) ||
         CASE
           WHEN active = FALSE THEN
             '{"calendar:read":false,"calendar:create":false,"calendar:edit":false,"calendar:reschedule":false,"calendar:cancel":false,"calendar:sync_retry":false}'::jsonb
           WHEN LOWER(display_name) IN ('jean-pierre','christel') THEN
             '{"calendar:read":true,"calendar:create":true,"calendar:edit":true,"calendar:reschedule":true,"calendar:cancel":true,"calendar:sync_retry":true,"client:lookup":true}'::jsonb
           ELSE
             '{"calendar:read":true,"calendar:create":false,"calendar:edit":false,"calendar:reschedule":false,"calendar:cancel":false,"calendar:sync_retry":false}'::jsonb
         END,
       updated_at = NOW();

CREATE TABLE IF NOT EXISTS calendar_mutation_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_admin_id BIGINT NOT NULL REFERENCES staff_admin_accounts(id) ON DELETE RESTRICT,
  operation TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  request_hash TEXT NOT NULL,
  appointment_id BIGINT REFERENCES appointments(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'processing',
  response_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  CONSTRAINT calendar_mutation_operation_check CHECK (operation IN ('create','edit','reschedule','cancel','prepare','discard','sync_retry')),
  CONSTRAINT calendar_mutation_status_check CHECK (status IN ('processing','succeeded','failed')),
  CONSTRAINT calendar_mutation_key_check CHECK (length(idempotency_key) BETWEEN 8 AND 160),
  CONSTRAINT calendar_mutation_request_hash_check CHECK (request_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT calendar_mutation_unique UNIQUE (actor_admin_id, operation, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_calendar_mutation_requests_appointment
  ON calendar_mutation_requests(appointment_id, created_at DESC);

CREATE TABLE IF NOT EXISTS calendar_provider_sync_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mutation_request_id BIGINT NOT NULL REFERENCES calendar_mutation_requests(id) ON DELETE CASCADE,
  appointment_id BIGINT NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  operation TEXT NOT NULL,
  payload_json JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  attempt_count INTEGER NOT NULL DEFAULT 0,
  provider_calendar_id TEXT,
  provider_event_id TEXT,
  last_error TEXT,
  next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_attempt_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT calendar_provider_sync_provider_check CHECK (provider IN ('shared_google','practitioner_google')),
  CONSTRAINT calendar_provider_sync_operation_check CHECK (operation IN ('create','update','cancel')),
  CONSTRAINT calendar_provider_sync_status_check CHECK (status IN ('pending','processing','synced','failed','skipped')),
  CONSTRAINT calendar_provider_sync_attempt_count_check CHECK (attempt_count >= 0),
  CONSTRAINT calendar_provider_sync_unique UNIQUE (mutation_request_id, provider)
);

CREATE INDEX IF NOT EXISTS idx_calendar_provider_sync_retry
  ON calendar_provider_sync_jobs(status, next_attempt_at, id)
  WHERE status IN ('pending','failed');

CREATE INDEX IF NOT EXISTS idx_calendar_provider_sync_order
  ON calendar_provider_sync_jobs(appointment_id, provider, id)
  WHERE status IN ('pending','processing','failed');

-- Historical appointment provider rows are deliberately untouched. New provider identifiers
-- continue to be stored in appointment_calendar_events and are linked to the outbox audit trail.
