-- Shiloh CRM V2 clean client master.
--
-- This is an additive, zero-backfill migration. It deliberately does not read
-- or copy legacy client, contact, alias, evidence, Goldie or appointment data.

CREATE TABLE IF NOT EXISTS crm_v2_clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (BTRIM(name) <> '' AND CHAR_LENGTH(name) <= 120),
  normalized_mobile TEXT NOT NULL CHECK (normalized_mobile ~ '^27[678][0-9]{8}$'),
  date_of_birth DATE,
  gender TEXT,
  profile_status TEXT NOT NULL DEFAULT 'minimal'
    CHECK (profile_status IN ('minimal', 'registered')),
  mobile_verified_at TIMESTAMPTZ,
  source TEXT NOT NULL CHECK (BTRIM(source) <> ''),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
  provenance JSONB NOT NULL DEFAULT '{}'::jsonb
    CHECK (jsonb_typeof(provenance) = 'object'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT crm_v2_registered_profile_complete CHECK (
    profile_status <> 'registered'
    OR (date_of_birth IS NOT NULL AND gender IS NOT NULL AND BTRIM(gender) <> '')
  ),
  CONSTRAINT crm_v2_date_of_birth_floor CHECK (
    date_of_birth IS NULL OR date_of_birth >= DATE '1900-01-01'
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_crm_v2_clients_active_mobile
  ON crm_v2_clients(normalized_mobile)
  WHERE status = 'active';

CREATE INDEX IF NOT EXISTS idx_crm_v2_clients_name_search
  ON crm_v2_clients(LOWER(name));

CREATE INDEX IF NOT EXISTS idx_crm_v2_clients_status_updated
  ON crm_v2_clients(status, updated_at DESC, id DESC);

-- Compatibility seam only: legacy/future appointments keep their existing
-- client_id and snapshots. No appointment row is populated or changed here.
ALTER TABLE appointments
  ADD COLUMN IF NOT EXISTS crm_v2_client_id BIGINT
    REFERENCES crm_v2_clients(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_appointments_crm_v2_client_id
  ON appointments(crm_v2_client_id)
  WHERE crm_v2_client_id IS NOT NULL;

COMMENT ON TABLE crm_v2_clients IS
  'Clean Shiloh CRM V2 client master. Exact normalized mobile is the only automatic client-resolution key.';

COMMENT ON COLUMN appointments.crm_v2_client_id IS
  'Nullable cutover seam for new CRM V2 bookings. Existing appointments remain on their legacy client_id and stored snapshots.';
