-- SHILOH-STAFF-PASSKEY-AUTH-V1
-- Additive WebAuthn credential/challenge state attached to canonical staff_admin_accounts.
-- No biometric data, private keys, session tokens, TOTP secrets, recovery codes, or provider credentials are stored here.

ALTER TABLE staff_browser_sessions
  DROP CONSTRAINT IF EXISTS staff_browser_session_auth_method_check;
ALTER TABLE staff_browser_sessions
  ADD CONSTRAINT staff_browser_session_auth_method_check
    CHECK (auth_method IN ('whatsapp_otp', 'totp', 'recovery_code', 'emergency_bootstrap', 'break_glass', 'passkey'));

ALTER TABLE staff_auth_security_events
  DROP CONSTRAINT IF EXISTS staff_auth_event_method_check;
ALTER TABLE staff_auth_security_events
  ADD CONSTRAINT staff_auth_event_method_check
    CHECK (auth_method IS NULL OR auth_method IN ('whatsapp_otp', 'totp', 'recovery_code', 'emergency_bootstrap', 'break_glass', 'control', 'passkey'));

CREATE TABLE IF NOT EXISTS staff_auth_passkey_credentials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id BIGINT NOT NULL REFERENCES staff_admin_accounts(id) ON DELETE CASCADE,
  credential_id TEXT NOT NULL UNIQUE,
  public_key_spki BYTEA NOT NULL,
  algorithm INTEGER NOT NULL,
  sign_count BIGINT NOT NULL DEFAULT 0,
  transports JSONB NOT NULL DEFAULT '[]'::jsonb,
  backed_up BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_used_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  revoked_by_admin_id BIGINT REFERENCES staff_admin_accounts(id) ON DELETE SET NULL,
  CONSTRAINT staff_auth_passkey_credential_id_check CHECK (credential_id ~ '^[A-Za-z0-9_-]{16,1024}$'),
  CONSTRAINT staff_auth_passkey_algorithm_check CHECK (algorithm IN (-7, -8, -257)),
  CONSTRAINT staff_auth_passkey_sign_count_check CHECK (sign_count >= 0),
  CONSTRAINT staff_auth_passkey_transports_check CHECK (jsonb_typeof(transports) = 'array')
);

CREATE INDEX IF NOT EXISTS idx_staff_auth_passkeys_admin
  ON staff_auth_passkey_credentials(admin_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_staff_auth_passkeys_active
  ON staff_auth_passkey_credentials(admin_id, last_used_at DESC NULLS LAST)
  WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS staff_auth_webauthn_challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  challenge_hash TEXT NOT NULL UNIQUE,
  purpose TEXT NOT NULL,
  admin_id BIGINT REFERENCES staff_admin_accounts(id) ON DELETE CASCADE,
  session_id BIGINT REFERENCES staff_browser_sessions(id) ON DELETE CASCADE,
  request_fingerprint_hash TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  CONSTRAINT staff_auth_webauthn_challenge_hash_check CHECK (challenge_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT staff_auth_webauthn_purpose_check CHECK (purpose IN ('registration', 'authentication')),
  CONSTRAINT staff_auth_webauthn_expiry_check CHECK (expires_at > created_at),
  CONSTRAINT staff_auth_webauthn_fingerprint_check CHECK (request_fingerprint_hash IS NULL OR request_fingerprint_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT staff_auth_webauthn_registration_binding_check CHECK (
    (purpose = 'registration' AND admin_id IS NOT NULL AND session_id IS NOT NULL)
    OR (purpose = 'authentication' AND admin_id IS NULL AND session_id IS NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_staff_auth_webauthn_challenges_expiry
  ON staff_auth_webauthn_challenges(expires_at)
  WHERE consumed_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_staff_auth_webauthn_registration_session
  ON staff_auth_webauthn_challenges(session_id, expires_at DESC)
  WHERE purpose = 'registration' AND consumed_at IS NULL;
