-- SHILOH-STAFF-WHATSAPP-PASSKEY-BOOTSTRAP-V1
-- Add a narrowly purpose-built, hashed, single-use passkey-bootstrap token authority.
-- The released break-glass table is deliberately not reused: its existing issue/consume
-- semantics can revoke sessions and enter recovery-required state, which is a different
-- security purpose and must not be coupled to ordinary staff onboarding.
-- No plaintext setup token, biometric, private key, session token, TOTP secret, recovery code,
-- provider credential, role, scope, or capability is stored or broadened by this migration.

CREATE TABLE IF NOT EXISTS staff_auth_passkey_bootstraps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id BIGINT NOT NULL REFERENCES staff_admin_accounts(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  source TEXT NOT NULL DEFAULT 'whatsapp_self',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT staff_auth_passkey_bootstrap_token_hash_check CHECK (token_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT staff_auth_passkey_bootstrap_expiry_check CHECK (expires_at > issued_at),
  CONSTRAINT staff_auth_passkey_bootstrap_source_check CHECK (source IN ('whatsapp_self'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_staff_auth_open_passkey_bootstrap_per_admin
  ON staff_auth_passkey_bootstraps(admin_id)
  WHERE consumed_at IS NULL AND revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_staff_auth_passkey_bootstraps_expiry
  ON staff_auth_passkey_bootstraps(expires_at)
  WHERE consumed_at IS NULL AND revoked_at IS NULL;

ALTER TABLE staff_auth_webauthn_challenges
  DROP CONSTRAINT IF EXISTS staff_auth_webauthn_purpose_check;
ALTER TABLE staff_auth_webauthn_challenges
  ADD CONSTRAINT staff_auth_webauthn_purpose_check
    CHECK (purpose IN ('registration', 'authentication', 'bootstrap_registration'));

ALTER TABLE staff_auth_webauthn_challenges
  DROP CONSTRAINT IF EXISTS staff_auth_webauthn_registration_binding_check;
ALTER TABLE staff_auth_webauthn_challenges
  ADD CONSTRAINT staff_auth_webauthn_registration_binding_check CHECK (
    (purpose = 'registration' AND admin_id IS NOT NULL AND session_id IS NOT NULL)
    OR (purpose = 'bootstrap_registration' AND admin_id IS NOT NULL AND session_id IS NULL)
    OR (purpose = 'authentication' AND admin_id IS NOT NULL AND session_id IS NULL)
  );

CREATE INDEX IF NOT EXISTS idx_staff_auth_webauthn_bootstrap_registration_admin
  ON staff_auth_webauthn_challenges(admin_id, expires_at DESC)
  WHERE purpose = 'bootstrap_registration' AND consumed_at IS NULL;
